### ISSUE TITLE
Support Apache HttpClient 5

### ISSUE THREAD

**Issue by davidkron** [scribejava/scribejava#1016]
It would be great if the current major version of Apache HttpClient would be supported, which is 5:
https://hc.apache.org/httpcomponents-client-5.1.x/index.html

**Comment by kullfar** [comment]
Hi. It's not an issue.
It's better to submit Pull Requests with such enhances ;-)

**Comment by davidkron** [comment]
You are right, sorry for misusing the issue tracker for this request.

Since we are currently using HttpClient 5 in our project and want to use Scribe as well, I think I will have to write an implementation anyway. So I will create a pull request if I have something working.
