### ISSUE TITLE
Unmaintained?

### ISSUE THREAD

**Issue by Syndlex** [scribejava/scribejava#1047]
Hey,

Is this libary Unmaintained?
Or is it under sanctions from the US or something?

**Comment by kullfar** [comment]
@Syndlex , Hi!

In short - no, library is not unmaintained. And there are no any sanctions.

I'm just lack of time last year, but planning to be back soon.

**Comment by Syndlex** [comment]
Thanks for the Information!
This is a really create project and very easy to integrate!
