### ISSUE TITLE
API Secret currently doesn't allow for an empty string

### ISSUE THREAD

**Issue by Kieveli** [scribejava/scribejava#154]
There are preconditions which require the API secret to be assigned and not an empty string.  This manifests in two identified places (and possibly more):
 1) In the ServiceBuilder ApiSecret method
 2) In the org.scribe.services.HMACSha1SignatureService.getSignature method

This is relevant to integrating with Plaxo who currently has the ApiKey set to 'anonymous' and the secret is an empty string.  See this site for their test client implementation to verify the api key and api secret:
http://www.plaxo.com/pdata/testClient/

**Comment by jdussouillez** [comment]
I have the same issue. The Basic auth password is an empty string and I'm stuck because of this issue.

I tried to inherit the builder to override the `apiSecret` setter but the apiSecret field is `private`. Do you have any workarounds (other than forking the project) ?

**Comment by kullfar** [comment]
Hi, @jdussouillez!

You mean, you need to have such code in your project ```new ServiceBuilder(clientId).apiSecret("")```?

As fast workaround you can override one of this method from ServiceBuilder
```
    @Override
    public OAuth10aService build(DefaultApi10a api) {
        return api.createService(apiKey, apiSecret, callback, scope, debugStream, userAgent, httpClientConfig,
                httpClient);
    }

    @Override
    public OAuth20Service build(DefaultApi20 api) {
        return api.createService(apiKey, apiSecret, callback, scope, responseType, debugStream, userAgent,
                httpClientConfig, httpClient);
    }
```

Just provide "" instead of apiSecret to the api.createService(...)


And I think I will implement method like apiSecretIsEmptyString() without parameters in the next version of ScribeJava.

**Comment by kullfar** [comment]
But can you provide a link to such spec, where api secret is empty string?

**Comment by jdussouillez** [comment]
@kullfar Thanks for the answer. I found a workaround using reflection to set the apiSecret (very dirty hack but it works) in a custom service builder instance.

Unfortunately I can't provide you the spec, it's an old proprietary system we use at work and on premise. And the apiSecret is empty (don't know why, but we can't change it) for the staging environment only.

Here's the temporary workaround we use :

```java
protected static class MyServiceBuilder extends ServiceBuilder {

    public MyServiceBuilder(final String apiKey) {
        super(apiKey);
    }

    @Override
    public ServiceBuilder apiSecret(final String apiSecret) {
        // TODO: delete this workaround (required because the apiSecret can be an empty string).
        // The field is private so we need to use reflection to force the value
        // https://github.com/scribejava/scribejava/issues/154
        try {
            Field field = getClass().getSuperclass().getDeclaredField("apiSecret");
            field.setAccessible(true);
            field.set(this, apiSecret);
        } catch (IllegalAccessException | IllegalArgumentException | NoSuchFieldException | SecurityException ex) {
            throw new IllegalArgumentException("Failed to force apiSecret", ex);
        }
        return this;
    }
}
```

**Comment by kullfar** [comment]
oook, that's it in the master
https://github.com/scribejava/scribejava/commit/8f4891554e5edd4a52d019126d852bda503f0af9
