### ISSUE TITLE
Support for Pinterest OAuth 2 and Pinning

### ISSUE THREAD

**Issue by sonaliparikh** [scribejava/scribejava#267]
Hi Pablo, I was looking to add Pinterest to our solution. Since I'm already using scribe for twitter/facebook/linked-in, I was hoping to use it for Pinterest also. I am not sure of your plans to integrate a new API - is it in the next milestone?
-sonali

**Comment by martinmalek** [comment]
Any updates on this. There is an official API now - https://developers.pinterest.com/docs/api/overview/

**Comment by kullfar** [comment]
Aha. I see your PR https://github.com/scribejava/scribejava/pull/591
will continue there

**Comment by sst89** [comment]
I want to used pinterest api in adobe flash builder air desktop application. If you have any api inbuild library or swf file in flex as3 then please give me link.

**Comment by kullfar** [comment]
I do not, sorry
