### ISSUE TITLE
Setting request headers?

### ISSUE THREAD

**Issue by jplock** [scribejava/scribejava#280]
Is there anyway to expose the Request.setHeaders() method up into the service to support setting arbitrary request headers?  I'm working with an OAuth 1.0a implementation that requires an additional request header to be set in each request.  Thanks.

**Comment by cfrancomme** [comment]
Hi,
In my API i need custom headers each time i send a request to the server.
When doing

    public Token getRequestToken(RequestTuner tuner)
I need to set this headers with a "Accept: application/x-www-form-urlencoded" (yes, that's non-standard, but well... that's how it is)
I would like to be able to modify the request object as it's not possible in OAuth10aServiceImpl.
Or maybe i should Override something else ?
Cheers

**Comment by fernandezpablo85** [comment]
Can't you create a `RequestTuner` that adds the header in the `tune` method?
