### ISSUE TITLE
Custom Response Headers are missing

### ISSUE THREAD

**Issue by praveenthames** [scribejava/scribejava#389]
When making a request using the HEAD method, I am expecting a custom header in the response. I see the Charles Proxy trace shows that the header is present in the actual http response. However, org.scribe.model.Response.getHeaders() does not seem to contain that header variable. Is this a known issue ? Any work-arounds ?

**Comment by kullfar** [comment]
It seems, the issue is quite outdated and not relevant to the currenst state of source code.
If noone interested, I will close issuie on one month
