### ISSUE TITLE
Flickr authorization URL is missing a permissions parameter

### ISSUE THREAD

**Issue by MThoma202** [scribejava/scribejava#412]
When using 1.3.5 with Flickr we need to manually append "&perms=read" to the authorization URL for it to work.

Using the generated authorization URL:
![without_perms_1](https://f.cloud.github.com/assets/4305146/963400/3b7a325e-0502-11e3-8de8-aaae7c772073.png)
![without_perms_2](https://f.cloud.github.com/assets/4305146/963411/7670fdd4-0502-11e3-99a7-130b2752f3d7.png)

With the perms parameter appended to the URL:
![with_perms_1](https://f.cloud.github.com/assets/4305146/963421/ba103398-0502-11e3-8f27-b0a112ee21b9.png)
![with_perms_2](https://f.cloud.github.com/assets/4305146/963423/bc0aceec-0502-11e3-9bb3-1dcfdcce6ff3.png)

**Comment by rogerhu** [comment]
See https://github.com/scribejava/scribejava/pull/763

**Comment by kullfar** [comment]
fixed, Pull Request in the master
