### ISSUE TITLE
TwitterAPI example fails

### ISSUE THREAD

**Issue by laszlomiklosik** [scribejava/scribejava#439]
I took the code from master today morning and tried to run class:

org.scribe.examples.TwitterExample

I successfully get both the request and access tokens, but when requesting the resource using:

OAuthRequest request = new OAuthRequest(Verb.GET, PROTECTED_RESOURCE_URL);

the result is:

{"errors":[{"message":"Could not authenticate you","code":32}]}

and http status code 401.

Is by any chance the apiKey / apiSecret used in the example wrong? I found lots of discussions when searching up the response error message.

**Comment by pi408637535** [comment]
Hi,I encountered some errors. when I'm seeing this article,I couldn't to find "request.addBodyParameter" in   TwitterExample. I'm very doubt. Anybody can help me.

**Comment by kullfar** [comment]
so, what is your problem&

**Comment by kullfar** [comment]
Do you use the latest ScribeJava version? this issue is from 2013

**Comment by pi408637535** [comment]
I'm sure that I'm making user of "3.1.1-SNAPSHOT". when a user verify by phone,I will encounter this issue.
this is my program:      
 
`public class TwitterExample2 {
    private static final String PROTECTED_RESOURCE_URL = "https://api.twitter.com/1.1/account/verify_credentials.json";


    public static void main(String... args) throws IOException {
        final OAuth10aService service = new ServiceBuilder()
                .apiKey("hCxxZ3HDhW12K5McAahxRUrLm")
                .apiSecret("m7CuEiv0WBpMFFyIZF0fRBQ56ZJy1ULm48KyCGYfdbD3xySu8Q")
                .build(TwitterApi.instance());
        String token = "766473911873789956-Pr19hg7wbo3SbVmGfzADV1LEXQg5hpx";
        String token_secret = "jVp6St3Sw5NhjRHvsPptxyWzmhJgsQhzMNT99WGqokIjK";
        String uid = "766473911873789956";
        String screen_name = "gezhu974422073";
        //String rawResponse = String.format("oauth_token=%s&oauth_token_secret=%s&user_id=%s&screen_name=%s&x_auth_expires=0",token,token_secret, uid, screen_name);
        String rawResponse = String.format("oauth_token=%s&oauth_token_secret=%s&user_id=%s&screen_name=%s&x_auth_expires=0",token,token_secret, uid, screen_name);


        final OAuth1AccessToken accessToken = new OAuth1AccessToken(token, token_secret, rawResponse);

        System.out.println("Got the Access Token!");
        System.out.println("(if your curious it looks like this: " + accessToken
                + ", 'rawResponse'='" + accessToken.getRawResponse() + "')");
        System.out.println();

        // Now let's go and ask for a protected resource!
        System.out.println("Now we're going to access a protected resource...");
        final OAuthRequest request = new OAuthRequest(Verb.GET, PROTECTED_RESOURCE_URL, service);
        
        //request.addBodyParameter("status", "this is sparta! *");

        service.signRequest(accessToken, request);


        final Response response = request.send();
        System.out.println("Got it! Lets see what we found...");
        System.out.println();

        System.out.println(response.getBody());
    }
}
`

**Comment by kullfar** [comment]
What for do you need rawResponse, generated by yourself?

**Comment by pi408637535** [comment]
User don't log in by H5 but making use of twitter client. so I couldn't acquire code. I'm only to obtain token,secret,userId(coming from third) and screen_name. I see a construct "OAuth1AccessToken(String token, String tokenSecret, String rawResponse)" so I decide to take advantage of this. I has already tried to log in by H5 that it's perfect but If I log in by client,I will obtain that issue.

**Comment by kullfar** [comment]
What is the "H5"?
Do you need password grant_type?  look at OAuth20Service::getAccessTokenPasswordGrant

**Comment by kullfar** [comment]
btw, seems you obtained broken token

**Comment by kullfar** [comment]
outdated
