### ISSUE TITLE
PlainTextSignatureService does not allow empty secrets (while RFC 5849 does)

### ISSUE THREAD

**Issue by TuomasKiviaho** [scribejava/scribejava#444]
I got unexpectedly "Api secret cant be null or empty string" when testing the library and noticed that PlainTextSignatureService has a empty string precondition check event though spec doesn't require such. Could this be changed to allow empty string by using Preconditions.checkNotNull instead.
- \* \* RFC 5849 \* \* *

3.4.4.  PLAINTEXT
   ...
1.  An "&" character (ASCII code 38), which MUST be included even
      when either secret is empty.

**Comment by kullfar** [comment]
It seems, the issue is quite outdated and not relevant to the currenst state of source code.
If noone interested, I will close issuie on one month
