### ISSUE TITLE
Failure making signed request

### ISSUE THREAD

**Issue by richarth** [scribejava/scribejava#459]
I'm creating an Android app that access Twitter.  The app is able to successfully get a request and access token but when it tries to call the verify credentials API I receive a 'No authentication challenges found' error.  Does anybody know how I solve this?

I've had a look at the debugging logs and it appears to be generating the base string successfully.

**Comment by kullfar** [comment]
It seems, the issue is quite outdated and not relevant to the currenst state of source code.
If noone interested, I will close issuie on one month

**Comment by kullfar** [comment]
It seems, the issue is quite outdated and not relevant to the currenst state of source code.
If noone interested, I will close issuie on one month
