### ISSUE TITLE
Flickr OAuth flow *just stopped working

### ISSUE THREAD

**Issue by bleeckerj** [scribejava/scribejava#475]
It seems that either the folks at Flickr migrated their API endpoints to be SSL, which means that FlickrApi would need a small refactoring to reflect this change:

https://www.flickr.com/help/forum/en-us/72157643180802354/

*or this is a problem that has occurred in the past and has just cropped up again within the last 24 hours:

https://www.flickr.com/help/forum/en-us/72157640083333913/

This appears to only affect Mobile Safari, which is a bit of a nutter and makes me think that it's definitely a service-side issue. (Or, more precisely, when Scribe shepherds the oauth flow, it works fine in Chrome on a desktop. The same flow, running off the same codebase, does _not_ work on Mobile Safari.)

But the problem can be summed up as the oauth flow not getting to step 2. Effectively, after you've logged into the service, you're callback URL isn't requested and you're quietly dumped into your standard Flickr welcome page.

I only bring this up as a flag. Hopefully in the next day or so there'll be some word from Flickr as to if someone just tripped over a cat or they've actually changed their endpoint protocols.

**Comment by kullfar** [comment]
It seems, the issue is quite outdated and not relevant to the currenst state of source code.
If noone interested, I will close issuie on one month
