### ISSUE TITLE
gradle cannot build project with org.scribe dependency when using proguard

### ISSUE THREAD

**Issue by aleb** [scribejava/scribejava#480]
In build.gradle I have the following dependency on the org.scribe:scribe library: 
    compile 'org.scribe:scribe:1.3.5'

Building the release version of the app fails because the proguardRelease target fails:

```
 [exec] Warning: org.scribe.services.CommonsEncoder: can't find referenced class org.apache.commons.codec.binary.Base64
 [exec] Warning: org.scribe.services.CommonsEncoder: can't find referenced class org.apache.commons.codec.binary.Base64
 [exec] Warning: org.scribe.services.DatatypeConverterEncoder: can't find referenced class javax.xml.bind.DatatypeConverter
 [exec] Warning: org.scribe.services.DatatypeConverterEncoder: can't find referenced class javax.xml.bind.DatatypeConverter
 [exec] Warning: there were 4 unresolved references to classes or interfaces.
 [exec] 
 [exec] FAILURE: Build failed with an exception.         You may need to add missing library jars or update their versions.
 [exec]          If your code works fine without the missing classes, you can suppress
 [exec] 
 [exec] 
 [exec] * What went wrong:
 [exec] Execution failed for task ':proguardRelease'.
 [exec]          the warnings with '-dontwarn' options.> java.io.IOException: Please correct the above warnings first.
 [exec]          (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
 [exec] :proguardRelease FAILED
```

I'm not sure what the meaning of the error is.

I've seen this workaround of adding the following two lines to the proguard configuration file: (https://github.com/yasuoza/HBFav-Android/blob/master/HBFav/proguard-android-release.txt)

-dontwarn org.apache.commons.codec.binary.Base64
-dontwarn javax.xml.bind.DatatypeConverter

Is this ok? If so, could you update your readme.md? Thanks!

**Comment by lawrence-dol** [comment]
I dug into this in the source and found that the use of the Apache Base64 encoder is optional and it will fall back to the Java 7 `javax.xml.bind.DatatypeConverter` if the Apache one is not found. This does mean that Scribe is dependent on Java 7 ***or*** Apache Codec.

**Comment by fernandezpablo85** [comment]
I thought it was available since Java 5:

https://docs.oracle.com/javaee/5/api/javax/xml/bind/DatatypeConverter.html

**Comment by lawrence-dol** [comment]
@fernandezpablo85

That's on Java EE. I was looking at Java SE, though I was wrong there too -- it first shows up in Java 6.

> `https://docs.oracle.com/javase/6/docs/api/javax/xml/bind/DatatypeConverter.html`

where the Java 5 page 404's

> `https://docs.oracle.com/javase/1.5.0/docs/api/javax/xml/bind/DatatypeConverter.html == 404 Not Found`

**Comment by fernandezpablo85** [comment]
okay, seems like its safe to assume java6 or more since it has already been
EOLed

**Comment by truefedex** [comment]
I get this exception while using Twitter apis with proguarded app:
java.lang.IllegalArgumentException: class com.github.a.b.e.b declares multiple JSON fields named a

Then I added this to my proguard configuration
-keepclasseswithmembers class com.github.scribejava.core.** { *; }
and error dissappeared
