### ISSUE TITLE
OAuth20ServiceImpl doesn't respect signature type specified in config

### ISSUE THREAD

**Issue by cwc** [scribejava/scribejava#489]
The 1.0a implementation [takes this setting into account](https://github.com/fernandezpablo85/scribe-java/blob/master/src/main/java/org/scribe/oauth/OAuth10aServiceImpl.java#L160), but the 2.0 implementation [does not](https://github.com/fernandezpablo85/scribe-java/blob/master/src/main/java/org/scribe/oauth/OAuth20ServiceImpl.java#L61).

**Comment by kullfar** [comment]
fixed 14 days ago
https://github.com/scribejava/scribejava/commit/4cd58302f9e252e0a3c355b1f842a527e9b6af3d
there is no signatureType method in the Builder anymore ;-)
It's in DefaultApi10a.java  and DefaultApi20.java
