### ISSUE TITLE
NullPointerException org.scribe.model.Response

### ISSUE THREAD

**Issue by wateringcan** [scribejava/scribejava#492]
by calling method Response.getBody() if the Body of the Response is null.
Bugfix would be:

``` java
package org.scribe.model;
//....
  private String parseBodyContents()
  {
    try{
      body = StreamUtils.getStreamContents(getStream());
      return body;
    }catch(Exception e){
      return "";
    }
  }
```

**Comment by kullfar** [comment]
It seems, the issue is quite outdated and not relevant to the currenst state of source code.
If no one interested, I will close issue in one month
