### ISSUE TITLE
Using Basic Authentication ?

### ISSUE THREAD

**Issue by rsoika** [scribejava/scribejava#504]
Is it possible to use scribe-java also together with basic authentication? 
I have a szenario where a Magento Shop System is secured in general with a basic authentication. Behind that I would like to work with scribe to use the Magento Rest API which is secured with OAUth. 
Scribe works perfect if Magento is not secured additional with basic authentication.
So my question is if I can provide username and credentials for basic authentication to scribe-java?

**Comment by mpanzeri86** [comment]
H
