### ISSUE TITLE
javadoc syntax check issues on java 8 

### ISSUE THREAD

**Issue by GerardPaligot** [scribejava/scribejava#549]
I opened an [issue](https://github.com/fernandezpablo85/scribe-java/issues/539) some weeks ago about the compatibility with Java 8. There was a [PR](https://github.com/fernandezpablo85/scribe-java/pull/543) to fix the bug reported but Scribe Java isn't always compatible with Java 8.

With this last version of Java, it makes some checks in the javadoc and there is a lot of errors with these checks. I won't copy past errors because there are a lot but if you make a `mvn install` on the project, you should see these errors.

**Comment by fernandezpablo85** [comment]
would you check if this PR fixes the doc linting issues?

https://github.com/fernandezpablo85/scribe-java/pull/529

Also, renaming the title since it may (wrongly) imply that scribe is not jdk8 read.

**Comment by fernandezpablo85** [comment]
@GerardPaligot ?

**Comment by GerardPaligot** [comment]
@fernandezpablo85 Really sorry for the delay.

I have a test fail (see below) but the PR seems good for the documentation.

```console
Failed tests:   shouldExtractStandardHeader(org.scribe.extractors.HeaderExtractorTest): expected:<OAuth oauth_[callback="http%3A%2F%2Fexample%2Fcallback", oauth_signature="OAuth-Signature]", oauth_consumer_ke...> but was:<OAuth oauth_[signature="OAuth-Signature", oauth_callback="http%3A%2F%2Fexample%2Fcallback]", oauth_consumer_ke...>

Tests run: 99, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by fernandezpablo85** [comment]
so the PR doesn't fix it?

**Comment by GerardPaligot** [comment]
No, the PR fix this issue but there is another one with this test.

I checked your travis configuration and I see that you don't execute test cases:

```yaml
install: mvn clean package -DskipTests=true
```

It seems a good solution to fix this test and remove the end of this instruction to avoid future regression.

**Comment by fernandezpablo85** [comment]
That's just for the install step, if you check the travis job you'll see
tests are being run:

https://travis-ci.org/fernandezpablo85/scribe-java/builds/70755219

**Comment by kullfar** [comment]
ScribeJava has no javadoc syntax issues on java 8 for the moment. Closing this issue
