### ISSUE TITLE
org.scribe.model.Response needs to catch more exceptions

### ISSUE THREAD

**Issue by CoryAlbrecht** [scribejava/scribejava#567]
Currently the Response class only deals with UnknownHostExceptions but there are other type of IOException that might be thrown. One example is EOFException which is passed when the connection is HTTPS and the SSL negotiation is unexpectedly broken off. There are others, but this is an important one because many APIs require the use of an HTTPS connection. Otherwise, why bother catching *any*  IOException from the attempted connection and turning it into OAuthException?

**Comment by fernandezpablo85** [comment]
PRs are welcome :smile:
