### ISSUE TITLE
Need add support for custom OAuth providers

### ISSUE THREAD

**Issue by netroby** [scribejava/scribejava#569]
In many company intranet. there be many OAuth providers inside their network.
May we provide function for configure Authorize_url and AccessToken_url via function like

setAuthorizeUrl(String xxx)
setAccessTokenUrl(String xxx)

**Comment by fernandezpablo85** [comment]
I don't understand, how is that useful given that you can create your own Api class that has those fields?

**Comment by netroby** [comment]
The benefit parts, No need to wrote Java code.
Just small configure files, Like

authorize_url = "http://www.example.com/authorize"
access_token_url = "http://www.example.com/access_token"

So it will be easily to integrate with ThirdParty OAuth 2.0 providers.

**Comment by fernandezpablo85** [comment]
You can have a properties file with those values and read them into your Api class. I still don't see the benefit of this approach. OAuth providers and their urls don't change that often that you need to externalise these values into (perhaps) reloadable configuration files.

**Comment by kullfar** [comment]
It seems, the issue is quite outdated and not relevant to the current state of source code.
If no one interested, I will close issue in one month
