### ISSUE TITLE
OAuth 2.0 Two Legged - grant password

### ISSUE THREAD

**Issue by igorescobar** [scribejava/scribejava#571]
Hi Guys,

I couldn't see any example using OAuth 2.0 Two Legged (grant_type: password) in the examples section:

In order to get an access token I need to do this:
```
POST /oauth/token HTTP/1.1
Host: docker:9000
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=igor&password=escobar&client_id=igor&client_secret=escobar
```

Also I need to map an route so the client can validate an access_token with our oauth server (which isn't in the same app)

**Comment by kullfar** [comment]
Hi, we have 'getAccessTokenPasswordGrant' method in OAuth20Service. Look, may be it will resolve your issue
