### ISSUE TITLE
Need Pocket support

### ISSUE THREAD

**Issue by soniccat** [scribejava/scribejava#574]
Hello
I'm trying to implement Pocket Api and see that it implements OAuth2 but also requires a request token. I see that DefaultApi20 doesn't support it. It looks like I should create a subclass of OAuth20ServiceImpl and add request token support. Or is it better to change OAuth20ServiceImpl? I just think about sending a pull request and would like to discuss about a better solution.

Pocket spec: https://getpocket.com/developer/docs/authentication

Hmm, I've looked at http://tools.ietf.org/html/rfc6749#section-1.2 and see that there is no a request token. It looks like Pocket has his own hybrid OAuth and I need a separate service for it.

**Comment by kullfar** [comment]
there is no actual question here, right?
