### ISSUE TITLE
I can not find 2.0 in maven central

### ISSUE THREAD

**Issue by enesakar** [scribejava/scribejava#576]
http://search.maven.org/#search%7Cga%7C1%7Ccom.github.scribejava
is it in another repository?

**Comment by kullfar** [comment]
Hi, give me some time ;-) it was not released yet.
It's the first release under new groupid. It allways take some time

**Comment by lockbur** [comment]
me too ,can not find 2.0 in maven central

**Comment by kullfar** [comment]
For the moment you can use old 1.3.x versions
https://github.com/scribejava/scribejava/tree/0311a435fa492cbaa87f4e1c63395f33770d7d38

I expect 2.0 be in central in next week

**Comment by kullfar** [comment]
it's here
http://repo1.maven.org/maven2/com/github/scribejava/

**Comment by kullfar** [comment]
try&check
