### ISSUE TITLE
Executable example link not working

### ISSUE THREAD

**Issue by er-nitishkumar** [scribejava/scribejava#577]
Hi,
Executable example download [link](https://github.com/scribejava/scribejava/blob/master/src/test/java/org/scribe/examples/TwitterExample.java) is not working ( 404 ).

**Comment by kullfar** [comment]
Where did you find this link? It's wrong. The correct one is https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples/TwitterExample.java

Seems you found it on the external resource. It's better to ask them (external resource author) to update link to the provided one. Or to link to specific git commit, not 'master' branch, where this old file exists.

Thanks, anyway for attention ;-)

**Comment by kullfar** [comment]
FYI, have asked to fix the link here
http://akoskm.github.io/2015/07/31/twitter-sign-in-for-web-apps.html#comment-2374382358
