### ISSUE TITLE
Invalid test folder link

### ISSUE THREAD

**Issue by agomezmoron** [scribejava/scribejava#578]
Hi,

In the main page the tests page is pointing to https://github.com/scribejava/scribejava/tree/master/src/test/java/com/github/scribejava/apis/examples instead of https://github.com/scribejava/scribejava/tree/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples.

After reviewing it it was added with the commit https://github.com/scribejava/scribejava/commit/04195020558ea17ba1c271b85ef40977055942c8.

Regards

**Comment by kullfar** [comment]
thanks, will fix soon with https://github.com/scribejava/scribejava/issues/577

**Comment by kullfar** [comment]
fixed, thanks again for attentiveness
