### ISSUE TITLE
Dont Need Token 

### ISSUE THREAD

**Issue by SaeedDarvish** [scribejava/scribejava#580]
hi before every thing tanks for grate library ..
i want to use [woocommerce rest APi](http://woothemes.github.io/woocommerce-rest-api-docs/?shell#authentication) with [Okhttp](http://square.github.io/okhttp/), woocommerce dosent need token it just need 
 * oauth_consumer_key 
 * oauth_timestamp 
 * oauth_nonce
 * oauth_signature
 * oauth_signature_method
 * oauth_version

### is there any way to use scribejava.. how can i use it ...?
thanks....

**Comment by kullfar** [comment]
Hi!

I do not see WooCommerce API here
https://github.com/scribejava/scribejava/tree/master/scribejava-apis/src/main/java/com/github/scribejava/apis
Seems scribejava doesn't support it yet.
You can try to create WooCommerce API and (if needed) any specific services and create a pull request with adding support of WooCommerce to scribejava.

Thanks,
Stas

**Comment by kullfar** [comment]
+ Example of using the new API
(https://github.com/scribejava/scribejava/tree/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples)

Pull Requests are welcome ;-)
