### ISSUE TITLE
Support streamed responses (e.g. twitter streaming endpoints)

### ISSUE THREAD

**Issue by bbarker** [scribejava/scribejava#582]
Hi - I'm just getting started with scribejava, so please forgive me if I've missed some key point. I'm attempting to [access a Twitter streaming endpoint](https://dev.twitter.com/streaming/overview/connecting), with the operative word being streaming - I need to act on the incoming data as I'm getting it. The [Response](https://github.com/scribejava/scribejava/blob/04195020558ea17ba1c271b85ef40977055942c8/scribejava-core/src/main/java/com/github/scribejava/core/model/Response.java) class only has a public method `getBody` for getting content as a string, which would seemingly prevent stream processing.

At least, I think having `getStream`, or some wrapped version of it be `protected` might solve the issue as we could potentially use our own derived response classes, though the response constructor might have to be overridden as well to enable [chunked transfer encoding](https://en.wikipedia.org/wiki/Chunked_transfer_encoding).

Thanks,

Edit: initially I said scribescala - that was a typo, though I did see the project and looked at it with some interest, but noticed it seems to have not been the preferred path :).

**Comment by kullfar** [comment]
Hi, I don't see anything really bad in your idea of making getStream() protected.
Actually I have nothing against making it even public.
Create Pull Request please, if you're interesting in that

**Comment by kullfar** [comment]
done. protected getter in the master

**Comment by kullfar** [comment]
2.0.1 is in the maven central

**Comment by bbarker** [comment]
Thanks! I'd hoped to get back to this. Look forward to trying it soon.

On Thu, Dec 17, 2015 at 4:34 AM, Stas Gromov <notifications@github.com>
wrote:

> 2.0.1 is in the maven central
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scribejava/scribejava/issues/582#issuecomment-165395841>
> .
>



-- 
Brandon Barker
brandon.barker@gmail.com
