### ISSUE TITLE
Integration with Spring Security

### ISSUE THREAD

**Issue by filosssof** [scribejava/scribejava#584]
Can you provide an example with integrating Scribe Java with Spring Security, for storing information about users and limit access to some URL's

**Comment by filosssof** [comment]
More info: http://stackoverflow.com/questions/33964325/how-to-wire-scribe-java-with-spring-security

**Comment by kullfar** [comment]
Sorry, I have no expertise with Spring Context/Security. Seems, like the question is beyond the scope of the scribejava. If you will find the solution, such example of integration will be very wellcome!

**Comment by filosssof** [comment]
Thanks for your answer, I'll try to find the solution in other places. If I'll find it I'll write to you.

**Comment by kullfar** [comment]
Thanks!

**Comment by Omnipresent** [comment]
@filosssof Were you able to find a way to integrate spring security with ScribeJava?

**Comment by mtbadi39** [comment]
Hi @filosssof,  @Omnipresent
Were you able to find a way to do that ! thanks.
