### ISSUE TITLE
[Need Help] Authorization Code for Product Hunt OAuth2.0

### ISSUE THREAD

**Issue by hhua** [scribejava/scribejava#585]
I am trying to use `scribe` in my Android app for Product Hunt API. They require a `grant_type` in the access token request [here](https://api.producthunt.com/v1/docs/oauth_user_authentication/oauth_token_use_the_access_grant_code_you_received_through_the_redirect_to_request_an_access_token).

I've successfully built my custom [API](https://github.com/hhua/product-hunt-android/blob/master/app/src/main/java/com/hhua/android/producthunt/network/ProductHuntApi.java) for Product Hunt. 

I am getting to the point where Access request can be sent but seems lack `grant_type` param.
I found two problems when I tried to set this param.

1. I tried to implement `ProductHunt20ServiceImpl` like [here](https://github.com/hhua/product-hunt-android/blob/master/app/src/main/java/com/hhua/android/producthunt/services/ProductHunt20ServiceImpl.java#L14). However, `AbstractRequest` class is not in the `jar` so that I cannot override `createAccessTokenRequest` method.

2. I found something code mismatch in the `jar` and source code. The source code has one extra [line](https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/oauth/OAuth20ServiceImpl.java#L68) to include `grant_type`; However, the code `jar` file does not.

The code in `jar`. I am using `scribe-1.3.7.jar`. The latest version I can download.

```java
  /**
   * {@inheritDoc}
   */
  public Token getAccessToken(Token requestToken, Verifier verifier)
  {
    OAuthRequest request = new OAuthRequest(api.getAccessTokenVerb(), api.getAccessTokenEndpoint());
    request.addQuerystringParameter(OAuthConstants.CLIENT_ID, config.getApiKey());
    request.addQuerystringParameter(OAuthConstants.CLIENT_SECRET, config.getApiSecret());
    request.addQuerystringParameter(OAuthConstants.CODE, verifier.getValue());
    request.addQuerystringParameter(OAuthConstants.REDIRECT_URI, config.getCallback());
    if(config.hasScope()) request.addQuerystringParameter(OAuthConstants.SCOPE, config.getScope());
    Response response = request.send();
    return api.getAccessTokenExtractor().extract(response.getBody());
  }
```

Could somebody please help me on this?

**Comment by hhua** [comment]
Hmm, I guess I should use scribe 2.0.0. Is there a way to get a `scribe-2.0.jar`? I am on Android project and `Gradle` will work for me as well.

**Comment by hhua** [comment]
Temporarily solved the my own problem by appending `grant_type` to access_token endpoint.

**Comment by kullfar** [comment]
Hi, it's on the maven central.
here
http://repo1.maven.org/maven2/com/github/scribejava/

You can find information about how to get it from maven on the main page of the repo https://github.com/scribejava/scribejava (file README.md)

--------------------
Pull it from Maven Central!

You can pull ScribeJava from the central maven repository, just add these to your pom.xml file:

<dependency>
    <groupId>com.github.scribejava</groupId>
    <artifactId>scribejava-apis</artifactId>
    <version>2.0</version>
</dependency>

And in case you need just core classes (that's it, without any external API (FB, VK, GitHub, Google etc) specific code), you could pull just 'core' artifact.

<dependency>
    <groupId>com.github.scribejava</groupId>
    <artifactId>scribejava-core</artifactId>
    <version>2.0</version>
</dependency>

--------------------

**Comment by hhua** [comment]
@kullfar Thank you a lot! I will dig into that part. Since I haven't worked on Java for a long time, I didn't know how to use Maven. Android app is using Gradle a lot. I will definitely dig into maven.
