### ISSUE TITLE
OAuthRequestAsync ignore all added headers

### ISSUE THREAD

**Issue by huylenq** [scribejava/scribejava#587]
Only URL and request body are forwarded when building the async request, this causes trouble on header-based OAuth signature
https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/model/OAuthRequestAsync.java#L54-L58

**Comment by kullfar** [comment]
Do you mean that Async version misses some analogous line from Sync:
https://github.com/scribejava/scribejava/blame/master/scribejava-core/src/main/java/com/github/scribejava/core/model/OAuthRequest.java#L69-L73 
?

**Comment by huylenq** [comment]
Yes, that's what I mean

**Comment by breadfan** [comment]
Any progress here?

**Comment by breadfan** [comment]
Fixed it: Please merge https://github.com/scribejava/scribejava/pull/638

**Comment by kullfar** [comment]
Merged. thanks!
