### ISSUE TITLE
Google+ DOES support OOB

### ISSUE THREAD

**Issue by chenjianjx** [scribejava/scribejava#588]
When using google2.0 API I got error msg "Must provide a valid url as callback. Google+ does not support OOB" thrown by GoogleApi20.java . 

Actually it supports OOB.   Please try the following url with a clientId. 

https://accounts.google.com/o/oauth2/v2/auth?scope=email&redirect_uri=urn:ietf:wg:oauth:2.0:oob&response_type=code&client_id=xxx

**Comment by chenjianjx** [comment]
Dear @kullfar ,  can you take a look at this one?

**Comment by kullfar** [comment]
Actually I will not have free time to extend any APIs in the near future. I have only plans to enhance and improve the core module of the library. If you could extend GoogleApi and provide pull request, it'll be awesome!

**Comment by chenjianjx** [comment]
Thank you.  What's your code format guideline, such as "replace a tab with 4 (or 8) spaces? ")

**Comment by kullfar** [comment]
There is no guideline actually. Just common "sun" conventions.
I have plan to introduce checkstyle in the project. It will check code for any violations. Before that moment, no rules (

**Comment by chenjianjx** [comment]
PR:  https://github.com/scribejava/scribejava/pull/595  
@kullfar

**Comment by chenjianjx** [comment]
Dear @kullfar, can you deal with the PR ?  My product is going to release soon and I want to use an official version of scribejava.

**Comment by kullfar** [comment]
@chenjianjx I'm looking now

**Comment by kullfar** [comment]
PR merged to the master
