### ISSUE TITLE
Why does GoogleToken.openIdToken not have a public getter?  

### ISSUE THREAD

**Issue by chenjianjx** [scribejava/scribejava#589]
````

public class GoogleToken extends Token {
    private final String openIdToken;
````

The openIdToken is private and has only public getter.  How can I retrieve the value?

**Comment by kullfar** [comment]
Hi, seems you are the first who need it ;-)
you can create Pull request with fixing that. or wait some unwarranted time while I do it myself

**Comment by chenjianjx** [comment]
PR at https://github.com/scribejava/scribejava/pull/590

**Comment by kullfar** [comment]
done. "getter" in master
thanks for pull request

**Comment by kullfar** [comment]
2.0.1 is in the maven central

**Comment by chenjianjx** [comment]
Thanks!   Actually I was thinking you will also integrate the change for https://github.com/scribejava/scribejava/issues/588  to 2.0.1

**Comment by kullfar** [comment]
There was no Pull Request ;-)

**Comment by chenjianjx** [comment]
Dear @kullfar , when will you address that issue?

**Comment by kullfar** [comment]
What do you mean?
issue was "Why does GoogleToken.openIdToken not have a public getter?"
public getter is in v2.0.1

**Comment by chenjianjx** [comment]
Well... forget it.
