### ISSUE TITLE
refresh tokens

### ISSUE THREAD

**Issue by pdtyreus** [scribejava/scribejava#596]
More an more OAuth 2 services are using "refresh" tokens to extend the life of access tokens. The `refresh_token` is usually returned along with the `access_token`, but scribe currently does not parse it out or store it in the `Token` object.

I see that you previously rejected a [pull request](https://github.com/scribejava/scribejava/pull/253) to bring refresh tokens in to this library. However, this was many years ago and I think that use of refresh tokens is much more common now. I've run across it in three major services already.

 * [Google Refresh Tokens](https://developers.google.com/identity/protocols/OAuth2WebServer?hl=en#offline)
 * [Facebook Refresh Tokens](https://developers.facebook.com/docs/facebook-login/access-tokens/expiration-and-extension)
 * [Medium Refresh Tokens](https://github.com/Medium/medium-api-docs)

With Google, it's especially important since the access tokens only live for an hour.

I'm volunteering to do this work as a pull request but wanted to check in with you before I do it. Can I add a `refreshToken` member to `Token`? Or extend it to a `RefreshableToken`? What type of modification would you accept as a PR?

**Comment by kullfar** [comment]
Hi!
It's a very nice proposal.
Will be very happy to get such Pull Request. As for preferable type of modification, it's hard to understand now, what will be the best decision. Any modification, that will improve the library are welcome ;-)

Thanks,
Stas

**Comment by kullfar** [comment]
done
