### ISSUE TITLE
More detailed error logs?

### ISSUE THREAD

**Issue by hdavidzhu** [scribejava/scribejava#598]
Recently I posted this StackOverflow on trying to see more details into a network error:

http://stackoverflow.com/questions/34744856/how-do-i-see-the-details-of-a-scribejava-network-error-in-android

Is there a way to surface the source of these errors easier when using Scribe?

**Comment by kullfar** [comment]
Hi,
current version of ScribeJava has additionally an url in such error statements.
https://github.com/scribejava/scribejava/blob/04195020558ea17ba1c271b85ef40977055942c8/scribejava-core/src/main/java/com/github/scribejava/core/model/OAuthRequest.java#L39

stacktrace here as well

You can download sources and debug as well. Or enhance ScribeJava even more by creating new Pull Request.
