### ISSUE TITLE
LiveApi fails (wrong authorization URL?)

### ISSUE THREAD

**Issue by totof3110** [scribejava/scribejava#601]
When trying to use LiveApi, during the authorization flow I end up at:

https://login.live.com/login.srf?wa=wsignin1.0&rpsnv=12&ct=1452840746&rver=6.7.6631.0&wp=MBI_SSL_SHARED&wreply=https:%2F%2Foauth.live.com%2Fauthorize%3Fclient_id%MYCLIENTID%26redirect_uri%3DMYRETURNURL%26response_type%3Dcode%26scope%3Dwl.emails%2Bwl.signin%26MSPPError%3D-2147198207%26MSPPError%3D-2147198207%26MSPPError%3D-2147198207%26MSPPError%3D-2147198207%26MSPPError%3D-2147198207%26MSPPError%3D-2147198207%26MSPPError%3D-2147198207&lc=1033&id=250206&cbcxt=sky

which shows an error page saying:

>OneDrive
>
>Something went wrong and we can't sign you in right now. Please try again later.

The LiveApi.java has the authorization URL set to `https://oauth.live.com/authorize?client_id=%s&redirect_uri=%s&response_type=code`. If I change it to `https://login.live.com/oauth20_authorize.srf?client_id=%s&redirect_uri=%s&response_type=code` then the authorization flow works and I can get a token.

See https://msdn.microsoft.com/en-us/library/hh243647.aspx#authcodegrant

Does Scribe use the wrong URL?

**Comment by kullfar** [comment]
Any OAuth service are changing their urls from time to time.
Can you make Pull Request with updated url?
I'll need test application and test user credentials to test the change (run the Example), and we will update the url in the ScribeJava.

**Comment by totof3110** [comment]
Here's the PR with the fix: https://github.com/scribejava/scribejava/pull/602/files. I tested with my own Live account and included the output (anonymized :P).

**Comment by kullfar** [comment]
Thanks!

**Comment by kullfar** [comment]
Seems like nobody needs this API, PullRequest were closed, I'm closing the issue as well
