### ISSUE TITLE
How to mock out OAuth for End-to-end tests

### ISSUE THREAD

**Issue by eddiejaoude** [scribejava/scribejava#608]
What is the best way for an end-to-end test (eg. Selenium) to mock out the OAuth process?

**Comment by kullfar** [comment]
I'd prefer to write some generic http emulator. Not only for OAuth process. But to mock any external http server.
Smth like https://github.com/chernatkin/httpemulator
Where your test will set request2response mapping to this http server before actual testing. And then test will start the main selenium test.
Another solution is to write concrete OAuth provider emulator with predefined responses.
In any case you will need to change your /etc/hosts. so your http client will resolve external host to this mock http emulator.
