### ISSUE TITLE
How create a Token obejct?

### ISSUE THREAD

**Issue by stefan-lindvall** [scribejava/scribejava#609]
Hi,

I am about to integrate with WoraPay API (https://sites.google.com/site/worapay/api)
I will be implementing server-to-server methods (MarkBillAsPaid(https://sites.google.com/site/worapay/api/resources/bills#TOC-MarkBillAsPaid), MarkBillPaymentAsFailed(https://sites.google.com/site/worapay/api/resources/bills#TOC-MarkBillAsPaymentFailed)) and do not need to get tokens since they are generated and provided beforehand.

How can I create the Token Object I need when I want to sign the request?

**Comment by kullfar** [comment]
I didn't catch the question.
smth like "new Token(...)"? ;-)

**Comment by stefan-lindvall** [comment]
Exactly. I need to be able to create a Token from string. (string Key, string Secret).

**Comment by kullfar** [comment]
So, what's the problem?
you have this constructor
public Token(String token, String secret)
https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/model/Token.java#L25

**Comment by stefan-lindvall** [comment]
Hi,
Sorry for that simple miss. It works great with that constructor.
Thanks!!

**Comment by kullfar** [comment]
welcome ;-)
