### ISSUE TITLE
Unable to connect to https url 

### ISSUE THREAD

**Issue by anand514** [scribejava/scribejava#610]

**Comment by kullfar** [comment]
Could you provide more info?

**Comment by anand514** [comment]
we are using oauth1.0a authentication for the rest services, we are invoking rest services using scribe1.3.7, in local machine it is working fine,but when we deploy those rest services on "https" then we were unable to connect to those rest services ,we are getting javax.net.ssl.SSLHandshakeException

**Comment by kullfar** [comment]
First of all try to migrate to the newest version of scribejava. 2.2.0 for the moment
```
<dependency>
    <groupId>com.github.scribejava</groupId>
    <artifactId>scribejava-apis</artifactId>
    <version>2.2.0</version>
</dependency>
```

and the second... seems like incorrect certificates. Could you try to make https-connect without using scribejava? just some native java code.
ps. Stacktrace are welcome as well ;-)

**Comment by anand514** [comment]
may be i am asking a out of scope question ...why scribe didn't provide http://www.bhaveshthaker.com/24/calling-invoking-secure-restful-web-service-over-https-with-jax-rs-in-java-without-keystore-truststore-information/      as the url suggested.

**Comment by kullfar** [comment]
Cause is simple
Nobody needs that feature so much, so he make the 'Pull Request' ;-)
