### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: Cannot get String from a null object

### ISSUE THREAD

**Issue by SyCode7** [scribejava/scribejava#618]
Hi, 

Many thanks for this awesome library.
I am writing a REST client application to interact with launcpad.net
following their documentation (https://help.launchpad.net/API/SigningRequests).

After extending the DefaultApi10a class including PLAINTEXT method,
I still encounter java.lang.IllegalArgumentException.
I have tried all the possiblities within my knowledge to no avail.
Kindly aid me.....many thanks.
Snippets of my code are below 

++++++++++ LaunchPadCreds Class +++++++++++++++++++++++++++

```
public class LaunchPadCreds extends DefaultApi10a {
	

    private static final String AUTHORIZATION_URL = "'https://launchpad.net/+authorize-token?oauth_token=%LW0mTGSTRRlXntqjQMw5'";

    @Override
    public String getRequestTokenEndpoint() {
    	
    	return "https://launchpad.net/+request-token";
    }
    
    @Override
    public String getAccessTokenEndpoint() {
    	return "https://launchpad.net/+access-token";
    }
    
    @Override
    public String getAuthorizationUrl(Token requestToken) {

        return String.format(AUTHORIZATION_URL, requestToken.getToken());
    }
    
    @Override
    public  SignatureService getSignatureService(){
    	return new PlaintextSignatureService();
        
    }


```
++++++++++++++++++ OAuth Service Class ++++++++++++++++++

```
OAuthService service = new ServiceBuilder()
                .provider(LaunchPadCreds.class)
                .apiKey("cavasTest2")
                .apiSecret("Sg6cLg2JTl34RHWV4f5rwkrKmZFzkKSmwwNtTqRHfSKLgxtlTNG0s4WZ0qdpmCQTN7gklbqhGwkSp7T8&lp")

                .debug()
                .build();
		System.out.println("+++++++++ Launchpad OAuth workflow ++++++++");
		
		Scanner scanner = new Scanner(System.in);
		System.out.println("Now go and authorize Scribe here:");
		System.out.println("And paste the verifier here");
		System.out.print(">>");
		System.out.println();
		

		System.out.println("Now we're going to access a protected resource...");
		OAuthRequest request = new OAuthRequest(Verb.GET, PROTECTED_RESOURCE_URL, service);
		request.addBodyParameter("status", "this is sparta! *");
		Response response = request.send();
		System.out.println("Got it! Lets see what we found...");
		System.out.println();
		System.out.println(response.getBody());

		System.out.println();
		System.out.println("Thats it man! Go and build something awesome with Scribe! :)");
		
		}

	}

```

**Comment by kullfar** [comment]
Hi. I see problems with using Strings in LaunchPadCreds.java.
{code}
    private static final String AUTHORIZATION_URL = "'https://launchpad.net/+authorize-token?oauth_token=%LW0mTGSTRRlXntqjQMw5'";
{code}
why the whole string is in single-quotes?
what for oauth_token is here?

{code}
return String.format(AUTHORIZATION_URL, requestToken.getToken());
{code}
you have no params in AUTHORIZATION_URL to String.format() it.

**Comment by kullfar** [comment]
try to use any ready API as an example

**Comment by SyCode7** [comment]
Thanks Kullfar. I have tried to make the change you recommended.  I still have the same errors.
It seems also that the working examples differ form my use case slightly. 
Moreso, my application is not a web app so I do not have  are direct ...
thanks in advance.

the error stack is below 

```

obtaining request token from https://launchpad.net/+request-token
setting oauth_callback to oob
generating signature...
using base64 encoder: CommonsCodec
base string is: POST&https%3A%2F%2Flaunchpad.net%2F%2Brequest-token&oauth_callback%3Doob%26oauth_consumer_key%3DLW0mTGSTRRlXntqjQMw5%26oauth_nonce%3D2072828676%26oauth_signature_method%3DPLAINTEXT%26oauth_timestamp%3D1455017236%26oauth_version%3D1.0
signature is: Sg6cLg2JTl34RHWV4f5rwkrKmZFzkKSmwwNtTqRHfSKLgxtlTNG0s4WZ0qdpmCQTN7gklbqhGwkSp7T8&
appended additional OAuth parameters: { oauth_nonce -> 2072828676 , oauth_signature -> Sg6cLg2JTl34RHWV4f5rwkrKmZFzkKSmwwNtTqRHfSKLgxtlTNG0s4WZ0qdpmCQTN7gklbqhGwkSp7T8& , oauth_callback -> oob , oauth_consumer_key -> LW0mTGSTRRlXntqjQMw5 , oauth_timestamp -> 1455017236 , oauth_signature_method -> PLAINTEXT , oauth_version -> 1.0 }
using Http Header signature
sending request...
Exception in thread "main" java.lang.IllegalArgumentException: Cannot get String from a null object
	at com.github.scribejava.core.utils.Preconditions.check(Preconditions.java:73)
	at com.github.scribejava.core.utils.Preconditions.checkNotNull(Preconditions.java:28)
	at com.github.scribejava.core.utils.StreamUtils.getStreamContents(StreamUtils.java:22)
	at com.github.scribejava.core.model.Response.parseBodyContents(Response.java:41)
	at com.github.scribejava.core.model.Response.getBody(Response.java:63)
	at com.github.scribejava.core.oauth.OAuth10aServiceImpl.getRequestToken(OAuth10aServiceImpl.java:54)
	at launchpad.InitialRequest.main(InitialRequest.java:39)

```

**Comment by kullfar** [comment]
pay attention to the error stack you have. to the very first line.

**Comment by kullfar** [comment]
{code}
obtaining request token from https://launchpad.net/+request-token
{code}
I don't think "+request-token" part should be here

**Comment by SyCode7** [comment]
Yeah, i saw that, but I copied the link as is from the provider site as detailed here --> https://help.launchpad.net/API/SigningRequests

**Comment by kullfar** [comment]
Oh. btw, please use the latest ScribeJava version. there is no OAuth10aServiceImpl.java anymore

**Comment by kullfar** [comment]
and show the new corrected code

**Comment by kullfar** [comment]
and full ;-) Maybe some branch on the github.com?

**Comment by SyCode7** [comment]
hi... i just created a branch here [https://github.com/SyCode7/LaunchpadApi_Java/blob/dev/LaunchpadApi/src/launchpad/AuthService.java](url)
I also upgraded to the latest ScribeJava version. However, there is now an error in the AuthService class....something to do with "The method provider(Class<LaunchPadApi>) is undefined for the type ServiceBuilder".

**Comment by SyCode7** [comment]
Could be that the error has to do with removal of OAuth10aServiceImpl.java.....is there an alternative ?

**Comment by kullfar** [comment]
correct. method provider() was removed in the current version. Use something like
.build(API.instance());
or
.build(new API());

instead of
.provider(API.class).build()


and OAuth10aServiceImpl was renamed to OAuth10aService

**Comment by kullfar** [comment]
regarding your code. Why did you skip "getAuthorizationUrl" part?
As I understand you try to implement desktop application.
But to use this OAuth flow you need this step anyway.
According to provided by you link to the documentation
https://help.launchpad.net/API/SigningRequests
```
Step 2: Authenticate the user

Now the user needs to 1) log in to Launchpad, and 2) tell Launchpad how much authority they'd like to delegate to your program. You need to get them to visit the following URL in their web browser:

    https://launchpad.net/+authorize-token?oauth_token={oauth_token}
```

You need to send user to this url. even for stand alone apps. see "Step 2b: If you're writing a stand-alone program" chapter in their docs

**Comment by SyCode7** [comment]
Bear with me, I am still building my skills.
I am stil lseeing the same issues i.e null pointer exception, i am not even able to get to the stage 
for redirection. Does the library handle the first part of the LaunchPad OAuth dance as below 

`So the HTTP request might look like this:
    POST /+request-token HTTP/1.1
    Host: launchpad.net
    Content-type: application/x-www-form-urlencoded
    oauth_consumer_key=just+testing&oauth_signature_method=PLAINTEXT&oauth_signature=%26
The response should look something like this:
    200 OK  `              
Looked up the parameters in the OAuth Config Class, the parameters for this first step are not there. Could they be added in the setState() method
 ` /**
     * Sets optional value used by some provider implementations that is exchanged with provider to avoid CSRF attacks.
     *
     * @param state some secret key that client side shall never receive
     */
    public void setState(String state, String oauth_consumer_key, String oauth_signature_method, String oauth_signature ) {
        this.state = state;
        this.oauth_consumer_key = "cavasTest6";
        this.oauth_signature = "&";
        this.oauth_signature_method = "PLAINTEXT";
    }`          
I have tried but there are some compilation errors are the moment.
Also, I am not sure of how to implement the redirect, according to the launchpad documentation,
there is no inbuilt approach for redirecting.

Thanks.

**Comment by kullfar** [comment]
see here OAuth10aService::addOAuthParams

**Comment by kullfar** [comment]
they are already here

**Comment by SyCode7** [comment]
Many thanks.....could you consider adding supporting launchpad ?
Thanks.

**Comment by kullfar** [comment]
Sure!
Where is the PR?

**Comment by SyCode7** [comment]
PR ? you mean the docs ? ...or like the public relations. Anyway thanks

**Comment by kullfar** [comment]
I mean PullReuqest ;-) like this https://github.com/scribejava/scribejava/pull/651
