### ISSUE TITLE
Fitbit API

### ISSUE THREAD

**Issue by collegestudent2016** [scribejava/scribejava#622]
Would you be able to create a FitbitAPI.java please? I am working on my senior project and would like to use scribejava, but unfortunately there is no Fitbit file with OAuth2.0 within your examples. I am new to android so this would be greatly appreciated.

**Comment by kullfar** [comment]
Sorry, no.
https://github.com/scribejava/scribejava/wiki/Custom-Apis
It's will be a good addition for you project
