### ISSUE TITLE
OAuth2AccessToken  compilation error on 2.2.2

### ISSUE THREAD

**Issue by hkamel** [scribejava/scribejava#624]
I'm using 2.2.2 version of the APis and I'm getting an error about OAuth2AccessToken not being part of core package.

error:  Can't find symbol, com.github.scribejava.core.model

**Comment by FriiSRS** [comment]
Hello, I think that my problem is similar than yours:
The import com.github.scribejava.core.model.OAuth1AccessToken cannot be resolved
The import com.github.scribejava.core.model.OAuth1RequestToken cannot be resolved

What version we should use?
Thanks

**Comment by kullfar** [comment]
Hm. The latest version is 2.2.2. It's correct.
But there is no OAuth2AccessToken class in it yet.
https://github.com/scribejava/scribejava/tree/cf3c62664e1bca36408e671a0a719f6759399daa - this is 2.2.2 release
OAuth2AccessToken is in master, not released yet.

Seems like your are using some mix of unreleased master + released version 2.2.2
