### ISSUE TITLE
Oauth 1.0 ignoring oauth_token parameter for 2 legged call

### ISSUE THREAD

**Issue by aniket-21** [scribejava/scribejava#625]
Oauth 1.0 is ignoring oauth_token parameter for 2 legged call, resulting into a different base string and thus a different signature

According to Oauth 1.0 specs, even if any parameter is empty, it should be added as part of base string http://oauth.net/core/1.0/#rfc.section.9.1.1

issue in signRequest method:

// Do not append the token if empty. This is for two legged OAuth calls.
        if (!token.isEmpty()) {
            request.addOAuthParameter(OAuthConstants.TOKEN, token.getToken());
        }

**Comment by kullfar** [comment]
Hm. it was added 3.5 years ago
https://github.com/scribejava/scribejava/commit/97fa26fce79f98d467edc1997b1a49df162bdb19
@fernandezpablo85 Do you remember why it was done so?

**Comment by kullfar** [comment]
It was FIX
https://github.com/scribejava/scribejava/blob/master/v1-changelog#L91

**Comment by aniket-21** [comment]
this is not in compliance with oauth1.0 spec

**Comment by kullfar** [comment]
looks like this was fix for that
https://github.com/scribejava/scribejava/issues/252

**Comment by kullfar** [comment]
yep. Specs and Standard are great things. But we want to have working implementation, not clean Reference Implementation (as close as possible to the specs yet).

**Comment by aniket-21** [comment]
It may have fixed issue for LinkedIn APIs but what about the implementations who adhere to specs?
This API fails for them

**Comment by kullfar** [comment]
You're right. It should be fixed, but carefully.
It was for LinkedIn OAuth1 while there is LinkedIn OAuth2 already.
I'll look, maybe Linked In OAuth 1 can be dropped already from the library

**Comment by aniket-21** [comment]
Any possibility of adding an overloaded method with a parameter to decide if empty token needs to be added to base string?
This way both implementations can be retained and existing flows won't break

**Comment by kullfar** [comment]
BTW you provide link to the obsolete specs
```
This specification was obsoleted by OAuth Core 1.0 Revision A on June 24th, 2009 to address a session fixation attack. The OAuth Core 1.0 Revision A specification is being obsoleted by the proposed IETF draft draft-hammer-oauth. The draft is currently pending IESG approval before publication as an RFC.
 
Implementers should use RFC 5849: The OAuth 1.0 Protocol instead of this specification. 
```

and the actual one http://tools.ietf.org/html/rfc5849 says
```
   When making the request, the client authenticates using only the
   client credentials.  The client MAY omit the empty "oauth_token"
   protocol parameter from the request and MUST use the empty string as
   the token secret value.
```
and
```
       oauth_token
         The token value used to associate the request with the resource
         owner.  If the request is not associated with a resource owner
         (no token available), clients MAY omit the parameter.
```

see Appendix A.  Differences from the Community Edition
"o  Allowed omitting the "oauth_token" parameter when empty."

**Comment by kullfar** [comment]
Looks like ScribeJava code is ok.
Can you list APIs requiring this parameter here?
Is it one specific API or a whole bucket?

**Comment by kullfar** [comment]
I'd suggest such fix to the ScribeJava
```
        if (!token.isEmpty() || api.isTokenParameterRequired()) {
            request.addOAuthParameter(OAuthConstants.TOKEN, token.getToken());
        }
```
isTokenParameterRequired will by false by default. But any concrete API can override it.

In case there is only one such API, It will be better to create specific "APIService extends OAuth101Service" class and override addOAuthParams method

**Comment by aniket-21** [comment]
I still think there should be flexibility as this is very implementation specific. "May" word gives implementer a choice of considering or ignoring oauth_token (when empty).
Your suggested fix of checking if token parameter is required looks good to me

**Comment by kullfar** [comment]
"clients MAY omit" == "server MUST accept omitted" ;-)

**Comment by aniket-21** [comment]
Agreed :) but if sent empty, that should be handled as well is my point :)

**Comment by kullfar** [comment]
in master
https://github.com/scribejava/scribejava/commit/f7f390a8cfaaabcc6416a94a375e60955b31f9d0

**Comment by aniket-21** [comment]
Fantastic!! Appreciate that quick fix
