### ISSUE TITLE
OAuthRequestAsync Exception

### ISSUE THREAD

**Issue by chrizstone** [scribejava/scribejava#627]
Hi Fernandez,

first of all, very nice library. Works just great but when I try to use the request async it will not start working for me. Here´s my example:

`final String secretState = "secret" + new Random().nextInt(999_999);
final OAuth20Service service;
final OAuthRequestAsync request;
service = new ServiceBuilderAsync()
.asyncHttpClientConfig(buildConfig())
 .apiKey(getApiKey())
.apiSecret(getApiSecret())
.callback(getCallback())
                .state(secretState)
                .grantType(GRANT_TYPE)
                .build(DropBoxApi20.instance());

        request = new OAuthRequestAsync(Verb.GET, getCloud().getInfoUrl(), service);
        service.signRequest(new OAuth2AccessToken(getAccessToken(), ""), request);
        try
        {
            Thread thread = new Thread(new Runnable() {
                @Override
                public void run() {
                    request.sendAsync(new OAuthAsyncRequestCallback<Response>() {
                        @Override
                        public void onCompleted(Response response) {
                            String uniqueId = "";
                            int httpcode = response.getCode();
                            if (httpcode == 200) {
                                JSONObject jsonObj = null;
                                try {
                                    jsonObj = new JSONObject(response.getBody());
                                    uniqueId = jsonObj.getString(USERID);
                                    callback.onComplete(true, ErrorReason.NOERROR, uniqueId);
                                } catch (JSONException e) {
                                    e.printStackTrace();
                                }
                                Log.i(response.getBody());
                            } else {
                                
                            }
                        }

                        @Override
                        public void onThrowable(Throwable t) {
                            callback.onComplete(false, ErrorReason.HTTPCONNECTIONFAILED, "");
                        }
                    });
                }
            });
            thread.start();
        }
        catch (Exception ex)
        {
            Log.e("Exception:  " + ex.getMessage());
        }`
But always onThrowable is getting called with this exception:

`java.lang.NoSuchMethodError: No virtual method setEndpointIdentificationAlgorithm(Ljava/lang/String;)V in class Ljavax/net/ssl/SSLParameters; or its super classes (declaration of 'javax.net.ssl.SSLParameters' appears in /system/framework/core-libart.jar)`

What do I miss?

**Comment by kullfar** [comment]
Hm. What is your jre  provider/version?
Android? http://stackoverflow.com/questions/31358235/jetty-websocketclient-does-not-connect-with-ssl-on-android/31425078

**Comment by chrizstone** [comment]
Hi, yes it´s android. I just tried to set `setAcceptAnyCertificate` to true in the `AsyncHttpClientConfig` and it works. But thats not the nice way on a production version...

**Comment by kullfar** [comment]
Seems like it is the issue with ning http client and Android.
I'll suggest you to stick with sync version of ScribeJava. Why do you need async on the client (Android)? It should not be high-loaded, right? ;-)

**Comment by chrizstone** [comment]
I need the async version because the network operations should not be executed on main thread. Thats why I want to go async...And of course I do not want to freeze UI...

**Comment by kullfar** [comment]
Can't you use separate thread for this?

**Comment by chrizstone** [comment]
Yes, I could do this...But for which purposes is the async service of the library?

**Comment by kullfar** [comment]
For the high-loaded servers. Where we can have hundreds of parallel OAuth requests. And we do not want to have 100 threads waiting for all this network responses, but can use 10 threads to process all incoming oauth processes

**Comment by chrizstone** [comment]
Ok, thanks for the info!
