### ISSUE TITLE
OAuthRequestAsync timeout on mobile data connection

### ISSUE THREAD

**Issue by chrizstone** [scribejava/scribejava#628]
Hi,

If I am connected to a WiFi network on my android device everything is working fine. But if I disable WiFi and go via mobile data (3G, etc), every async request is timing out. Internet connection is working, I checked that already. On sync requests it is working as well.

**Comment by kullfar** [comment]
Is it working with simpe http requests with ning http client? I mean is it ScribeJava related or ning http client related issue?

**Comment by kullfar** [comment]
and the second question. How long sync requests are? May be you just need to increase timeouts in http client config?

**Comment by chrizstone** [comment]
I just tried a little example

`Thread thread = new Thread(new Runnable() {
            @Override
            public void run() {
                AsyncHttpClient asyncHttpClient = new AsyncHttpClient();
                asyncHttpClient.prepareGet("http://httpbin.org/ip").execute(new AsyncCompletionHandler<Response>() {

                    @Override
                    public Response onCompleted(Response response) throws Exception {
                        // Do something with the Response
                        // ...
                        Log.d("");
                        return response;
                    }

                    @Override
                    public void onThrowable(Throwable t) {
                        Log.d("");
                    }
                });
            }
        });
        thread.start();`

This does work on WiFi, but not on mobile connection. So it must be related to ning http client?! My request are little short. See Example...I already increased the timeouts, but no effect...

**Comment by kullfar** [comment]
yep, ning http client related.
Maybe it does his job not so good on mobile devices.

**Comment by kullfar** [comment]
yep, ning http client related.
Maybe it does his job not so good on mobile devices.

**Comment by chrizstone** [comment]
Hmm, thats very bad. Because you are writing about your library that it is fully android ready (out-of-the-box)...So what can I do? Go with sync version of scribe?

**Comment by kullfar** [comment]
Yep. I still can't imagine what for you can need async version ;-)
I'll add fix in Readme, thx for pointing that.

**Comment by chrizstone** [comment]
Ok, thanks...I will go with the sync version...
