### ISSUE TITLE
Access oon Axure server

### ISSUE THREAD

**Issue by Ginolan** [scribejava/scribejava#629]
Hi, i m trying this library, with a Microsoft Azure server. I create the verifier that send me bavk the authorizatoon url, then when i call service.getAccessToken(verifier) the server respons me that respurce is not provided. Do you know if it depends by a library missing or a bad server configuration?

**Comment by Ginolan** [comment]
Hi, i m trying this library, with a Microsoft Azure server. I create the verifier with code that send me back the authorization url, then when i call service.getAccessToken(verifier) the server response give me this error "resource is not provided". Do you know if it depends by a library missing or a bad server configuration?

Sorry for first message, is a SmartFail(smartphone fail)

**Comment by kullfar** [comment]
What methods getAccessTokenEndpoint() and getAccessTokenVerb() of your XXXApi.java return?
maybe there is actualy no such resource on the server? ;-)

**Comment by Ginolan** [comment]
I've created a class AzureApi20 that extends DefaultApi20.
Following specifics, i set the getAccessTokenEndPoint returns the access token given by azure server. In getaccessTokenVerb i've set the return to POST.
I've seen in some Azure guidelines that in the step that crash, the body of request should contain a variable "resource" with his value(seems it's not optional for Azure), but i've not found a method to set it in OAuth20Service object.

**Comment by kullfar** [comment]
I can't catch it.
"in the step that crash, the body of request should contain a variable "resource""
So, you have the step that crash before sending the request&

**Comment by Ginolan** [comment]
After some verify, i've seen that the problem is effectively the resource field.
I've downloaded the source code, and i modiefied the classes OAuth2Service, ServiceBuilder, AbstractServicebuilder, etc., so i was able to add the parameter "resource" to request. Now the request is correct, but the OAuth2AccessTokenExtractor does not succeed to parse the response. The problem is that the response is JSON Formatted, but i see that the regex to match "access_token" parameter expect to have 'access_token=', instead of '"access_token" :' .
So still fail. Have i missed some step where to specify how to parse the response?

**Comment by kullfar** [comment]
Do you need 'resource' parameter in getAccessToken method? Not in getAuthorizationUrl?
as for JSON response  - you need to use JSON extractor https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/extractors/OAuth2AccessTokenJsonExtractor.java

**Comment by Ginolan** [comment]
Yes, in getAccessToken, in this case, is a post, that i've to do after i get the code by getAuthorizationUrl.
Ahh ok, i need to override the getAccessTokenExtractor method in my AzureApi and it's work now.
Can i suggest you to add the resource field for OAuth20Service in next release?
If you want i can pass my code, but it's just five minutes of modifies

**Comment by kullfar** [comment]
Is "resource" field OAuth2 standard parameter? It seems to be Azure-specific stuff. In such case it will be better to create AZureService and override createAccessTokenRequest method https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/oauth/OAuth20Service.java#L66

with smth like
```
request = super.createAccessTokenRequest(verifier, request);
request.addParameter(...);
return request;
```

**Comment by kullfar** [comment]
Google impl as the example
https://github.com/scribejava/scribejava/blob/f5b8df91a6d49b1585a2801cf0142898ca6c0958/scribejava-apis/src/main/java/com/github/scribejava/apis/service/GoogleOAuthServiceImpl.java#L17

**Comment by Ginolan** [comment]
You're right, the field is just for microsoft service, seen in this documentation.
https://msdn.microsoft.com/en-us/library/azure/dn645542.aspx
Thank you for reply and support.
