### ISSUE TITLE
Google auth response_type 

### ISSUE THREAD

**Issue by stevesun21** [scribejava/scribejava#630]
Find url parameter 'response_type' in GoogleApi20 is hardcoded with 'code'. Please make it as configurable item.

**Comment by kullfar** [comment]
Do you need another value here?
Google says it's the only one possible value for Web Server Applications and Installed Applications.
And the 'token' value is for javascript clients.

**Comment by stevesun21** [comment]
Yes, I wanna my server to return a link for web client to use.

**Comment by kullfar** [comment]
Done. https://github.com/scribejava/scribejava/commit/a3ff12d320b13ebfb64dff3ac406a07e9b21c34e
use new method in builder
```
    final OAuth20Service service = new ServiceBuilder()
                .responseType("token")
```
"code" is default value
