### ISSUE TITLE
refreshAccessToken with non definable Endpoint

### ISSUE THREAD

**Issue by chrizstone** [scribejava/scribejava#631]
As I see the new version of ScribeJava now supports RefreshTokens. But in the method of the service "refreshAccessToken" it takes the api.getAccessTokenEndpoint() as endpoint. But in some cases the AccessToken endpoint is not equal to the RefreshToken endpoint. Please make this dynamic.

**Comment by kullfar** [comment]
yep, you are right. done
https://github.com/scribejava/scribejava/commit/d91f6ee0dd58c09c899bfc82888b1add63905a09

**Comment by kullfar** [comment]
Thanks for pointing
