### ISSUE TITLE
DefaultApi20 should use OAuth2AccessTokenJsonExtractor per 2.0 spec

### ISSUE THREAD

**Issue by maksimlikharev** [scribejava/scribejava#632]
https://tools.ietf.org/html/draft-ietf-oauth-v2-11#page-31

"The parameters are including in the entity body of the HTTP response
using the **"application/json" **media type as defined by [RFC4627]."

**Comment by kullfar** [comment]
It's better to use final, not draft specifications http://tools.ietf.org/html/rfc6749#section-5.1
But this part is the same.
Have fixed
https://github.com/scribejava/scribejava/commit/03b3820b24d646fb010ff5c5afcd76f689158cb5
Thanks for pointing
