### ISSUE TITLE
OAuth1.0a doesn't need request token secret to retrieve access token

### ISSUE THREAD

**Issue by sbley** [scribejava/scribejava#634]
As stated in the OAuth 1.0a specs (http://oauth.net/core/1.0a/#auth_step3) in order to obtain an access token you must send the request token and the verifier, but you don't need to send the request token secret.

How am I supposed to send the request without the secret? `new OAuth1RequestToken()` doesn't allow a `null` value for the request token secret. Providing an empty string `""`results in an invalid signature.

**Comment by kullfar** [comment]
But you need to send signature. And token is used for signing the request
http://oauth.net/core/1.0a/#signing_process
see SignatureService implementations in ScribeJava
