### ISSUE TITLE
OAuth 2.0 Access Token Request default verb should be POST

### ISSUE THREAD

**Issue by maksimlikharev** [scribejava/scribejava#636]
per: https://tools.ietf.org/html/rfc6749#section-4.1.3

**Comment by kullfar** [comment]
I'd say according to this chapter http://tools.ietf.org/html/rfc6749#section-3.2
```
The client MUST use the HTTP "POST" method when making access token requests.
```

anyway, you are right, in the master https://github.com/scribejava/scribejava/commit/bbb2aaa020a2f6a12cc16b109838a097d423e8eb
