### ISSUE TITLE
Custom API Help

### ISSUE THREAD

**Issue by collegestudent2016** [scribejava/scribejava#637]
Would you be able to help create a custom API using OAuth2.0 with Refresh tokens. I am using it for Fitbit's OAuth2, but your custom API example is only for OAuth1.0a. I am unsure how to implement the refresh token aspect to the code. Any suggestions/references for creating a custom API for OAuth2 with refresh tokens would be much appreciated.

**Comment by kullfar** [comment]
look at the https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/main/java/com/github/scribejava/apis/GoogleApi20.java as the example
and at the runnable class with example https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples/Google20Example.java

you can start with looking at the last PR with new API also 
https://github.com/scribejava/scribejava/pull/633/files
