### ISSUE TITLE
Facebook issue: Invalid appsecret_proof provided in the API argument

### ISSUE THREAD

**Issue by sachinwalia2k8** [scribejava/scribejava#640]
When I tried using Facebook login example I am getting following error:

Invalid appsecret_proof provided in the API argument

Facebook recommends generating sha256 hash of access token, using the app secret as the key. 
I am able to generate it but where do I set it in the API?

**Comment by kullfar** [comment]
I have just runned FacebookExample. All works good.
Can you copy-paste your console output. On which line (which http request) you have such error response from Facebook?

**Comment by kullfar** [comment]
oudated

**Comment by page31** [comment]
@kullfar see https://developers.facebook.com/docs/graph-api/securing-requests#require-proof

**Comment by kullfar** [comment]
autoadding for any oauth request.
seems there is no such ability with ScribeJava.
I thinks someone interested should implement this in FacebookService.java

**Comment by jkanniappan** [comment]
@kullfar , I am facing the same issue with the FB appsecret. I am using scribejava 4.0.0. 
The FB App is trying to use requires AppSecret and I am not sure how to add it using scribeJava
below error I am getting from FB

{"error":{"message":"API calls from the server require an appsecret_proof argument","type":"GraphMethodException","code":100,"fbtrace_id":"C56WCiA1KFP"}}

**Comment by kullfar** [comment]
Hi, according to  https://developers.facebook.com/docs/graph-api/securing-requests#require-proof "You can prevent this by adding the appsecret_proof parameter to every API call from a server and enabling the setting to require proof on all calls." So you can to disable it.
Second option (better) - implement this in ScribeJava.

**Comment by anandchakru** [comment]
The app secret proof is a sha256 hash of your access token, using the app secret as the key. [ref](https://developers.facebook.com/docs/graph-api/securing-requests/) do something like this:
```java
final OAuthRequest request = new OAuthRequest(Verb.GET, "https://graph.facebook.com/v2.8/me");
String appsecretProof = Hashing.hmacSha256(prop.getFacebookClientSecret().getBytes())
				.hashString(accessToken.getAccessToken(), StandardCharsets.UTF_8).toString();
request.addParameter("appsecret_proof", appsecretProof); 
service.signRequest(accessToken, request);
final Response response = service.execute(request);
String body = response.getBody();
`

**Comment by kullfar** [comment]
appsecret_proof support in the master https://github.com/scribejava/scribejava/commit/fd4f99ef56bbefcc75f0a028d14522a4711ebb11
