### ISSUE TITLE
why is apiSecret mandatory in ServiceBuilder?

### ISSUE THREAD

**Issue by wbartensleben** [scribejava/scribejava#644]
I am trying to use the library with our oauth2 service on an android app. What I currently don't understand is, why the apiSecret in the ServiceBuilder is a mandatory configuration. 

According to the OAuth2 RFC 6749 (4.1.3), the secret is only required, if the client was issued credentials. It makes absolutely no sense to issue credentials to a client that is supposed to run as an android client, because the secret is exposed to the public on a mobile device. 

So we really would like to use the library without issuing and providing a client secret. I guess the configuration is mandatory because you had a confidential service in mind while writing that. 

Is there a chance to make the apiSecret non-mandatory to support non-confidential clients?

**Comment by kullfar** [comment]
Hi, can you point me to the code, what makes you think, that apiSecret is the mandatory param?
Or maybe even provide me code/snippet/stackTrace? Do you use the latest version of ScribeJava?

**Comment by wbartensleben** [comment]
The AbstractServiceBuilder has a function called checkPreconditions, which bails out if there is no apiSecret provided. There might be more places in the followup code.

**Comment by kullfar** [comment]
thanks. have removed this check.
https://github.com/scribejava/scribejava/commit/c328d5db81d97dbffa395bf9fd376f75b52dc6d5

**Comment by sbley** [comment]
Making the client secret optional in the ServiceBuilder is only one part. What is missing is to remove the param from request construction (see [code](https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/oauth/OAuth20Service.java#L105)), otherwise it fails with the following stacktrace: 
```
Exception in thread "main" java.lang.IllegalArgumentException: Cannot encode null object
	at com.github.scribejava.core.utils.Preconditions.check(Preconditions.java:91)
	at com.github.scribejava.core.utils.Preconditions.checkNotNull(Preconditions.java:26)
	at com.github.scribejava.core.utils.OAuthEncoder.encode(OAuthEncoder.java:26)
	at com.github.scribejava.core.model.Parameter.asUrlEncodedPair(Parameter.java:16)
	at com.github.scribejava.core.model.ParameterList.asFormUrlEncodedString(ParameterList.java:63)
	at com.github.scribejava.core.model.OAuthRequest.getByteArrayPayload(OAuthRequest.java:248)
	at com.github.scribejava.core.oauth.OAuthService.execute(OAuthService.java:111)
	at com.github.scribejava.core.oauth.OAuth20Service.sendAccessTokenRequestSync(OAuth20Service.java:37)
	at com.github.scribejava.core.oauth.OAuth20Service.getAccessToken(OAuth20Service.java:61)
```

**Comment by kullfar** [comment]
Hm... according to the OAuth2 specifications, client_secret is not required param in this request. So, you're right, this param should be optional. I will fix it soon.

**Comment by kullfar** [comment]
Seems like in reality most of OAuth providers require this param. But ok. Will make it optional

**Comment by sbley** [comment]
Microsoft ADFS doesn't require it and even rejects the request when the secret is included.

**Comment by kullfar** [comment]
fixed. commit in the master
https://github.com/scribejava/scribejava/commit/ac8ff60ed008e43202d826d7ba7f21a881825e44

**Comment by aordines-vdm** [comment]
I think, this bug is available again with the recents releases.
So, i have a probleme with ADFS

**Comment by kullfar** [comment]
@aordines-vdm, sorry for the long answer, in case the problem is actual - Could you provide Exception's stack trace or any other additional info?
Or what make you think, this bug is available again?
the code is still here
https://github.com/scribejava/scribejava/blob/a7b01f632ac4283db7b7833d64b17a717de4bee7/scribejava-core/src/main/java/com/github/scribejava/core/oauth2/clientauthentication/RequestBodyAuthenticationScheme.java#L30
