### ISSUE TITLE
OAuthServices should provide verifier extractor method

### ISSUE THREAD

**Issue by andretietz** [scribejava/scribejava#647]
I am not sure about oauth10a but when getting the authorizationUrl using the OAuth20Service I have to manually check in my webview if the callback url was called and extract the token manually.

Since the OAuth20Service is aware of the callback itself, the api implementation can check for the verifier code already.

How it is now (using javafx with github api):

    WebView webView = new WebView();
    WebEngine engine = webView.getEngine();
    engine.load(service.getAuthorizationUrl());
    engine.locationProperty().addListener((observable, oldValue, newLocation) -> {
        // very optimistic check, that propably only works for github
        if (newLocation != null && newLocation.contains("code")) {
            String verifyCode = newLocation.substring(newLocation.indexOf("code=") + 5);
            OAuth2AccessToken accessToken = service.getAccessToken(verifyCode);
            doSomething(accessToken.getAccessToken());
        }
    });

Clear disadvantage here is that the verifier extraction hardly depends on the provider itself.

how it could look like:

    WebView webView = new WebView();
    WebEngine engine = webView.getEngine();
    engine.load(service.getAuthorizationUrl());
    engine.locationProperty().addListener((observable, oldLocation, newLocation) -> {
        String verifier = service.extractVerifier(newLocation);
        if(verifier != null) {
            OAuth2AccessToken accessToken = service.getAccessToken(verifier);
            doSomething(accessToken.getAccessToken());
        }
    });

This could be used for almost all of the oauth20 providers.
Edit: for oauth10a providers using a callback this could be good as well. (i.e. twitter)

What do you think?

Since the OAuth20Service is an abstract you could even provide a default implementation if there are several api's using the actual spec ^^

**Comment by kullfar** [comment]
Hm. Interesting. Looks like a hack, but why not?... I'll think about that.

As for your case, aren't "oob" redirect is the best choice?
Google's doc as for example https://developers.google.com/identity/protocols/OAuth2InstalledApp#choosingredirecturi

**Comment by andretietz** [comment]
No, because the user has to do something(in this particular case, copy the code from the browser, switch to the application again and paste it. As you may know users are lazy. I am more familar with Android than with JavaFX and in Android this is pretty much standard.

why do you think this is a hack?
The extraction would be exactly there where it belongs.

**Comment by kullfar** [comment]
I mean continue using WebView, but do not parse url.  smth like this
```
WebView webView = new WebView();
WebEngine engine = webView.getEngine();
engine.load(service.getAuthorizationUrl());
engine.locationProperty().addListener((observable, oldLocation, newLocation) -> {
   if(newLocation.startsWith("urn:ietf:wg:oauth:2.0:oob")) {
      ...get code from title...
       OAuth2AccessToken accessToken = service.getAccessToken(verifier);
       doSomething(accessToken.getAccessToken());
    }
});
```

**Comment by kullfar** [comment]
As For extractVerifier method, Actualy I like this idea. I thought a bit and liked it ;-) I'll create it a bit later.

**Comment by kullfar** [comment]
ps. I mean urn:ietf:wg:oauth:2.0:oob:auto
note 'auto', where code will come to the title

**Comment by andretietz** [comment]
Does this work for other providers than Google too? AFAIK this is not specified in the Oauth 2.0 specs.

**Comment by ankur99999** [comment]
Is your problem is something like this?

https://labs.aweber.com/docs/authentication

here i am also getting this error

Now go and authorize ScribeJava here:
**https://auth.aweber.com/1.0/oauth/authorize?oauth_token=NEWTOKEN**
And paste the verifier here
>>java.util.NoSuchElementException: No line found

when i open this URL in webview https://auth.aweber.com/1.0/oauth/authorize?oauth_token=NEWTOKEN, It will return a code. 

Facing same problem.
have to manually check in my webview if the callback url was called and extract the token manually.

**Comment by ankur99999** [comment]
Can you please tell what is oldLocation and newLocation here?

`WebView webView = new WebView();
WebEngine engine = webView.getEngine();
engine.load(service.getAuthorizationUrl());
engine.locationProperty().addListener((observable, oldLocation, newLocation) -> {
    String verifier = service.extractVerifier(newLocation);
    if(verifier != null) {
        OAuth2AccessToken accessToken = service.getAccessToken(verifier);
        doSomething(accessToken.getAccessToken());
    }
});`

**Comment by kullfar** [comment]
that's it for the OAuth2 
https://github.com/scribejava/scribejava/commit/aedc5890be77d2f50f1c2128bedb95516c397fcc

**Comment by ankur99999** [comment]
Sorry, but we are using maven dependency, How we pick these latest changes? By rebuild?
And how we extract verifier?

**Comment by kullfar** [comment]
I'll release new version today
as for "how we extract verifier" - do you mean OAuth1? I didn't implement this. You can ;-) and provide the PullRequest

**Comment by kullfar** [comment]
if you mean 'code' - look the commit, unit tests

**Comment by andretietz** [comment]
Nice work, this could work for OAuth10a too, I'll may be create the PR the next days. (twitter works quite similar)

**Comment by mtbadi39** [comment]
@kullfar good job thanks !
@andretietz, 

> because the user has to do something(in this particular case, copy the code from the browser, switch to the application again and paste it. As you may know users are lazy.

Yes, absolutely correct

>  I'll may be create the PR the next days

Or may be some working example (with OAuth10, please! )
