### ISSUE TITLE
Instagram Support

### ISSUE THREAD

**Issue by elihusmails** [scribejava/scribejava#650]
I would like to use scribejava to connect to Instagram.  

https://www.instagram.com/developer/

**Comment by kullfar** [comment]
You're welcome!
But create Pull Request instead of Issue.
Start with wiki https://github.com/scribejava/scribejava/wiki

**Comment by elihusmails** [comment]
I'll give it a shot.  I was hoping that one was already in the works.

Thanks!!

**Comment by dbwelch** [comment]
Any progress on Instagram?

**Comment by kullfar** [comment]
I have no info about this. I think, no progress for the moment
