### ISSUE TITLE
POST OAuthRequestAsync.sendAsync add `Content-Type` = `application/x-www-form-urlencoded` 

### ISSUE THREAD

**Issue by antonevane** [scribejava/scribejava#652]
Hi we have a rest service that accept only `application\json`
      
    final OAuthRequestAsync request = new OAuthRequestAsync(Verb.POST, serviceUrl, oauthService);
    request.addHeader(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE);
    request.addPayload(requestData);

    oauthService.signRequest(accessToken, oauthRequest);

    Response response = request.sendAsync(null).get();

Our service receives 2 `Content-Type` - `application/x-www-form-urlencoded`  and `application\json`

The issue has been introduced after #641.

OAuthRequestAsync 

            case POST:
                boundRequestBuilder = asyncHttpClient.preparePost(completeUrl)
                        .addHeader(CONTENT_TYPE, DEFAULT_CONTENT_TYPE) // The problem part
                        .setBody(getBodyContents());
                break;

Suggested fix would to add DEFAULT_CONTENT_TYPE if CONTENT_TYPE doesn't exist.

**Comment by kullfar** [comment]
Hi, thanks for pointing that. Sync version is ok. problem is only with async.
Have added check. last commit in master https://github.com/scribejava/scribejava/commit/f2b1185edda92310a79b4edb5c3006f42329c875

**Comment by antonevane** [comment]
Thanks for quick fix. 
Is there a schedule for the next release to use following fix?

**Comment by kullfar** [comment]
I'll try to release it on this Friday

**Comment by kullfar** [comment]
2.5.3 is in the central
