### ISSUE TITLE
Getting Started 

### ISSUE THREAD

**Issue by PGMacDesign** [scribejava/scribejava#653]
I must be missing something really basic, but I cannot get this library to work in the slightest. 

I have downloaded the Jar file (currently 2.5.2)  and am trying to follow the getting started or the tutorials without success. 

All of the samples of code either use OAuth20Service or OAuth10Service, both of which cannot be found in the library at all. 

The only bit of code I I have been able to get to compile is something like this:

FacebookApi anApi = com.github.scribejava.apis.FacebookApi.instance();

which seems like it does nothing... 
Am I doing something wrong? Am I missing a library or package somehow?

Thanks for the help.

-PGMacDesign

**Comment by kullfar** [comment]
Did you download jar file manualy? Not by maven?
If so, looks like you have downloaded only ...-api.jar and you need ...-core.jar as well.

**Comment by PGMacDesign** [comment]
That did the trick. Thanks for the tip!
