### ISSUE TITLE
Google Example always return refresh token as null

### ISSUE THREAD

**Issue by vinod-bb** [scribejava/scribejava#655]
I am trying the Google Example code in your code, everything works fine, but refresh token is always null.

Is there any change required to get refresh token for google ?

**Comment by kullfar** [comment]
did you see this screen while going to the provided authorization url?
![google](https://cloud.githubusercontent.com/assets/736714/14668268/7ef9e9c4-06f4-11e6-9cc5-cd59a2f358e9.png)

**Comment by vinod-bb** [comment]
I understood the problem. Google gives refresh token only first time or when the Grant Window as you have attached is shown.

After adding **prompt=consent** , I get Authorization window and refresh token every time.

Thanks

**Comment by kullfar** [comment]
yep, right.
It's here in the example
```
additionalParams.put("prompt", "consent");
```
https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples/Google20Example.java#L44
