### ISSUE TITLE
getting Access token with authorization header and authorization code, not password grant 

### ISSUE THREAD

**Issue by fandonov** [scribejava/scribejava#658]
I am trying to use scribejava for access to fitbit API. I have made a custom class as explained in the wiki and I am able to build authorization Url. After that however I have a problem with getting AccessToken. My application must exchange the authorization code for an access token, but in order to do so the request must have a header  that is a Base64 encoded string, and decoded as "client_id:client secret". Their example in the API docs is:
POST https://api.fitbit.com/oauth2/token
Authorization: Basic Y2xpZW50X2lkOmNsaWVudCBzZWNyZXQ=
Content-Type: application/x-www-form-urlencoded

client_id=22942C&grant_type=authorization_code&redirect_uri=http%3A%2F%2Fexample.com%2Ffitbit_auth&code=1234567890

In your library you have such header only for the method getAccessTokenPasswordGrant, but not for the simple getAccessToken. 
So the question is how can I send a request, that has a header as describred above AND a authorization code in the post parameters?

**Comment by kullfar** [comment]
Hi,

seems it's not OAuth2 standard header. You should add new XXXService.java
class.
As an example take a look at the
https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/main/java/com/github/scribejava/apis/service/GoogleOAuthServiceImpl.java

Here we have overrided createAccessTokenRequest method. You can edit
request as you want. And invoke addHeader() as well.

Regards,
Stas
