### ISSUE TITLE
Update Authenticate URL

### ISSUE THREAD

**Issue by drveresh** [scribejava/scribejava#664]
The authentication URL needs to be updated as per the latest LinkedIn REST service, the current one is causing errors.

Change:
From: https://api.linkedin.com/uas/oauth/authenticate?oauth_token=%s
To: https://www.linkedin.com/oauth/v2/authorization?[NEW_PARAMETER_SETS]

**Comment by kullfar** [comment]
LinkedInApi20 is still working
I think you mean LinkedInApi? seems like we need to just delete it

**Comment by mhaligowski** [comment]
Anyway, is LinkedInApi20 actually correct? The verb for getting the accessToken in ScribeJava is set to GET, while the docs says it's POST: https://developer.linkedin.com/docs/oauth2.

I'm getting error like this: 

    ! com.github.scribejava.core.exceptions.OAuthException: Response body is incorrect. Can't extract a '"access_token"\s*:\s*"(\S*?)"' from this: '{"error_description":"missing required parameters, includes an invalid parameter value, parameter more than once. : Unable to retrieve access token : authorization code not found","error":"invalid_request"}'


Let me know if that's an actual error or is this me doing something wrong, I'll be happy to fix that.

**Comment by kullfar** [comment]
Hi.. I have just run LinkedIn20Example
All worked fine for me

**Comment by kullfar** [comment]
Yep. ScribeJava use legacy urls
"If you are using legacy OAuth2 URLs, please see this page for example calling patterns."
https://developer.linkedin.com/docs/oauth21

**Comment by kullfar** [comment]
I have update LinkedInApi20. merged to the master
