### ISSUE TITLE
ScribeJava shouldn't require Async libraries to be on the classpath

### ISSUE THREAD

**Issue by bdunn44** [scribejava/scribejava#668]
The latest versions of Scribe have aimed to fix this, but there is still an issue with the OAuthConfig constructor which indirectly references ning/AHC classes and throws a compilation error. This should be fixable by adding a constructor to OAuthConfig without the Async client configuration.

**Comment by kullfar** [comment]
Hm... And what is the user story to use this constructor outside the library?
Looks like OAuthConfig shoud be 'private' class instead

**Comment by bdunn44** [comment]
I've developed a [Vaadin ](https://vaadin.com/home) add-on that uses this library. It allows users to tweak the OAuth configuration for the edge cases where the OOTB API configurations won't work. See [OAuthData.java](https://github.com/bdunn44/vaadin-oauthpopup/blob/master/oauthpopup/src/main/java/org/vaadin/addon/oauthpopup/OAuthData.java) (line 274). 

Essentially my add-on exposes it's own configuration object ([OAuthPopupConfig.java](https://github.com/bdunn44/vaadin-oauthpopup/blob/master/oauthpopup/src/main/java/org/vaadin/addon/oauthpopup/OAuthPopupConfig.java)), which produces a Scribe config object when needed (#asScribeConfig, line 89). This allows users to tweak details like the callback URL, etc.This isn't an issue with 2.4.0 but I'm looking to upgrade to the latest version without adding the ning/AHC dependencies to my project.

Is there another way that you would recommend I configure Scribe services other than using OAuthConfig? I'm not aware of another method, and it would seem quite limiting to remove that flexibility.

**Comment by kullfar** [comment]
OAuthPopupConfig can have method like
```
createScribeServiceBuilder() {
new ServiceBuilder()
.apiKey(getApiKey())
.apiSecret(getApiSecret())
....
}
```
and then in  OAuthData.java it will be like this
```
	private OAuthService getService() {
		if (service == null) {
			service = config.createScribeServiceBuilder().build(isOAuth20()?api20:api10a);
		}
		return service;
}
```
isn't it good?

**Comment by bdunn44** [comment]
Perfect! Thanks for the heads up on the ServiceBuilder. I think that will work for me.

Out of curiosity, what happened to the Grant Type configuration?

**Comment by kullfar** [comment]
It doesn't needed while service building. So it was removed.
It's needed in the specific methods.

OAuthConstants.GRANT_TYPE=OAuthConstants.AUTHORIZATION_CODE
while requesting AccessToken in method createAccessTokenRequest
https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/oauth/OAuth20Service.java#L85

OAuthConstants.GRANT_TYPE=OAuthConstants.REFRESH_TOKEN
while refreshing token, invoking createRefreshTokenRequest method
https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/oauth/OAuth20Service.java#L112

and
OAuthConstants.GRANT_TYPE=OAuthConstants.PASSWORD
while using Password OAuth flow, method createAccessTokenPasswordGrantRequest
https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/oauth/OAuth20Service.java#L112

**Comment by kullfar** [comment]
let me know if using ServiceBuilder will solve your problem. I'll close PR and issue and will think on dropping OAuthConfig class ;-)

**Comment by bdunn44** [comment]
Makes sense. The ServiceBuilder is working, thanks! It was a little bit of a pain due to the precodition checks though:

```java
	public ServiceBuilder createScribeServiceBuilder() {
		final ServiceBuilder sb = new ServiceBuilder()
				.apiKey(getApiKey())
				.apiSecret(getApiSecret());
		if (getCallbackUrl() != null && !getCallbackUrl().isEmpty()) 
			sb.callback(getCallbackUrl());
		if (getSignatureType() != null) 
			sb.signatureType(getSignatureType());
		if (getScope() != null && !getScope().isEmpty()) 
			sb.scope(getScope());
		if (getOutputStream() != null) 
			sb.debugStream(getOutputStream());
		if (getConnectTimeout() != null) 
			sb.connectTimeout(getConnectTimeout());
		if (getReadTimeout() != null) 
			sb.readTimeout(getReadTimeout());
		if (getUserAgent() != null && !getUserAgent().isEmpty()) 
			sb.userAgent(getUserAgent());
		if (getState() != null && !getState().isEmpty()) 
			sb.state(getState());
		if (getResponseType() != null && !getResponseType().isEmpty()) 
			sb.responseType(getResponseType());
		return sb;
	}
```

Thanks again!

**Comment by kullfar** [comment]
welcome
