### ISSUE TITLE
FacebookExample Error

### ISSUE THREAD

**Issue by pi408637535** [scribejava/scribejava#672]

**Comment by pi408637535** [comment]
Hi,when I run FacebookExample, I meet a error:  Unable to load the URL : URL of the domain name is not included in the application domain . To be able to load the URL, add all domains and subdomains applications in the application domain field application settings.  I don't know how to solve this error/

**Comment by kullfar** [comment]
It's not ScribeJava's error. Did your look the answer in the internet?
Smth like this http://stackoverflow.com/questions/37063685/facebook-oauth-the-domain-of-this-url-isnt-included-in-the-apps-domain
