### ISSUE TITLE
Google20Example Error

### ISSUE THREAD

**Issue by pi408637535** [scribejava/scribejava#673]
Hi, I meet a question. Android and IOS could't not use of G+ but now,scribejava make use of G+ to login google account. I should how to use scribejava implement Third Login By google account?

**Comment by kullfar** [comment]
Sorry, didn't catch your question

**Comment by pi408637535** [comment]
Sorry,My English is not good.
G + has been disabled . But scribejava  continue to choose the use of G + :private static final String NETWORK_NAME = "G+";  . I now want to know  that the continuing reference Google20Example or other example is the complete google Oauth.

**Comment by kullfar** [comment]
"G + has been disabled"
Really? What do you mean by this? I had no info about that ;-)

**Comment by kullfar** [comment]
as for ScribeJava. Core module is not aware about any API outside in the world.
And awareness of G+ is limited to the couple of classes in scribejava-api module.
So scribejava doesn't  continue to choose the use of any API

**Comment by kullfar** [comment]
Are there still any question open?

**Comment by kullfar** [comment]
no questions. closing
