### ISSUE TITLE
Why FacebookExample require userinfo only two attributes？

### ISSUE THREAD

**Issue by pi408637535** [scribejava/scribejava#675]
I refer FacebookExample and it success to run. 
Why we only can require two attributes?
response.getBody()==={"name":"\u9ec4\u7855","id":"675208112617636"}
I already have filled in a lot of user data.

**Comment by kullfar** [comment]
Ask Facebook

**Comment by pi408637535** [comment]
I solve this problem.
I refer this：https://developers.facebook.com/tools/explorer/242385899467098?method=GET&path=me%3Ffields%3Did%2Cname%2Cemail%2Clocation%2Cgender&version=v2.6

so I set PROTECTED_RESOURCE_URL="https://graph.facebook.com/v2.6/me?fields=id,name,email,gender";
