### ISSUE TITLE
Client-Side SSL

### ISSUE THREAD

**Issue by semyonfishman** [scribejava/scribejava#680]
Are there plans to enable **client-side** SSL?    For example [Xero Partner](https://developer.xero.com/documentation/getting-started/partner-applications/) integration requires this.

I think the basic idea would be to add some conditional logic to [`OAuthRequest.createConnection()`](https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/model/OAuthRequest.java#L60) that would set the [`SSLContext`](https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLContext.html) from a  [`KeyStore`](https://docs.oracle.com/javase/8/docs/api/java/security/KeyStore.html) on the connection. Something like this...
```java
private void createConnection() throws IOException {
	final String completeUrl = getCompleteUrl();
	if (connection == null) {
		System.setProperty("http.keepAlive", isConnectionKeepAlive() ? "true" : "false");
		connection = (HttpsURLConnection) new URL(completeUrl).openConnection();
		connection.setInstanceFollowRedirects(isFollowRedirects());
		
		// if keystore is configured...
		SSLContext sslContext = SSLContexts.custom().loadKeyMaterial(keystore, keyPassword).build();
		connection.setSSLSocketFactory(sslContext.getSocketFactory());
	}
}
```

In an actual implementation the `KeyStore` (along with it's password) could be passed to the `OAuthRequest` via `OAuthService`.

Seems like something very similar to this was discussed in #503, but was abandoned.

If you guys are interested, I can push a PR with something along these lines.

Thanks

**Comment by kullfar** [comment]
Hi,
Cannot it be done outside of ScribeJava?
Like it was done for SalesForce and TLS >=v1.1
method initTLSv11orUpper https://github.com/scribejava/scribejava/commit/821bc7ce67ccddc240642a496a6cb469ceac4761#diff-4088d4bc2d35c02381574e4cdf0ad503R86

So user can configure SSLContext themselves or invoke this helper method, like in the example
https://github.com/scribejava/scribejava/commit/821bc7ce67ccddc240642a496a6cb469ceac4761#diff-8ae36f0f677a9a194f71ffce9cae3255R27

ps.Anyway it should be implemented for Async version as well

**Comment by semyonfishman** [comment]
@kullfar, thanks for the quick reply.

You were right, it can (and probably should) be done _outside_ of ScribeJava. While commit 821bc7c was not what I was looking for, it did lead me to the solution.  

In a nutshell, one should use [Java SSL](http://docs.oracle.com/javase/7/docs/technotes/guides/security/jsse/JSSERefGuide.html#Introduction) properties to enable client-side certificates, specifcally these three properties...
```ini
javax.net.ssl.keyStoreType=pkcs12
javax.net.ssl.keyStore=client.p12
javax.net.ssl.keyStorePassword=whatever
```
Checkout [this Stackoverflow for more info](http://stackoverflow.com/questions/1666052/java-https-client-certificate-authentication)

I'll PR you guys my Xero Partner API implementation once it's ready.   Closing this for now.

**Comment by kullfar** [comment]
Good.
Anyway, I think it will be great to have some hints in javadoc or even some helper method to simplify usage for 'common' user, who don't want to configure this outside or can't understand what they have to do to start using this API.
Thanks in advance for Xero Partner API!
