### ISSUE TITLE
How can I  gain user's protected resource by Google20Example?  

### ISSUE THREAD

**Issue by pi408637535** [scribejava/scribejava#682]
I have apply for a application in Google APIs and make use of Oauth to gain user's resource. I refer scribejava--Google20Example. I don't know how to fill with "scope("profile") // replace with desired scope" . I have tried:emil,picture. Can you give me some suggest. thank you very much.

**Comment by kullfar** [comment]
not ScribeJava related issue/question. Ask Google
http://lmgtfy.com/?q=google+OAuth+scopes
