### ISSUE TITLE
Adding some abstraction arround http client

### ISSUE THREAD

**Issue by juherr** [scribejava/scribejava#683]
I'd like to use scribejava with Okhttp where scribejava will use Okhttp.

I found something going into this direction: #484 and #485 

Is it something you can accept?

About implementation, we can imagine having a module like `scribejava-okhttp` (and some others) which is responsible to integrate scribejava and okhttp together. At least, this integration could be done in a 3rd party project.

**Comment by kullfar** [comment]
https://github.com/scribejava/scribejava/pull/484 and https://github.com/scribejava/scribejava/pull/485 are very old PRs. ScribeJava has changed a lot from that time. It supports Ning http client 1.9.x and AsyncHttpClient 2.x for the moment.
ScribeJava is not very "pluggable" yet, hope someday it will.
Now all source code about both http clients is in one monolith core submodule. I think it will become more pluggable (maybe even in different maven modules) while adding new http client implementation. As Okhttp or Apache http client.
And I think it should be made a bit more "pluggable" before adding new  http client. I had some thoughts about making this sometime in the near future. I want to separate usages of org.asynchttpclient.* and  com.ning.http.clien.* from scribejava-core.
