### ISSUE TITLE
scribejava api first vs http client api first

### ISSUE THREAD

**Issue by juherr** [scribejava/scribejava#685]
Currently, scribejava is oriented as a top layer library which uses 3rd party http client (what I call "scribejava api first").

I'd like to integrate scribejava with okhttp but I want to continue to use the okhttp api as usual and just integrate scribejava as an `Authenticator`.
For that purpose, I need to pass my own httpclient instance and want scibejava use it.

What do you think? How can I implement it?

**Comment by kullfar** [comment]
I'd start with scribejava-httpclient-okhttp ;-)
I don't see anything complicated with creating okhttp-authenticator-scribejava integration then

**Comment by juherr** [comment]
Forget the question. I wanted to use only one okhttp instance and I supposed okhttp provides a way to make request from `Authenticator`.

Workflow: 
my code -> new okhttp with (authenticator -> "current okhttp" + oauth workflow)
instead of
my code -> new okhttp with (authenticator -> new okhttp + oauth workflow)

But I don't find how to make request from an authenticator, so, it is not a problem for the moment.

**Comment by kullfar** [comment]
Ah, I see.
I had thoughts, that ServiceBuilder should not just provide httpClientConfig(..) method, but httpClient(..) as well to inject any preinitiated httpClient
It would help you

**Comment by juherr** [comment]
:+1: Thank! Need to find how making requests from Authenticator now.
