### ISSUE TITLE
Any ideas how to use the SHA1 service builder?

### ISSUE THREAD

**Issue by coderbec** [scribejava/scribejava#688]
I can generate the service, and ask it for the secret, but what do I do with that?

**Comment by kullfar** [comment]
Sorry, I didn't understand you. What is the problem?

**Comment by Sheikh-Aman** [comment]
@coderbec You'd generally send a request from that

**Comment by kullfar** [comment]
or look here for usage examples
https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples/

**Comment by kullfar** [comment]
out of date
