### ISSUE TITLE
It is not possible to use current versions of scribejava on JDK 6 or olders. 

### ISSUE THREAD

**Issue by adrianobrito** [scribejava/scribejava#690]
I tried to use this wonderful dependency on my project, but I'm not getting success on hosts that uses JVM 6- . It's nice to have backward-compatiblity on this marvelous project for people see what can it do for them.

Thank you and greetings from Brazil.
[]'s

**Comment by adrianobrito** [comment]
For someone which is facing this problem, i get a solution based in:

* Clone the project to your host
* Changes POM changing the source and target version to 1.6
* Them trigger `mvn clean install`
* It'll be listed some source code error that are related to JVM changing
* Try to adapt that errors to the Java 6 Language Scope
* Generate a new dependency and put on your dependency management system or your local machine

[]'s

**Comment by kullfar** [comment]
Java 6 is ten years old, it's public support is over.
Java 7 is 5 y.o. It's time to switch. Even Java 8 is 2y.o. ;-)

As for backward compatibility in ScribeJava. it's a time consuming job to support them for free

Greeting from Russia ;-)

**Comment by adrianobrito** [comment]
ai dento, #TEUBOGA
