### ISSUE TITLE
2-legged Oauth1 Example

### ISSUE THREAD

**Issue by magic-lantern** [scribejava/scribejava#691]
Is it possible to provide an updated example of how to do 2-legged OAuth 1? A working example code or a WIKI/FAQ post would be great.

I've found some previous issues (such as https://github.com/scribejava/scribejava/issues/510) as well as various posts on other sites such as http://stackoverflow.com/questions/20384045/2-legged-oauth-client-not-working-with-scribe, https://www.drupal.org/node/1827698, https://answers.atlassian.com/questions/10402525/trying-to-use-scribe-library-for-2-legged-oauth-in-jira.

However, the issues and example code from other sites don't match the current state of the ScribeJava API.

**Comment by kullfar** [comment]
Hi, could you provide the working example with Scribe pre 2.x version? Using 1.3.6 for example https://github.com/scribejava/scribejava/tree/1.3.6
Smth like the others examples in it 
https://github.com/scribejava/scribejava/tree/1.3.6/src/test/java/org/scribe/examples

and name it like XXX2LeggedExample.
I'll try to adapt it to the latest ScribeJava version and put to the master branch.

ps.I will need test application credentials to run the example

**Comment by magic-lantern** [comment]
I'll work on this. The 2-legged OAuth 1.0a server I use is internal/private, but I believe I can setup something for testing/validation purposes.

**Comment by kullfar** [comment]
out of date
