### ISSUE TITLE
An example that works.

### ISSUE THREAD

**Issue by ssozonoff** [scribejava/scribejava#697]
Hi Guys,

I dont know whats going on but the Scribe implementation seems to have changed so much that all I can find are examples which dont compile with the latest release of Scribe! I have spent far too much time looking for answers for a lib that is claiming to be dead simple.

Is there somewhere I can find a simple example of an OAuth2 implementation which works and actually compiles ?

Thanks

**Comment by kullfar** [comment]
Sure. You have the link on the main page Readme
https://github.com/scribejava/scribejava/tree/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples

I will make it more visible ;-)

**Comment by kullfar** [comment]
have added the link in the "Dead Simple" chapter on the main page (README.md)

**Comment by ssozonoff** [comment]
Thanks.

**Comment by kullfar** [comment]
fixed
