### ISSUE TITLE
user password example?

### ISSUE THREAD

**Issue by WreckCenter** [scribejava/scribejava#699]
this seems like it should be "dead simple"...but apparently you can't create a service without an api, and i don't really need an api to do a resource owner password grant type...must be missing something simple? or no way around not having an api...

**Comment by kullfar** [comment]
XXXAPI.java contains urls and http method. They are used for password grant as well.
Look the method
```
    public final OAuth2AccessToken getAccessTokenPasswordGrant(String uname, String password) throws IOException {
        final OAuthRequest request = createAccessTokenPasswordGrantRequest(uname, password,
                new OAuthRequest(api.getAccessTokenVerb(), api.getAccessTokenEndpoint(), this));

        return sendAccessTokenRequestSync(request);
    }

```
in OAuth20Service
https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/oauth/OAuth20Service.java

it need getAccessTokenVerb and getAccessTokenEndpoint

DefaultApi20.java https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/builder/api/DefaultApi20.java
has default HTTP Verb
```
    public Verb getAccessTokenVerb() {
        return Verb.POST;
    }
```
But getter for the url is abstract and should be implemented in XXXApi.java
```
    /**
     * Returns the URL that receives the access token requests.
     *
     * @return access token URL
     */
public abstract String getAccessTokenEndpoint();
```

**Comment by WreckCenter** [comment]
yah i was being a moron...should just delete this comment ;) ...i realized after i posted i just needed to extend the default20.api...my apologies
