### ISSUE TITLE
Need a example to login Microsoft Live on Android

### ISSUE THREAD

**Issue by nguyencongbinh** [scribejava/scribejava#700]
I need a example to login Oauth2 for Microsoft Live on Android. 
I searched but can not find any example.

**Comment by kullfar** [comment]
I have no example as well. You could provide one ;-)
ps. https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples/LiveExample.java - should differ a lot for Andorid

**Comment by kullfar** [comment]
should **NOT** differ a lot for Andorid
