### ISSUE TITLE
No way to add MultipartEntity to post request.

### ISSUE THREAD

**Issue by madale2010** [scribejava/scribejava#705]
Using the given methods there isn't a way to add parts or MultipartEntity's to current service. If you try to use payload it doesn't correctly setup headers needed for a multi part form post.

**Comment by kullfar** [comment]
Pull Requests are welcome ;-)
Actually I have never done such task as sending MultipartEntities using OAuth signed APIs.
As I understand your problem, You want to upload some file to the external API and ScribeJava cann't sign the request correctly?

**Comment by madale2010** [comment]
You are correct, due to the nature of the request and the requirements involved I do believe it is possible but it would require changing some of the core parts of the code. If scribe is built on top of other packages such as apache http packages, it could be added to the building of requests to allow for proper headers to be sent.

**Comment by kullfar** [comment]
for the moment ScribeJava can use AsyncHttpClient, NingAsyncHttp and standard java.net.HttpURLConnection

Yep. I think it's possible to implement.

**Comment by kullfar** [comment]
there are some changes in ScribeJava
It should support now java.io.File and byte[] payloads https://github.com/scribejava/scribejava/commit/b7d0c6dd510c23457fa8ad9da46a6748749aa032
And PUT, DELETE methods https://github.com/scribejava/scribejava/commit/43ea452609f7fa857e61c5f35f955faff6efe760
Maybe it will helps you a bit
