### ISSUE TITLE
Cannot unit test using Mockito due to methods in OAuth20Service class being final

### ISSUE THREAD

**Issue by wilferraciolli** [scribejava/scribejava#709]
The best framework for testing cannot be used for this library due to having final merthods which cannot be stubbed neither easy to use reflection to unit test it.

`public final OAuth2AccessToken getAccessToken(String code) throws IOException {
        final OAuthRequest request = createAccessTokenRequest(code,
                new OAuthRequest(api.getAccessTokenVerb(), api.getAccessTokenEndpoint(), this));
        return sendAccessTokenRequestSync(request);
    }`

**Comment by kullfar** [comment]
sad
Do you need this at all? Stubing createAccessTokenRequest and/or sendAccessTokenRequestSync isnot enough?

**Comment by wilferraciolli** [comment]
Hi


yes, we cant get coverage therefore we will have to stop using it. Junit will not mock the getAccess token at all.  regards


________________________________

**Comment by kullfar** [comment]
out of date
