### ISSUE TITLE
DefaultApi10a.java

### ISSUE THREAD

**Issue by leogariba** [scribejava/scribejava#712]
Maven getAuthorizationUrl(Token token);
Github getAuthorizationUrl(OAuth1RequestToken requestToken);

**Comment by leogariba** [comment]
Maven DefaultApi10a implements Api 
Github DefaultApi10a implements BaseApi<OAuth10aService>

**Comment by kullfar** [comment]
mmm?

**Comment by leogariba** [comment]
I am sorry. I was using another lib that use an old version of scribejava, thats why i was seeing a different implementation of some classes.  Nice work btw! Thanks

**Comment by kullfar** [comment]
Ah... got it ;-)
welcome
