### ISSUE TITLE
How to use scribe for woocommerce

### ISSUE THREAD

**Issue by rameshvoltella** [scribejava/scribejava#713]
hi  how to use scribe for woocommere can you please provide a api for that oAuth1.0

**Comment by kullfar** [comment]
Hi, no, I can't provide (https://github.com/scribejava/scribejava/wiki/FAQ#when-will-you-support-insert_api_here-)
Start here https://github.com/scribejava/scribejava/wiki/Custom-Apis

**Comment by rameshvoltella** [comment]
Okey i have fix that thank you :+1:
