### ISSUE TITLE
Extract data from Facebook

### ISSUE THREAD

**Issue by xerest** [scribejava/scribejava#714]
Hi,

How to use the follow example:

https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples/FacebookExample.java

if I have already Facebook Access Token(String)?

**Comment by kullfar** [comment]
String accessTokenAlreadyHave = "...";
        OAuth2AccessToken accessToken = new OAuth2AccessToken(accessTokenAlreadyHave);

        // Now let's go and ask for a protected resource!
        System.out.println("Now we're going to access a protected resource...");
        final OAuthRequest request = new OAuthRequest(Verb.GET, PROTECTED_RESOURCE_URL, service);
        service.signRequest(accessToken, request);
        final Response response = request.send();
        System.out.println("Got it! Lets see what we found...");
        System.out.println();
        System.out.println(response.getCode());
        System.out.println(response.getBody());

        System.out.println();
System.out.println("Thats it man! Go and build something awesome with ScribeJava! :)");

**Comment by xerest** [comment]
Thank you very much @kullfar
