### ISSUE TITLE
Issue with ServiceBuilder 

### ISSUE THREAD

**Issue by samrock06** [scribejava/scribejava#715]
I followed the linkedIn example as described for version 3.2.0, but when I try to instantiate my service 

`final OAuth20Service service = new ServiceBuilder().apiKey(apiKey).apiSecret(apiSecret).scope(OAuthScope).callback(callbackUrl).state("some_param").debug().build(LinkedInApi20.instance());` 

It seems to fail. debug() does not seem to work as it isn't logging to console so I can't determine what the issue might be. Am I missing something?

**Comment by kullfar** [comment]
Hm. Do you have any output in the console?

**Comment by kullfar** [comment]
What made you think it failed? Any exceptions etc

**Comment by kullfar** [comment]
out of date
