### ISSUE TITLE
NullPointerException thrown with OAuth10aService

### ISSUE THREAD

**Issue by ddavtian** [scribejava/scribejava#731]
Hello,

Great project guys. I am running into a NullPointerException when trying to call the following code

```
// test only, remove before it goes into production
  ProxyServer proxy = new ProxyServer("proxy.esl.domain.com", 80);
  // test only, remove before it goes into production

OAuth10aService service;   

ScribeJavaConfig.setForceTypeOfHttpRequests(ForceTypeOfHttpRequest.FORCE_ASYNC_ONLY_HTTP_REQUESTS);
            final NingHttpClientConfig clientConfig = new NingHttpClientConfig(new AsyncHttpClientConfig.Builder()
                    .setMaxConnections(5)
                    .setRequestTimeout(10_000)
                    .setAllowPoolingConnections(false)
                    .setPooledConnectionIdleTimeout(1_000)
                    .setReadTimeout(1_000)
                    .setProxyServer(proxy) // test only, remove before it goes into production
                    .build());

            service = new ServiceBuilder()
                    .apiKey("jhvS5aXXXXXXXXXCKyQcxjuba")
                    .apiSecret("OPu6QzvbXXXXXXX7R0PK4z9UT4wrH0")
                    .callback("http://test.cmxde.mo/api/connect/config/v1/twitter/oauth/services")
                    .httpClientConfig(clientConfig)
                    .build(TwitterApi.instance());`
```

Right after the build is call the NullPointerException is thrown. 

Any help is appreciated.

**Comment by ddavtian** [comment]
Also if I use it as simply as possible as such

`            service = new ServiceBuilder()
                    .apiKey("jhvS5ahCekMHl3DCKyQcxjuba")
                    .apiSecret("OPu6Qzvb7siRKpHsDElJADWNPn07Z2GuMmD7R0PK4z9UT4wrH0")
                    .build(TwitterApi.instance());`

I see the following error: com.github.scribejava.core.exceptions.OAuthException: Cannot use sync operations, only async

**Comment by kullfar** [comment]
1.NullPointerException - show full StackTrace, pls
2."Cannot use sync operations, only async" - You can set desired behaviour, like this for example: 
ScribeJavaConfig.setForceTypeOfHttpRequests(ForceTypeOfHttpRequest.FORCE_ASYNC_ONLY_HTTP_REQUESTS);

look for ScribeJavaConfig usages. in XXXExample.java
and in ForceTypeOfHttpRequestTest.java

**Comment by ddavtian** [comment]
@kullfar this was an operator error on my part, closing it.
