### ISSUE TITLE
Twitter upload image

### ISSUE THREAD

**Issue by maciejbak85** [scribejava/scribejava#732]
Hi,

I need to upload image to twitter using OAuth ( I have working text tweeting, feeds etc )

> POST https://upload.twitter.com/1.1/media/upload.json

Im trying by such code

> def postData(file: File): String = {
>     import org.apache.commons.codec.binary.Base64
>     Base64.encodeBase64String(Files.readAllBytes(Paths.get(file.getAbsolutePath)))
>   }
> 
>   def uploadFile(file:File) : Unit = {
>     val request = new OAuthRequest(Verb.POST, "https://upload.twitter.com/1.1/media/upload.json", service.getConfig)
>     service.signRequest(accessToken, request)
>     //request.addBodyParameter("test", postData(file))
>     request.addBodyParameter("media[]", file.getAbsolutePath)
>     val response = request.send()
>     println(response.getBody)
>   }

no way to make it working :( always I get error:

> {"errors":[{"code":32,"message":"Could not authenticate you."}]}

Anyone managed to successfully upload image to twitter ?

Thanks!

**Comment by kullfar** [comment]
Hi,

first of all try setPayload method instead of addBodyParameter. addBodyParameter works with strings, you gave  file.getAbsolutePath to it. It's not the file, but it's name

**Comment by kullfar** [comment]
And the next thing.
I think service.signRequest should be executed after setting payload, params etc

**Comment by maciejbak85** [comment]
hugh great it helped !

  

> def postData(file: File): String = {
>     import org.apache.commons.codec.binary.Base64
>     Base64.encodeBase64String(Files.readAllBytes(Paths.get(file.getAbsolutePath)))
>   }
> 
>   def uploadFile(file:File) : Unit = {
>     val request = new OAuthRequest(Verb.POST, "https://upload.twitter.com/1.1/media/upload.json", service.getConfig)
>     request.addBodyParameter("media_data", postData(file))
>     service.signRequest(accessToken, request)
>     val response = request.send()
>     println(response.getBody)
>   }

**Comment by kullfar** [comment]
cool! ;-)
