### ISSUE TITLE
Adding body parameter that is an object

### ISSUE THREAD

**Issue by phixMe** [scribejava/scribejava#733]
I wish to add a body parameter for the GitHub hooks api like below. These body parameters contain objects, not just strings. I haven't seen any instances where anybody has tried to do this in the issues documentation. I am getting a parse error from gitHub that says "Problems parsing JSON" when I try to issue this POST request. I have also noted the unusual escaping that shows in the getBodyContents() call, perhaps the source of the issue?

GitHub has the following in their API documentation:
```javascript
{
  "name": "web",
  "active": true,
  "events": [
    "push",
    "pull_request"
  ],
  "config": {
    "url": "http://example.com/webhook",
    "content_type": "json"
  }
}
```

Adding in the body parameters:
```java
request.addBodyParameter("name", "web");
request.addBodyParameter("config", "{\"url\":\"http://demo.local.com/GoughApi/webresources/service\",\"content_type\":\"json\"}");
request.addBodyParameter("events", "[\"push\",\"pull_request\"]");
request.addBodyParameter("active", "true");
```

When I call the `request.getBodyContents()` I see:
```sh
name=web&config=%7B%22url%22%3A%22http%3A%2F%2Fdemo.local.com%2Fapi%2Fwebresources%2Fservice%22content_type%22%3A%22json%22%7D&events=%5B%22push%22%2C%22pull_request%22%5D&active=true
```

**Comment by kullfar** [comment]
Hi, you shouldn't parse the json yourself and set several body params.
You have to set one big payload. All this json - is the one body param in terms of HTTP.
Serialize somehow your json (usual String for example), and use setPayload method then. like this
{code}
.setPayload("{\n" +
"  \"name\": \"web\",\n" +
"  \"active\": true,\n" +
"  \"events\": [\n" +
"    \"push\",\n" +
"    \"pull_request\"\n" +
"  ],\n" +
"  \"config\": {\n" +
"    \"url\": \"http://example.com/webhook\",\n" +
"    \"content_type\": \"json\"\n" +
"  }\n" +
"}");{code}

**Comment by phixMe** [comment]
Thanks for the help. 

I found:
`request.addPayload(jsonObject)`

and that seems to work great.
