### ISSUE TITLE
JDKHttpClient does not include body in PATCH requests

### ISSUE THREAD

**Issue by eyeled** [scribejava/scribejava#737]
Changing line 99 in JDKHttpClient.java from:
        if (httpVerb == Verb.POST || httpVerb == Verb.PUT || httpVerb == Verb.DELETE) {
to:
        if (httpVerb == Verb.POST || httpVerb == Verb.PUT || httpVerb == Verb.DELETE || httpVerb == Verb.PATCH) {

seems to fix it.

**Comment by kullfar** [comment]
fixed, thanks.
fix in the master https://github.com/scribejava/scribejava/commit/bd9a43018147cd72e5d2d04ad76752c3b4065ae4
