### ISSUE TITLE
OAuth Implementation for IBM

### ISSUE THREAD

**Issue by priyadarshi035** [scribejava/scribejava#738]
Hi,
I am trying to authenticate sonarqube with our company saml directory.Since SonarQube doesnot have saml plugin i came across Google Oauth plugin which uses your code.So is it possible to implement this for IBM also.
Regards,
Peter
priyadarshi035@gmail.com

**Comment by kullfar** [comment]
I think there is nothing impossible. Pull Requests are welcome ;-)
You can start by looking existing pull requests with new APIs. From the latest, it is https://github.com/scribejava/scribejava/pull/718/files I think. And look the wiki https://github.com/scribejava/scribejava/wiki
