### ISSUE TITLE
Outdated exampled?

### ISSUE THREAD

**Issue by bangoker** [scribejava/scribejava#740]
I'm trying to follow the example used I'm seeing that this call is deprecated: 

`final OAuthRequest request = new OAuthRequest(Verb.GET, "https://api.twitter.com/1.1/account/verify_credentials.json", service);` (though the constructur without the `service` parameter is not deprecated)

and the request object doesn't even have the `send` method used here:

`final Response response = request.send();`

Am I'm doing something wrong or are the examples just outdated? If so, what is the new way to actually send the request?

This is using V4 from gradle:
    `compile 'com.github.scribejava:scribejava-apis:4.0.0'`

**Comment by kullfar** [comment]
Hi, actual always-working examples are here
https://github.com/scribejava/scribejava/tree/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples
