### ISSUE TITLE
Respose comming 400 bad request

### ISSUE THREAD

**Issue by Amirulhos** [scribejava/scribejava#742]
I am implementing garmin integration, after getting access token and secret I am calling a api for json and getting code-400, message- Bad request, my code is here.

 OAuthService service = new ServiceBuilder()
            .provider(TradeKingAPI.class)
            .signatureType(SignatureType.Header)
            .apiKey("XXXX")
            .apiSecret("XXXXXXXXXXXX")
            .build();

  OAuthRequest request = new OAuthRequest(Verb.GET, "https://gcsapitest.garmin.com/wellness-api/rest/dailies");
                    request.addQuerystringParameter("format","json");
                    request.addQuerystringParameter("uploadStartTimeInSeconds", String.valueOf(time));
                    request.addQuerystringParameter("uploadEndTimeInSeconds", String.valueOf(pre_time));
                    service.signRequest(accessToken, request1);
                    response = request.send();
                    System.out.println(response.getBody());

**Comment by eshkoliGilad** [comment]
Hi, I'm implementing also the Garmin API using this library but could get a hold of how the Provider class should look. (Your TradeKingAPI.class), can you share that with me, please?

**Comment by Amirulhos** [comment]
Sure, give me your email id. So, I can send you.

**Comment by eshkoliGilad** [comment]
eshkoli.gilad@gmail.com

Thanks a lot !
