### ISSUE TITLE
Wrong signature type used in LinkedInApi20

### ISSUE THREAD

**Issue by realtybaron** [scribejava/scribejava#743]
I just integrated with LinkedIn using scribejava but get receiving a 401 Unauthorized response when attempting to make a request after obtaining an access token. In the end, I realized the LinkedIn docs specify putting the token in the header rather in the query string.

```
@Override
    public SignatureType getSignatureType() {
        return SignatureType.BEARER_AUTHORIZATION_REQUEST_HEADER_FIELD;
    }
```

**Comment by realtybaron** [comment]
Disregard. I see now the signature type can be overridden via the `ServiceBuilder`.

**Comment by kullfar** [comment]
Hm... It shouldn't help you.
signatureType in ServiceBuilder is used on OAuth1.0 only. BTW, thanks for pointing this, I'll fix that somehow.

**Comment by kullfar** [comment]
Do you use LinkedInApi20 or LinkedInApi?

**Comment by realtybaron** [comment]
LinkedInApi20

I followed the example [here](https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples/LinkedIn20Example.java) which does use `ServiceBuilder`. Here is my resulting code which seems to work:

```
ServiceBuilder builder = new ServiceBuilder()
                .state(RandomUtil.string(8))
                .apiKey("xxxxxx")
                .apiSecret("xxxxxx")
                .signatureType(SignatureType.Header)
                .callback("https://www.youworthapp.com" + LinkedInAccessAction.path);
        this.bind(OAuth20Service.class).annotatedWith(Names.named("linkedin")).toInstance(builder.build(LinkedInApi20.instance()));
```

**Comment by kullfar** [comment]
FYI,
https://github.com/scribejava/scribejava/commit/4cd58302f9e252e0a3c355b1f842a527e9b6af3d

there will be no more 'signatureType' method in ServiceBuilder.
signatureType is defined in API. default in DefaultApi and overridden in any other API which need it to override
