### ISSUE TITLE
Correct Gradle Address? 

### ISSUE THREAD

**Issue by OmarBizreh** [scribejava/scribejava#744]
Hi, The only address I was able to use for your API was compile 'org.scribe:scribe:1.3.5'
while if I add compile 'com.github.scribejava:scribejava-apis:4.0.0' everything breaks
For example:
Verifier: Not found
service.getAccessToken: No such method
OAuthConstants: Doesn't exist

Everything is working for me on v1.3.5 but OAuth1 request signature is not working for me while Postman is generating the correct signature with the same parameters I pass to your library, thought I'd update to latest version to check if it is fixed

I'm authenticating agains Magento 1.9 with a custom OAuth API derived from DefaultApi10a

**Comment by kullfar** [comment]
v1.3.5 is very old. 4.0.0 have a lot not fully compatible improvements, fixes and architectural changes.
You will need to adapt your code to use the last version.
Look any Example here https://github.com/scribejava/scribejava/tree/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples
to understand what you have to change

**Comment by OmarBizreh** [comment]
My issue is not migrating to your latest version, my issue is [your documentations for v4](http://www.javadoc.io/doc/com.github.scribejava/scribejava-core/4.0.0) has signRequest function, but when I add your latest version to gradle I do note find this function in the service instance and if I check OAuth10aService code the sign request isn't there. What to do from here?

**Comment by kullfar** [comment]
Hm. The method is here https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/oauth/OAuth10aService.java#L140
As for Verifier class, there is no such class in ScribeJava anymore.
Maybe it's a gradle problem? Try to compare jar from maven central and jar gradle downloads for you

**Comment by OmarBizreh** [comment]
Everything is working now, updated Android Studio to 2.3 which also upgrades gradle, I think something was wrong in gradle. My signing issue also got fixed in v4.0.0 
Thank you for you help much appreciated :)

**Comment by kullfar** [comment]
cool!
welcome
