### ISSUE TITLE
Support for Single Sign On capability with CloudFoundry?

### ISSUE THREAD

**Issue by Omnipresent** [scribejava/scribejava#745]
CloudFoundry makes an SSo service available that makes the following env vars available to the deployed application that is bind to the sso service:

     "auth_domain": "https://ssotest.login.com",
     "client_id": "jhjh-some-client-id",
     "client_secret": "jhj-some-client-secret"

Then an application can consume this information to make OAuth connection. Here is an example of such an applicatio (Java)

https://github.com/pivotal-cf/identity-sample-apps/blob/develop/non-spring-boot-sample/src/main/java/SsoServiceInfoCreatorInitializer.java

My question is: Can Scribe be used to do what the above linked app is doing? Basically getting the environment variables to do the SSO OAuth authentication. Irrespective of the identity provider being used by the SSO service.

**Comment by kullfar** [comment]
Dunno...
IMHO it's out-of-scope for OAuth library, like ScribeJava. And it's a API specific thing, not some OAuth standard extension, right?
If you can extend some API in ScribeJava or can use it for your task somehow - feel free to create PullRequest or add some notes to wiki https://github.com/scribejava/scribejava/wiki

**Comment by Omnipresent** [comment]
@kullfar I am thinking of doing this, please let me know if this would work:

1. Create a custom api with OAuth 2.0 as described here https://github.com/scribejava/scribejava/wiki/Custom-Apis
2. Get `AUTHORIZE_URL`, `api_key`, and `api_secret` from the above mentioned environment variables: `auth_domain`, `client_id`, `client_secret`
3. And just hope it work?... :)

Am I missing something?

**Comment by kullfar** [comment]
Looks good. XXXApi.java will take environment variables, use domain to construct access points (different urls) and then will use provided client credentials in overrided "public OAuth20Service createService(OAuthConfig config)" method to create new Service. Looks like a solution.

**Comment by kullfar** [comment]
The only problem I see for the moment. How can I run the XXXExample.java to test new code  ;-)

**Comment by Omnipresent** [comment]
@kullfar I've been able to make good progress but I am stuck and would really appreciate some guidance. I am using Scribe 1.3.6

When I get redirected to login page for my third party OAuth2 and enter the correct uname/pwd, I get the following error: 

> No client with requested id: null

In a separate application that works with this OAuth and that is not using ScribeJava but Spring and other stuff the authentication works. In that scenario the following are sent in the body:

```
URL: https://oauth_provider_url/oauth/authorize
client_id:b56b0543-fb79-4405-8c83-dabe09c77bb6
redirect_uri:http://my-spring-application/
response_type:code
state:4MiLKp
```

However, when I get the error using ScribeJava I see nothing in the request body and I believe this is why I'm getting an error. 

So my **question** is: How can I replicate the request body for authorize to be similar to the one I know that works (listed above)?

**Details**

My API:

```
package com.acme.scribe;
import org.scribe.builder.api.DefaultApi20;
import org.scribe.model.OAuthConfig;
import grails.util.Holders;
public class SomeOauth2API extends DefaultApi20 {
	@Override
	public String getAccessTokenEndpoint() {
		return System.getenv("auth_domain") + "/oauth/token";
	}

	@Override
	public String getAuthorizationUrl(OAuthConfig arg0) {
		return System.getenv("auth_domain") + "/oauth/authorize";
	}
}
```

I use it like this:

```
OAuthService service = new ServiceBuilder()
                                  .apiKey(System.getenv("client_id"))
                                  .apiSecret(System.getenv("client_secret))
                                  .build(SomeOauth2API.instance());
```

This is the method that executes when I actually click "login using oauth2" in my application:

```
    def authenticate() {
         OAuthService service = new ServiceBuilder()
                                  .apiKey(System.getenv("client_id"))
                                  .apiSecret(System.getenv("client_secret))
                                  .build(SomeOauth2API.instance());
         Token requestToken = new Token('','')
         String url = service.getAuthorizationUrl(providerName, requestToken)
          return redirect(url: url)
    }
```

**Comment by Omnipresent** [comment]
@kullfar Please disregard the above. After some digging around and stopping dependence on an old grails plugin (github.com/antony/grails-oauth-scribe) that was using 1.3.6 version of ScribeJava. I decided to use the latest version. I modified my API to be like below:

```
public class MyAPI extends DefaultApi20 {
    protected MyAPI() {
    }
    private static class InstanceHolder {
        private static final MyAPI INSTANCE = new MyAPI();
    }    
    @Override
    public String getAccessTokenEndpoint() {
	return "https://myapi.com/oauth/token";
    }
    public static MyAPI instance() {
        return InstanceHolder.INSTANCE;
    }	
    @Override
    public String getAuthorizationUrl(OAuthConfig config, Map<String, String> additionalParams) {
        final ParameterList parameters = new ParameterList(additionalParams);
        parameters.add(OAuthConstants.RESPONSE_TYPE, "code");
        parameters.add(OAuthConstants.CLIENT_ID, config.getApiKey());

        final String callback = config.getCallback();
        if (callback != null) {
            parameters.add(OAuthConstants.REDIRECT_URI, "https://myapplication.com/someurl");
        }

        final String scope = config.getScope();
        if (scope != null) {
            parameters.add(OAuthConstants.SCOPE, scope);
        }

        final String state = config.getState();
        if (state != null) {
            parameters.add(OAuthConstants.STATE, state);
        }

        return parameters.appendTo("https://myapi.com");
    }    
}
```

And then I simply use it like this:

```
   def authenticate() {
		OAuthService service = new ServiceBuilder()
                                  .apiKey(System.getenv("api_key"))
                                  .apiSecret(System.getenv("api_secret"))
                                  .build(MyAPI.instance());
        String url =  service.getAuthorizationUrl();
        return redirect(url: url)
    }
```

Now when I try to authenticate, the following items are being sent:

```
URL: https://oauth_provider_url/oauth/authorize
client_id:someasdlkj-client-laksj-id
redirect_uri:https://myapplication.com
response_type:code
```

The above works pretty much great out of the box, except a few things:

1. I am still missing `state` from response body. How can I get that?
2. When I enter the correct credentials on my oauth providers login page, I am not being redirected to my application. Is there something special that needs to happen for that?
3. In my `authenticate()` method, how can I get the `authorizationcode` that is returned from my Oauth provider?

Thanks!!

**Comment by kullfar** [comment]
Hi.
1.you need to set 'state' param in your request.
for example
```
   def authenticate() {
		OAuthService service = new ServiceBuilder()
                                  .apiKey(System.getenv("api_key"))
                                  .apiSecret(System.getenv("api_secret"))
                                  .state("your_state_here")
                                  .build(MyAPI.instance());
        String url =  service.getAuthorizationUrl();
        return redirect(url: url)
    }
```

2.maybe you need to set callback url?
```
.callback("http://your.site.com/callback")
```
3.You should get this param ('code') in GET params in callback.  Like this http://your.site.com/callback?code=xxx
