### ISSUE TITLE
send()

### ISSUE THREAD

**Issue by 616c** [scribejava/scribejava#750]
Hi Stas,
trying to get started with the 'Get Started' example in the wiki. In step 5, seems the request.send() method is gone during refactoring early this year. Is there a working example somewhere around?
Much Thanks for help & for scribejava in general!
Andreas

**Comment by kullfar** [comment]
Hi,

Working runnable examples are here https://github.com/scribejava/scribejava/tree/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples

Regards,
Stas
