### ISSUE TITLE
Response Body format is changed by Facebook 

### ISSUE THREAD

**Issue by mihirgohel** [scribejava/scribejava#752]
Hi, 

I already have integrated with Facebook and running the code live. 

It started throwing exception from today with message 

> org.scribe.exceptions.OAuthException: Response body is incorrect. Can't extract a token from this:

thrown exception stack is: 
`org.scribe.exceptions.OAuthException: Response body is incorrect. Can't extract a token from this: '{"access_token":"EAAWZCVqCZCIzkBALdZA9wZBS5ZAYC6ZAS1ZCrs3GrzRwwEoswqDcC1As6C0jhVMddgrzbyP0U3I4uaUMsoKTbFYfZBq1BLOP3TL0sDKHSOZBSyARhhPN7RquUz820ly2J32W6Um7yCdEYlGdYWt493jOggxXl45G8TYIZD","token_type":"bearer","expires_in":5178133}'
	org.scribe.extractors.TokenExtractor20Impl.extract(TokenExtractor20Impl.java:32)
	org.scribe.oauth.OAuth20ServiceImpl.getAccessToken(OAuth20ServiceImpl.java:37)`

**Comment by kullfar** [comment]
Hi, you are using very, very-very old version of SribeJava, pls upgrade.

**Comment by jako512** [comment]
There is simple fix for version 1.x: https://github.com/jako512/scribejava/commit/faaaba
