### ISSUE TITLE
Additional parameters when obtaining request token

### ISSUE THREAD

**Issue by vivin** [scribejava/scribejava#753]
Please let me know if I am reading the spec wrong. Under section 6.1.1 of the OAuth 1.0a spec, it mentions that it is possible to provide additional parameters when obtaining a request token:

>6.1.1.  Consumer Obtains a Request Token

> To obtain a Request Token, the Consumer sends an HTTP request to the Service Provider's Request Token URL. The Service Provider documentation specifies the HTTP method for this request, and HTTP POST is RECOMMENDED. The request MUST be signed and contains the following parameters:
> 
> oauth_consumer_key: The Consumer Key.
> oauth_signature_method: The signature method the Consumer used to sign the request.
> oauth_signature: The signature as defined in Signing Requests.
> oauth_timestamp: As defined in Nonce and Timestamp.
> oauth_nonce: As defined in Nonce and Timestamp.
> oauth_version: OPTIONAL. If present, value MUST be 1.0 . Service Providers MUST assume the protocol version to be 1.0 if this parameter is not present. Service Providers' response to non-1.0 value is left undefined.
> oauth_callback: An absolute URL to which the Service Provider will redirect the User back when the Obtaining User Authorization step is completed. If the Consumer is unable to receive callbacks or a callback URL has been established via other means, the parameter value MUST be set to oob (case sensitive), to indicate an out-of-band configuration.
> **Additional parameters: Any additional parameters, as defined by the Service Provider.**

However, I notice that the `getRequestToken()` does not provide a way to specify additional parameters. It isn't possible to override as it is final, and I am unable to override `prepareRequestTokenRequest` (as I could in 3.x) in order to supply these parameters, since it not only creates the request within that method, but signs it there as well using the private `appendSignature` method.

**Comment by kullfar** [comment]
It's better to use this final official RFC https://tools.ietf.org/html/rfc5849
interested section is
https://tools.ietf.org/html/rfc5849#section-2.1

as for your question... I see... So making methods addOAuthParams and  appendSignature protected will solve your issue?

**Comment by vivin** [comment]
Yes, that would definitely help. You can make them final also, so that it will lessen the chances of someone messing up that core part by overriding those methods. 

I can submit a PR if need be.

**Comment by vivin** [comment]
Another option is to override the `getRequestToken` and `getRequestTokenAsync` methods and provide ones that accept a `Map<String, String> additionalParameters` argument. What do you think?

**Comment by vivin** [comment]
I have the PR ready -- I opted to just make `appendSignature` and `addOAuthParams` `protected final`. Otherwise, if overload the `getRequestToken` and `getRequestTokenAsync` methods to expose ones that take additional parameters, I would have to change the signature of `prepareRequestTokenRequest` as well, which would be a breaking change. To get around that, I could have also exposed a protected `prepareRequestTokenRequest` that didn't take in additional parameters, but that doesn't seem very clean, as it wouldn't actually be used by anything. 

Maybe we can explicitly support the ability to supply additional parameters to `getRequestToken` in the next major release.

**Comment by kullfar** [comment]
No need to make them final. If someone want to mess up, let him mess up ;-)
as for additionalParameters argument - it will be hard to understand where and how to add this params  to the request. And seems it's a rare case. Better to override prepareRequestTokenRequest.

**Comment by vivin** [comment]
@kullfar Do you want me to take out `final`? :D I thought that it would be the smallest change required to get this working and didn't want to go any further. :)

**Comment by kullfar** [comment]
I want you not to add 'final' ;-) Anyway, you can leave it as is, I'll remove them while merging to the master

**Comment by vivin** [comment]
Ok! :)

**Comment by kullfar** [comment]
Pull Request https://github.com/scribejava/scribejava/pull/755 merged, releasing to the central today
