### ISSUE TITLE
Verifying the OAuth API is well configured without going through the authorization process

### ISSUE THREAD

**Issue by victornoel** [scribejava/scribejava#754]
I didn't find any way to do it, but maybe I didn't look well enough (or maybe OAuth does not permit this kind of usage… I'm no expert :).
Anyway, this is a feature request for testing that an instantiated `OAuthService` is correctly configured with respect to the key and secret, but without the need to actually go through the process of authorizing someone.

The use case would be to use this functionality to implement a dropwizard health check: http://www.dropwizard.io/1.1.0/docs/manual/core.html#health-checks

**Comment by kullfar** [comment]
"correct" configuration depends on the future usage of the OAuthService. e.g. secret is not always needed.

as for key - it's mandatory for the moment. And it's checked on build() stage. check here
https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/builder/ServiceBuilder.java#L148

```
    public void checkPreconditions() {
        Preconditions.checkEmptyString(apiKey, "You must provide an api key");
    }

    private OAuthConfig createConfig() {
        checkPreconditions();
        return new OAuthConfig(apiKey, apiSecret, callback, signatureType, scope, debugStream, state, responseType,
                userAgent, httpClientConfig, httpClient);
    }

    /**
     * Returns the fully configured {@link S}
     *
     * @param <S> OAuthService implementation (OAuth1/OAuth2/any API specific)
     * @param api will build Service for this API
     * @return fully configured {@link S}
     */
    public <S extends OAuthService<?>> S build(BaseApi<S> api) {
        return api.createService(createConfig());
}
```

So you can not instantiate OAuthService without providing mandatory param (apiKey).

**Comment by victornoel** [comment]
@kullfar I meant correct w.r.t. to the actual deployed real oauth service (e.g., is the URL reachable, is the key/secret actually recognized by the oauth service, etc), not correct in the sense of "are the parameters present".

**Comment by kullfar** [comment]
Hm... Interesting ;-) But it looks like impossible without support from the server side. Or it will be very specific to concrete OAuth provider, anyway, if you or someone will make smth - Pull Requests are welcome ;-)

**Comment by victornoel** [comment]
@kullfar ok, so you mean that OAuth itself does not provide any way to implement that in a generic way? (I have exactly ZERO experience with OAuth, so I may completely off ^^).
I guess the only option we would have is to:
1. do a request with a fake auth request, and
2. be able to determine if the returned error is caused by the key/secret or by the fake auth request (so it is dependant on the OAuth service implementation as you said)

Could we reopen the issue then? :)

**Comment by kullfar** [comment]
At least I don't know such ways.
As for spec, you can read OAuth2 here https://tools.ietf.org/html/rfc6749
I think it's better to request not a fake request, but some real service. like 'getIdOfMyApplication" or "getMyBalance" or smth like that.

As you correctly mentioned before, it's a feature request. And it should be placed in PullRequests, not in the issues list ;-)

**Comment by victornoel** [comment]
> As you correctly mentioned before, it's a feature request. And it should be placed in PullRequests, not in the issues list ;-)

Pull Request are for actual code proposition, not for the feature request itself… that's the whole point of using issue to track feature request until a PR is made and merged.

**Comment by kullfar** [comment]
Nobody interested in feature requests. Nobody will implement them, so no need to track them in issues.
And PRs are welcome by all users.
That's my view.

**Comment by victornoel** [comment]
ok :)
