### ISSUE TITLE
Reading response body with Instagram custom

### ISSUE THREAD

**Issue by kfredy** [scribejava/scribejava#757]
Hi,
I'm trying to read Instagram api response and sometimes i'm getting part of the response and not the full response (Json is broken, usually on more than 20,000 char). Running on Ubuntu machine.
i tested 3.10 and about to check on v4.0.0 (BTW wiki needs update)
is there any limitation on lengths? i saw some discussion on content length and gzip
=== custom class:
package Instagram;

import com.github.scribejava.core.builder.api.DefaultApi20;

public class InstagramApi20 extends DefaultApi20 {

    protected InstagramApi20() {
    }

    private static class InstanceHolder {
        private static final InstagramApi20 INSTANCE = new InstagramApi20();
    }

    public static InstagramApi20 instance() {
        return InstanceHolder.INSTANCE;
    }

    @Override
    public String getAccessTokenEndpoint() {
        return "https://api.instagram.com/oauth/access_token";
    }

    @Override
    protected String getAuthorizationBaseUrl() {
        return "https://api.instagram.com/oauth/authorize";
    }
}

**Comment by kullfar** [comment]
Hi, no, I haven't heard such things about content length limit.
Is it reproducible with Ning, AHC and OKhttp providers?

**Comment by kfredy** [comment]
Its not reproducible. v4.0.0. had issues as well. testing regular http request and see maybe some special char breaks the reading of the response. I'll update you. thanks

**Comment by kullfar** [comment]
So, as I can understand, problems are only with java.net.HttpURLConnection. This can localize problem to it. And it can means, that's not a problem with ScribeJava 	on the whole but in use of java.net.HttpURLConnection.

**Comment by kfredy** [comment]
I used only HttpUrlConnection and got part of the response
I think we can close this issue. I'll try to open an issue to Instagram.
Thanks for looking into it. Fredy
