### ISSUE TITLE
Facebook : Require an appsecret_proof argument

### ISSUE THREAD

**Issue by jkanniappan** [scribejava/scribejava#758]
@kullfar , I am facing the an issue with the FB appsecret (using scribejava 4.0.0).
The FB App requires AppSecret and I am not sure how to add it using scribeJava
below error I am getting from FB

{"error":{"message":"API calls from the server require an appsecret_proof argument","type":"GraphMethodException","code":100,"fbtrace_id":"C56WCiA1KFP"}}

**Comment by kullfar** [comment]
duplicates https://github.com/scribejava/scribejava/issues/640

**Comment by kullfar** [comment]
appsecret_proof support in the master https://github.com/scribejava/scribejava/commit/fd4f99ef56bbefcc75f0a028d14522a4711ebb11
