### ISSUE TITLE
oAuth URL Changed for LiveApi, Please change in the file, also a typo error in the example file

### ISSUE THREAD

**Issue by sony-george-ibs** [scribejava/scribejava#759]
Hello,
as per the document in **Authentication with OAuth** 
[(https://msdn.microsoft.com/en-us/library/bing-ads-user-authentication-oauth-guide.aspx)](https://msdn.microsoft.com/en-us/library/bing-ads-user-authentication-oauth-guide.aspx)

the url to do the authentication has been changed from "https://oauth.live.com/authorize" to "https://login.live.com/oauth20_authorize.srf" 
so please do change this in com.github.scribejava.apis.LiveApi.java line no 32 for the method **_protected String getAuthorizationBaseUrl()_**
```
    @Override
    protected String getAuthorizationBaseUrl() {
        return "https://oauth.live.com/authorize";
    }
```
should be 
```
    @Override
    protected String getAuthorizationBaseUrl() {
        return "https://login.live.com/oauth20_authorize.srf";
    }
```

also in the file _com.github.scribejava.apis.examples.LiveExample.java_ line no 16 the PROTECTED_RESOURCE_URL variable value used is a copy from the _com.github.scribejava.apis.examples.FoursquareExample.java_ , i think it is a typo mistake, which is not correct,

the correct value is **PROTECTED_RESOURCE_URL = "https://apis.live.net/v5.0/me";**
as per this doc from microsoft 
[https://msdn.microsoft.com/en-in/library/hh826533.aspx](https://msdn.microsoft.com/en-in/library/hh826533.aspx
)

Thanks and Regards
Sony George

**Comment by kullfar** [comment]
hm... interesting finding, thanks.
unfortunately, I need test application credentials and test user credentials to check this changes.
So I can't make this changes myself. I need Pull request with this diff and credentials to run the Example

**Comment by typhoon17** [comment]
Additionally to changes mentioned above the following change in LiveApi is needed

```
    @Override
    public Verb getAccessTokenVerb() {
        return Verb.POST;
    }
```

Source - https://msdn.microsoft.com/en-us/library/hh243647.aspx

**Comment by typhoon17** [comment]
My 5 cents - found some other issues mentioning this problem, which were closed/cancelled just because you don't have test credentials to test fix. That's really weird...

**Comment by kullfar** [comment]
You can always create a fork with any changes. But prior to merging changes back to the master I have to test them myself.

**Comment by kullfar** [comment]
It's not so hard to provide test credentials.

**Comment by typhoon17** [comment]
Hi Stas, test credentials (app id, secret and accepted return URL) sent to your gmail.
Please test changes and let me know when finished (I will remove test app).

**Comment by kullfar** [comment]
Gr8! Almost done. But I need test user credentials as well. Thanks!

**Comment by typhoon17** [comment]
Well, I will not share my user credentials...
Can you just register your own account on outlook.com? It's like registering gmail, should be simple.

**Comment by kullfar** [comment]
Sorry, no (c) https://github.com/scribejava/scribejava/wiki/FAQ#when-will-you-support-insert_api_here-
I do not need your user, it can be new user, created specially for testing.

**Comment by typhoon17** [comment]
How complicated :)
Test account sent to your email.

**Comment by kullfar** [comment]
Super. Have tested and merged to the master.
You can drop test user and application, I do not need them more.
Thanks again

**Comment by kullfar** [comment]
https://github.com/scribejava/scribejava/commit/3b3cbcc8090df83f02252ad816363a050700381b

**Comment by typhoon17** [comment]
Thanks Stas!

**Comment by xmeng1** [comment]
+1

**Comment by kullfar** [comment]
will release in 1-2 hour

**Comment by kullfar** [comment]
done. 4.1.2 well appear in the maven central in 15min - 2 hour.
