### ISSUE TITLE
atlassian and sbt 

### ISSUE THREAD

**Issue by holzfelix** [scribejava/scribejava#761]
Hi can I use sbt to set the dependencies to this project?

can I use it to oAuth atlassian as well?

**Comment by kullfar** [comment]
What is the "sbt"? I don't know what is it, so I can not answer you, sorry.
As for atlassian - sure, but not from the box. You will need to implemend DefaultApi20 or DefaultApi10a yourself. You can start with looking small wiki here
https://github.com/scribejava/scribejava/wiki
this chapter
https://github.com/scribejava/scribejava/wiki/Custom-Apis

Wiki is always a bit outdated, but is ok in general.
