### ISSUE TITLE
How to use a client AccessToken like in Twitter

### ISSUE THREAD

**Issue by Mdhaker** [scribejava/scribejava#764]
Can we create OAuth1AccessToken from a String ? if we want to test it with the app generated access token in Twitter how we do that ?

**Comment by kullfar** [comment]
Yep, you can. Use one of the provided constructor.
You can see examples of creating OAuth1AccessToken from the string in unit tests.

**Comment by kullfar** [comment]
or even you can use OAuth1AccessTokenExtractor
