### ISSUE TITLE
Verb.DELETE requests on Android <=4.4?

### ISSUE THREAD

**Issue by rnekicOD** [scribejava/scribejava#766]
I'm trying to send a DELETE request and I'm not including any body parameters or data.  I see the Verb.DELETE permits a body and JDKHttpClient ends up adding a 0-length byte array and sets connection.doOutput(true) in addBody.  On Android <=4.4, this causes a ProtocolException ("DELETE does not support writing").  More recent versions of Android don't seem to have this concern and it all works fine.

Possible solution: check bodyContents length in JDKHttpClient.addBody and skip connection.doOutput, etc. when length == 0?

**Comment by kullfar** [comment]
It was introduced here
https://github.com/scribejava/scribejava/commit/a1cb90a9688c6d36ef81ec9c4ea53b9e7db90dff#diff-455545b18f9da7afdd0db36dc6fa293bR53
in v4.0.0

http DELETE method supports body, so ScribeJava starting from v4.0.0 support sending body with DELETE method.

Actually, you will get the same error while executing any http request with the support for Body contents, but not providing one (POST, PUT, DELETE, PATCH) (c) https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/model/Verb.java#L8

**Comment by kullfar** [comment]
I will fix it now

**Comment by kullfar** [comment]
ready, fixed
https://github.com/scribejava/scribejava/commit/17e9220b72965a67726011e0f7255d9e2cb6cf4d
