### ISSUE TITLE
params name when creating access token from String

### ISSUE THREAD

**Issue by Mdhaker** [scribejava/scribejava#769]
Hello,

I had a problem creating an access token from a string with Google, because it uses the param key instead of access token, when I provide the Google API key it gives this URL with the params access_token, while it shoud be " key " !

How to change it ?

https://www.googleapis.com/plus/v1/people?query=lorem&access_token=**************

**Comment by kullfar** [comment]
I do not understand you.
Who uses the param key instead of access token?
whom do you give Google API key, who gives you an URL with access_token param. Why should it be 'key'?

**Comment by Mdhaker** [comment]
Google uses "Key" in GET param to make calls to public endpoints (Google API key), so in order for my query to work it should be like this : 
`https://www.googleapis.com/plus/v1/people?query=lorem&key=**************`

but not 

`https://www.googleapis.com/plus/v1/people?query=lorem&access_token=**************`

by default when we create an access token from String it uses " access_token"

**Comment by kullfar** [comment]
1.It's not OAuth2 part.
2.According to Google docs
key - API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.

access_token - OAuth 2.0 token for the current user. Learn more about OAuth. 

https://developers.google.com/+/web/api/rest/
3.You can try implement your request this way:
        final OAuthRequest request = new OAuthRequest(Verb.GET, https://www.googleapis.com/plus/v1/people?query=lorem&key=**************);
// skip signing
//        service.signRequest(accessToken, request);
        final Response response = service.execute(request);

**Comment by kullfar** [comment]
Or we can override method for GoogleService, like here
https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/main/java/com/github/scribejava/apis/service/ImgurOAuthServiceImpl.java#L36

in case 'key' param is common for all public APIs in Google

**Comment by Mdhaker** [comment]
Even Flickr uses the param "key_api" I think it should be generic but anyway I will try send the request with signing as you said, Thanks for the reply.
