### ISSUE TITLE
What about dropbox ?

### ISSUE THREAD

**Issue by arelaxend** [scribejava/scribejava#774]
Hi,

Dropbox is not yet implemented but it requires also oauth2.

Cheers,
A.

**Comment by chooco13** [comment]
> You can implement your own API by extending `Default10Api` or `Default20Api` and defining the endpoints.

please see
https://github.com/scribejava/scribejava/wiki/FAQ#when-will-you-support-insert_api_here-

**Comment by arelaxend** [comment]
👍  thank you.
For Dropbox, the URL must contain "&response_type=token". Otherwise it does not work. Is there a way to add this parameter to the ServiceBuilder ? I am not familiar with scribejava.

**Comment by arelaxend** [comment]
The url should be : `https://www.dropbox.com/1/oauth2/authorize?client_id=<app key>&response_type=token&redirect_uri=<redirect URI>&state=<CSRF token>`

**Comment by kullfar** [comment]
just implement it in the overrided
    /**
     * Returns the URL that receives the access token requests.
     *
     * @return access token URL
     */
    public abstract String getAccessTokenEndpoint();

**Comment by arelaxend** [comment]
Fine. There is a different issue. After receiving the "code", to have the token the process is not usual. This is not a GET request but a POST request. The format is:
```
curl 'https://api.dropboxapi.com/oauth2/token' \
-X POST \
-H 'Content-Type: application/x-www-form-urlencoded' \
--data-binary 'code=<code>&grant_type=authorization_code&client_id=<client_id>&client_secret=<secret>&redirect_uri=<redirect_uri>' \
-vvvv
```

Any idea how to override sendAccessTokenRequestSync() ? Or ?
