### ISSUE TITLE
Request Microsoft Graph OneDrive Example 

### ISSUE THREAD

**Issue by xcomprs** [scribejava/scribejava#776]
Hi Guys,

I trying to connect to Microsoft Graph generating a JWT Access Token but is not working.

Do you have scribejava's example that works for this platform ?

grant_type=client_credentials
client_id=AS_REGISTERED_ABOVE
client_secret=AS_REGISTERED_ABOVE
redirect_uri=https://backendapplicationuri
resource=https://graph.microsoft.com/ (This is important as rest of the document will be using this API to access OneDrive).

curl -X POST -H "Cache-Control: no-cache" -H "Content-Type: application/x-www-form-urlencoded" -d 'grant_type=client_credentials&client_id=XXXXXX&client_secret=XXXXXXXXXX&redirect_uri=https://backendappuri&resource=https://graph.microsoft.com/' "https://login.microsoftonline.com/azure_domain/oauth2/token"

Thanks !!

**Comment by kullfar** [comment]
Sorry, no examples

**Comment by kullfar** [comment]
Sorry, we have no examples ;-(
You can add them in case of success! ;-)
