### ISSUE TITLE
Correct branch for v1.x

### ISSUE THREAD

**Issue by jako512** [scribejava/scribejava#777]
I believe branch [1.3.7](https://github.com/scribejava/scribejava/tree/1.3.7) is placed incorrectly on version 2.2.2 - I suggest moving it to corresponding tag [1.3.7](https://github.com/scribejava/scribejava/releases/tag/1.3.7) or even better to remove it and create branch "1.x" on last commit compatible with version 1.x (e.g. 0311a435fa492cbaa87f4e1c63395f33770d7d38) so that critical hotfix PR is possible for v1.x.

**Comment by kullfar** [comment]
Thanks, I have dropped branches '1.3.7' and 'scribejava-2.2.2' to not confuse anyone anymore.
As for new 1.x branches - this version is not supported, so no PRs are welcome. Do we need such branch in this case?

**Comment by jako512** [comment]
I think that 1.x branch is useful at least as history reference. I understand that it is not supported anymore but there are still people stuck with 1.x version (e.g. using Grais 2.x) and it would be good to have the possibility to hotfix API changes that causes it to stop working recently.

**Comment by kullfar** [comment]
For history reference - there are corresponding release Tags.
As for HotFix - anyone can checkout/fork from any historical tag and fix it for himself.
Or even he can just write and use their own API class (in case it's only changes, he need).

And creating this 1.x branch can mess up other users, making them think, it's still supported.
