### ISSUE TITLE
The example doesn't work with Flickr - could not fetch a request token

### ISSUE THREAD

**Issue by miguelD73** [scribejava/scribejava#781]
Hello,

It seems that  the "Fetching the Request Token..." from the example doesn't work anymore with Flickr ...

```
        System.out.println("=== Flickr's OAuth Workflow ===");
        System.out.println();

        // Obtain the Request Token
        System.out.println("Fetching the Request Token...");
        final OAuth1RequestToken requestToken = service.getRequestToken();
        System.out.println("Got the Request Token!");
        System.out.println();
```

The getRequestToken() in debug mode give the following info :

```
Fetching the Request Token...
obtaining request token from https://www.flickr.com/services/oauth/request_token
setting oauth_callback to oob
generating signature...
using base64 encoder: CommonsCodec
base string is: POST&https%3A%2F%2Fwww.flickr.com%2Fservices%2Foauth%2Frequest_token&oauth_callback%3Doob%26oauth_consumer_key%xxx%26oauth_nonce%3D496610766%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1499846779%26oauth_version%3D1.0
signature is: 7pUG1sADinLOiQ6xaJHefej3/X4=
appended additional OAuth parameters: { oauth_nonce -> 496610766 , oauth_signature -> 7pUG1sADinLOiQ6xaJHefej3/X4= , oauth_callback -> oob , oauth_consumer_key -> xxx , oauth_timestamp -> 1499846779 , oauth_signature_method -> HMAC-SHA1 , oauth_version -> 1.0 }
using Http Header signature
sending request...
response status code: 411
```

Is it a trouble with flickr or the code?

**Comment by kullfar** [comment]
this commit https://github.com/scribejava/scribejava/commit/17e9220b72965a67726011e0f7255d9e2cb6cf4d
brokes Flickr
I'll fix it on the ScribeJava side

**Comment by kullfar** [comment]
relates https://github.com/scribejava/scribejava/issues/766

**Comment by kullfar** [comment]
fixed.
https://github.com/scribejava/scribejava/commit/98ec232371e521af119ed4d5489594163adbe3e3 in the master

**Comment by miguelD73** [comment]
And as long you're doing change in the example

( scribejava-apis/src/test/java/com/github/scribejava/apis/examples/FlickrExample.java )

this line :
private static final String PROTECTED_RESOURCE_URL = "http://api.flickr.com/services/rest/";

should be :
private static final String PROTECTED_RESOURCE_URL = "http**s**://api.flickr.com/services/rest/";

**Comment by kullfar** [comment]
Is Flickr works on https only?
In any case I need test user/app to run the example and to test any changes to it

**Comment by miguelD73** [comment]
Now, yes (for some months I think) flickr is only https.

And yes, I understand for testing and all but as I was trying the example and saw that mistake, I just said it

(and yes, with the change, now it works!)
