### ISSUE TITLE
live resource url correct?

### ISSUE THREAD

**Issue by JurrianFahner** [scribejava/scribejava#785]
In file `scribejava/scribejava-apis/src/test/java/com/github/scribejava/apis/examples/LiveExample.java`:

```java
    private static final String PROTECTED_RESOURCE_URL
            = "https://api.foursquare.com/v2/users/self/friends?oauth_token=";
``` 

I don't think it's correct, it should be something like `https://graph.microsoft.com/v1.0/me/mailfolders/inbox/messages` with a bearer token in the headers.

**Comment by kullfar** [comment]
Yep. There are multiple issues and PRs about that, for example:
https://github.com/scribejava/scribejava/issues/366
https://github.com/scribejava/scribejava/pull/602/files
but no any approved PR yet ;-(
You can create it
