### ISSUE TITLE
PKCE support?

### ISSUE THREAD

**Issue by dieseldjango** [scribejava/scribejava#787]
I'm considering using this package for a project, but it doesn't look like it supports PKCE (https://tools.ietf.org/html/rfc7636), which is a requirement for me. Scanning through the code I don't see a way to pass in the code_verifier. Is anyone working on this? Would you welcome a contribution that adds this support?

**Comment by kullfar** [comment]
Hi,

hm... interesting. I will try to add this feature this week.
Thanks.

**Comment by kullfar** [comment]
Sorry, for the delay, was on vacation, I will try to return to this issue i next couple of week

**Comment by kullfar** [comment]
PKCE suport was added
https://github.com/scribejava/scribejava/commit/8d62f0cace86975a95c382fbf3176cbbf3881748
in the master

**Comment by dieseldjango** [comment]
Thanks! I'll try to find time to check it out.
