### ISSUE TITLE
LinkedIn Oauth fails

### ISSUE THREAD

**Issue by mudlee** [scribejava/scribejava#789]
We use scribdjava 4.1.1 and for a while, linkedin fails with 401. I found, that it's related to https://github.com/scribejava/scribejava/issues/773 where you say it's fixed in https://github.com/scribejava/scribejava/commit/30824b340cc68c6b5670450e3c295a3a108a76ee
But as I checked the commit, I couldn't see where is the newly added header parameter. Anyways, I tried both 4.1.2 and 4.2.0, both fail.

If I use 4.1.1 and add the header myself like:
`final OAuthRequest request = new OAuthRequest(Verb.GET, getResourceUrl());
        request.addHeader("oauth_token", token.getAccessToken());`
then it works. But it does not work neither with 4.1.2 nor with 4.2.0.

**I debugged the http request and saw the below.** 
_This was produced with 4.2.0 and failed:_
`DEBUG [2017-08-16 09:27:02,871] sun.net.www.protocol.http.HttpURLConnection: sun.net.www.MessageHeader@55b9b1467 pairs: {GET /v1/people/~ HTTP/1.1: null}{Authorization: Bearer MY_OAUTH_TOKEN}{oauth_token: MY_OAUTH_TOKEN}{User-Agent: Java/1.8.0_121}{Host: api.linkedin.com}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
DEBUG [2017-08-16 09:27:03,145] sun.net.www.protocol.http.HttpURLConnection: sun.net.www.MessageHeader@353c3e5c15 pairs: {null: HTTP/1.1 401 Unauthorized}{Server: Apache-Coyote/1.1}{x-li-request-id: A_REQUEST_ID}{Date: Wed, 16 Aug 2017 09:27:02 GMT}{Vary: *}{x-li-format: xml}{Content-Type: text/xml;charset=UTF-8}{Content-Length: 245}{X-Li-Fabric: prod-ltx1}{Connection: keep-alive}{X-Li-Pop: PROD-IDB2}{X-LI-Proto: http/1.1}{Set-Cookie: lidc="b=TB48:g=864:u=1:i=1502875622:t=1502962022:s=SOMETHING"}{X-LI-Route-Key: "b=TB48:g=864:u=1:i=1502875622:t=1502962022:s=SOMETHING"}{X-LI-UUID: SOMETHING}`

_This was produced with 4.1.1 with my additional header and succeeded:_
`DEBUG [2017-08-16 09:29:54,119] sun.net.www.protocol.http.HttpURLConnection: sun.net.www.MessageHeader@7b02a2346 pairs: {GET /v1/people/~?oauth2_access_token=MY_OAUTH_TOKEN HTTP/1.1: null}{oauth_token: MY_OAUTH_TOKEN}{User-Agent: Java/1.8.0_121}{Host: api.linkedin.com}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
DEBUG [2017-08-16 09:29:54,698] sun.net.www.protocol.http.HttpURLConnection: sun.net.www.MessageHeader@217d54da15 pairs: {null: HTTP/1.1 200 OK}{Server: Apache-Coyote/1.1}{x-li-request-id: A_REQUEST_ID}{Vary: *}{x-li-format: xml}{Content-Type: text/xml;charset=UTF-8}{Date: Wed, 16 Aug 2017 09:29:53 GMT}{X-Li-Fabric: prod-ltx1}{Transfer-Encoding: chunked}{Connection: keep-alive}{X-Li-Pop: PROD-IDB2}{X-LI-Proto: http/1.1}{Set-Cookie: lidc="b=TB48:g=864:u=1:i=1502875794:t=1502962194:s=SOMETHING"}{X-LI-Route-Key: "b=TB48:g=864:u=1:i=1502875794:t=1502962194:s=SOMETHING"}{X-LI-UUID: SOMETHING}`

**Comment by kullfar** [comment]
Hi,

> But as I checked the commit, I couldn't see where is the newly added header parameter. 
here
https://github.com/scribejava/scribejava/commit/30824b340cc68c6b5670450e3c295a3a108a76ee#diff-fbe464e7256cc20814269123448f8f92L39
LinkedIn had overrided default - OAuth2SignatureType.BEARER_URI_QUERY_PARAMETER;
After spciefied commit LinkedInAPI doesn't override this param and use default 
return OAuth2SignatureType.BEARER_AUTHORIZATION_REQUEST_HEADER_FIELD;

**Comment by kullfar** [comment]
> This was produced with 4.1.1 with my additional header and succeeded:

Looks very strange.
"/v1/people/~?oauth2_access_token=MY_OAUTH_TOKEN"
There is GET param here, not the HEADER.

Did you run this Example?
https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples/LinkedIn20Example.java

**Comment by mudlee** [comment]
I did not run yet, but I will. However linkedin does not require BEARER auth header, it requires this header specified: oauth_token
Maybe this is why it did not work for me. Actually, we use the LinkedIn's Javascript SDK which authenticates, and gives our back-end a ouath_token. To continue with that oauth_token, LinkedIn's doc says that it have to be provided in the header using "oauth_token"

**Comment by kullfar** [comment]
outdated
