### ISSUE TITLE
UcozApi oauth1.0a get tokent from json response body

### ISSUE THREAD

**Issue by evstropovv** [scribejava/scribejava#790]
Hi
I am trying to integrate [ucoz.api ](http://api.ucoz.net/ru/join/reg/pro) with scribe . 
UcozApi:
```
public class UcozApi extends DefaultApi10a {
    private static final String AUTHORIZE_URL = "http://uapi.ucoz.com/accounts/oauthauthorizetoken=%s";
    protected UcozApi() {
    }
    private static class InstanceHolder {
        private static final UcozApi INSTANCE = new UcozApi();
    }
    public static UcozApi instance() {
        return InstanceHolder.INSTANCE; }
    @Override
    public String getAccessTokenEndpoint(){
        return "http://uapi.ucoz.com/accounts/oauthgetaccesstoken"; }

    @Override
    public String getRequestTokenEndpoint() {
        return "http://uapi.ucoz.com/accounts/oauthgetrequesttoken"; }

    @Override
    public String getAuthorizationUrl(OAuth1RequestToken requestToken) {
        return String.format(AUTHORIZE_URL, requestToken.getToken()); }

    @Override
    public TokenExtractor<OAuth1AccessToken> getAccessTokenExtractor() {
        //   return super.getAccessTokenExtractor();
        return OAuth1AccessJsonTokenExtractor.instance(); }
}
```

```
    OAuth10aService service = new ServiceBuilder("murka1")
             .apiSecret("DqUQJzeCPmwD9CRqbHo6sGBzKCb5U4")
             .debug()
            .build(UcozApi.instance());
    Scanner in = new Scanner(System.in);
    OAuth1RequestToken requestToken = null;
    try {
        requestToken = service.getRequestToken(); //<<---error
    } catch (IOException e) {
        e.printStackTrace();
    } catch (InterruptedException e) {
         e.printStackTrace();
    } catch (ExecutionException e) {
         e.printStackTrace();
    }
    String authUrl = service.getAuthorizationUrl(requestToken);
```
when i start following code, it crash:

> aused by: com.github.scribejava.core.exceptions.OAuthException: Response body is incorrect. Can't extract token and secret from this: '{"oauth_token":"oBt4MDuWJi40ozh41wPcXWIEkC1D4RtSCmBYT20m","oauth_token_secret":"05YnXfwXnn2Cpuje61Uk7L6MC1VTSg6HommZ0LgT","oauth_callback_confirmed":"true"}'
>                                                                                 at com.github.scribejava.core.extractors.AbstractOAuth1TokenExtractor.extract(AbstractOAuth1TokenExtractor.java:42)
>                                                                                 at com.github.scribejava.core.extractors.AbstractOAuth1TokenExtractor.extract(AbstractOAuth1TokenExtractor.java:32)
>                                                                                 at com.github.scribejava.core.extractors.AbstractOAuth1TokenExtractor.extract(AbstractOAuth1TokenExtractor.java:19)
>                                                                                 at com.github.scribejava.core.oauth.OAuth10aService.getRequestToken(OAuth10aService.java:49)
>                                                                                 at com.vasyaevstropov.oauthtest.MainActivity$1$1.doInBackground(MainActivity.java:39)
>                                                                                 at com.vasyaevstropov.oauthtest.MainActivity$1$1.doInBackground(MainActivity.java:29)
> 

can anyone help me ?

**Comment by kullfar** [comment]
Hi,
There is no OAuth1AccessJsonTokenExtractor in ScribeJava and you use it.
looking at the stacktrace you need this OAuth1AccessJsonTokenExtractor. Did you write it yourself? Show it. Seems, you have a bug in it.
After all, Pull Request with OAuth1AccessJsonTokenExtractor will be welcome ;-)

**Comment by evstropovv** [comment]
Yes, that was bug in it. Now all works good. Added an example and ucoz api to pull request. 
For test:
apiKey = murka1
apiSecret = DqUQJzeCPmwD9CRqbHo6sGBzKCb5U4
email = uak63223@sjuaq.com
pass = qwerty
#791 

Many thanks for library ;)

**Comment by kullfar** [comment]
PullRequest was reviewed and merged to the master.
