### ISSUE TITLE
reusable accssToken on web application

### ISSUE THREAD

**Issue by jfabrix101** [scribejava/scribejava#792]
Hi,
In a web application i can use this code

        final OAuth10aService service = new ServiceBuilder(FlickrConst.API_KEY)
                .apiSecret(FlickrConst.API_SECRET)
                .callback("http://localhost:8080/myServlet")
                .build(FlickrApi.instance(FlickrApi.FlickrPerm.DELETE));
		
        final OAuth1RequestToken requestToken = service.getRequestToken();
        final String authorizationUrl = service.getAuthorizationUrl(requestToken);

to obtain an URL where after authentication flicker redirct the user browser to my server.

In my servlet a retrive the "oauth_token" and "oauth_verifier" parameters.
Now i need to call the backend to have the accessToken but i am unable to create a valid requestToken server side.

I read the [akoskm](http://akoskm.com/2015/07/31/twitter-sign-in-for-web-apps.html) tutorial but it referres to an old version. Now it's not possible to create a Token because Token in abstract class.

What i would like to do is to obtain a valid accessToken to save on database and resuse it when necessary without ask authorization each time.

How I can do it ?
Thanks

**Comment by kullfar** [comment]
Hi,
you have two variants.
persist strings in your DB or use implementations of abstract Token - OAuth1AccessToken or OAuth1RequestToken.

Regards,
Stas

**Comment by jfabrix101** [comment]
Solved !

During the first request (where I use the accessRequest) I save the accessToken , tokenSecret and tokenRawResponse.

`OAuth1RequestToken requestToken = new OAuth1RequestToken(p.getProperty("requestToken"), 
					p.getProperty("requestTokenSecret"), p.getProperty("requestRawResponse"));
			System.out.println("Created first request Token");
			
			final OAuth1AccessToken accessToken = service.getAccessToken(requestToken, p.getProperty("oauth_verifier"));
			System.out.println("Created accessToken - " + accessToken.getRawResponse());
			
			p.setProperty("accessToken", accessToken.getToken());
			p.setProperty("accessTokenSecret", accessToken.getTokenSecret());
			p.setProperty("accessTokenRawResponse", accessToken.getRawResponse());
			p.setProperty("user_nsid", accessToken.getParameter("user_nsid"));`

next when I want to call a service I use

`final OAuth1AccessToken accessToken = new OAuth1AccessToken(accessToken, 
					accessTokenSecret,  accessTokenRawResponse);`

and now works.
