### ISSUE TITLE
client_credentials grant type

### ISSUE THREAD

**Issue by vivin** [scribejava/scribejava#793]
I'm trying to authenticate against an internal service at work using the `client_credentials` grant-type for machine-to-machine communication (i.e., without a user). I notice that currently, the grant type is [hardcoded](https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/oauth/OAuth20Service.java#L91) to use `authorization_code` (using `OAuthConstants.AUTHORIZATION_CODE`). It appears that the `OAuthConstants` enum doesn't have a `CLIENT_CREDENTIALS` constant either. 

I can get around this for the time-being by overriding `createAccessTokenRequest`, but I think it would be nice if this was either ~~a configurable option~~ something that was returned from the API class (like signature-method), or if there were methods to handle this particular case similar to the ones that currently exist for the password-grant case.

I think having `DefaultApi20` expose a method that returns the grant type might be nicer because then `getAccessToken` can delegate to the appropriate method based on this value. I think it makes for a cleaner interface. I can make a PR if that's ok.

**edit**: Just realized that it would be hard to make this generic, because the signatures end up being completely different. :) I'll just expose a method similar to how it is currently being done for the password grant.

**Comment by vivin** [comment]
PR #794

**Comment by kullfar** [comment]
fixed. in the master
