### ISSUE TITLE
RFC 7009 - OAuth2 Token Revocation support

### ISSUE THREAD

**Issue by vivin** [scribejava/scribejava#795]
Have you thought about including support for [token revocation](https://tools.ietf.org/html/rfc7009)? If I get some more time I can make PR for this if that's ok.

**Comment by authorjapps** [comment]
Hi, Will this **sign out** the user from the provider session e.g. provider Google or LinkedIn etc ?

**Comment by vivin** [comment]
@authorjapps It will revoke the token, which means that the user will need to reauthorize. But it shouldn't affect any unrelated sessions.

**Comment by kullfar** [comment]
Sorry, for the delay, was on vacation, I will try to return to this issue i next couple of week

**Comment by vivin** [comment]
@kullfar oh, my apologies! Didn't realize you were on vacation -- hope you had fun! :)

**Comment by authorjapps** [comment]
Thanks Vivin, when you finish implementing this, kindly share a link how to use the api. Appreciate an example if you could provide. Regards

**Comment by kullfar** [comment]
RFC 7009 is in the master
https://github.com/scribejava/scribejava/commit/f3cd5193346b60503c2103bf776d384be2dcfa43
example is here
https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples/Google20RevokeExample.java
