### ISSUE TITLE
Potential tokenSecret leak

### ISSUE THREAD

**Issue by rcaa** [scribejava/scribejava#796]
Accidentally, I called OAuth1AccessToken.toString() somewhere in my code. It printed OAuth1Token.tokenSecret. Depending on where I print, this token might leak. 

Should I submit a pull request fixing this issue?

**Comment by kullfar** [comment]
closed for mistake

**Comment by kullfar** [comment]
Sorry, for the delay, was on vacation, I will try to return to this issue i next couple of week

**Comment by kullfar** [comment]
You're right. toString shouldn't throw such security-sensible data outside.
Furthermore, there is not sense in toString without this data, So I've just dropped this methods at all.
Fix is in the master https://github.com/scribejava/scribejava/commit/73c29f539804fbed6e7e2587a87f97898439eeca
