### ISSUE TITLE
Cannot get authorization code from authorization URL in GeniusExample.java

### ISSUE THREAD

**Issue by palatano** [scribejava/scribejava#797]
I've run the sample program, GeniusExample.java, with the clientId and the clientSecret on genius.com/api-clients. In addition, on the genius api page, I have set the redirection URL to:

"com.scribejavatest://callback"

with respect to the callback() method when creating the ServiceBuilder. As I run it, I successfully create an authorization link to choose; however, when I get to the page and click on Authorize, nothing happens. I looked at the console and noticed that I get these errors:

![image](https://user-images.githubusercontent.com/15245089/31027153-305765cc-a517-11e7-85a9-0cc3a404d55b.png)

How can I get past this issue?

**Comment by kullfar** [comment]
Hi,
I have no ideas. Is Genius.com is working ok?
I think about two reasons:
-GeniusApi is out-dated
-some problems on genius.com

**Comment by kullfar** [comment]
outdated
