### ISSUE TITLE
How we can run this code for the Facebook ?

### ISSUE THREAD

**Issue by JavaHelper** [scribejava/scribejava#799]
I have no idea how and where to get the 

And paste the authorization code here
>>

And paste the state from server here. We have set 'secretState'='secret928256'.
>>

**Comment by kullfar** [comment]
I need more details, I didn't understand your problem, sorry

**Comment by ruhman** [comment]
When running the facebook example, it gets the authorization url but then it asks you to access it "And paste the authorization code here". However, where can we find such a code?

**Comment by kullfar** [comment]
In browser url

**Comment by SoltauFintel** [comment]
If you have problems with the state, just remove it from the first call. (But it makes it open to attacks. Not recommended for production szenarios.)

**Comment by kullfar** [comment]
outdated
