### ISSUE TITLE
Google Login

### ISSUE THREAD

**Issue by SoltauFintel** [scribejava/scribejava#800]
Does the Google login work? When I use scribejava 4.2 I get this error: http status 400 { "error": "unsupported_grant_type", "error_description": "Invalid grant_type: " } 

When I use the example of http://o7planning.org/en/10339/using-scribe-oauth-java-api-with-google-oauth-2-tutorial#a351107 (old version 1.3.7!) it works quite good.

I'm not sure about this code piece:
			OAuthRequest request = new OAuthRequest(
					GoogleApi20.instance().getAccessTokenVerb(),
					GoogleApi20.instance().getAccessTokenEndpoint());

**Comment by kullfar** [comment]
Hi,
Google login should work.
Did you run this example
https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples/Google20Example.java
?

**Comment by SoltauFintel** [comment]
1) I already use the Facebook login with scribe 4.0 in production. That works. Some users don't want to use Facebook, so I want to use Google(=Android) alternatively.

2) I remembered that there were examples somewhere, but I didn't find the examples. Maybe you could highlight the examples link in the readme. Now it's the last entry of all login types.

3) So I tried to develop the Google login with everything I knew and found on the web.

4) Now I used the _clean_ Google20Example.java and entered only my IDs. There first result was:

403
{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "accessNotConfigured",
    "message": "Project ### is not found and cannot be used for API calls. If it is recently created, enable Google+ API by visiting https://console.developers.google.com/apis/api/plus.googleapis.com/overview?project=### then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
    "extendedHelp": "https://console.developers.google.com/apis/api/plus.googleapis.com/overview?project=###"
...

That's a better error message. More helpful. Then I activated the Google+ API with the given link. After that I got my login data = **it works**. :-)

I'm not sure what profile to use. I want that every Android (or e.g. YouTube) user can use the Google login. The user should not use Google+. (Maybe it's the same. I have to explore this further. Tips are welcome. It's a bit strange that the 1.3.7-example worked without activating the Google+ API.) Thank you.

**Comment by kullfar** [comment]
> It's a bit strange that the 1.3.7-example worked without activating the Google+ API.

sounds strange to me too. Maybe it was prev. google API version. 1.0...

ok, I can close the issue?

**Comment by SoltauFintel** [comment]
(No)
Can you give me please a tip what scope to use?
At this moment I use scope = "email" with activated "Google+ API". Can every user use that (without doing something on Google+)? My target is that every Android | Chrome | YouTube user can logon to my web app.

**Comment by kullfar** [comment]
Sorry, no info regarding this. It's out-of-scope for ScribeJava

**Comment by kullfar** [comment]
any other questions?
