### ISSUE TITLE
Azure Active Directory OAuth API and Service

### ISSUE THREAD

**Issue by kaushalmall** [scribejava/scribejava#802]
I had to create an Api and Service implementations for Azure Active Directory. Wondering if I should submit a PR for it and what the process was? 

Just create a fork and submit a PR? 

Thanks.

**Comment by kullfar** [comment]
Hi,
right. If you want to add you API to ScribeJava you have to create fork and then submit a PR. There should be the XXXExample.java class as well.
Next, you will need to provide me user and test application credentials to run this example.
(c) https://github.com/scribejava/scribejava/wiki/FAQ#when-will-you-support-insert_api_here-

Regards,
Stas

**Comment by kaushalmall** [comment]
Thanks @kullfar. Sorry for the inactivity on this. I'll try to submit this week. Its my first PR, so please bear with me to get it right after a couple of tries :-)

**Comment by kullfar** [comment]
Closing this issue. Activity will be in Pull Request https://github.com/scribejava/scribejava/pull/806
