### ISSUE TITLE
OAuth token request (possible contribution)

### ISSUE THREAD

**Issue by arranzropablo** [scribejava/scribejava#803]
Hello, I've been using your library to make requests to LinkedIn API and I've noticed that it would be useful to have a method which checks if there is a valid token already to use or, in case that there is not, ask for a new one and return that one.

Would you like me to request a pull which does something similar to that? Or there is already that functionality and I haven't found it?

Thanks for your code anyway! It was very useful!

PD: this is my first contribution to github, I'll try my best! 🤓

**Comment by kullfar** [comment]
It's not possible for some flows, where we need user's action in browser.
It can be achieved with refresh token or in case we have login+password ("password" flow) or even "client_credentials" grant_type. But in case we use "authorization_code" it can't be done automatically.

But anyway, maybe I'm wrong or didn't understand you fully, do not hesitate to provide your pull request!
