### ISSUE TITLE
Latest update such as revoke token is not updated to maven central

### ISSUE THREAD

**Issue by skystar7** [scribejava/scribejava#804]
I guess the title say it all...

This update https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples/Google20RevokeExample.java

```
 System.out.println("Revoking token...");
        service.revokeToken(accessToken.getAccessToken());
```

**Comment by kullfar** [comment]
yep. This update wasn't released yet. I'm planning to release new version this week.

**Comment by skystar7** [comment]
Many thanks....

**Comment by kullfar** [comment]
Here we go,
5.0.0 is on the maven central. enjoy ;-)
