### ISSUE TITLE
Java 7 support

### ISSUE THREAD

**Issue by nikolazius** [scribejava/scribejava#807]
Dear team, 
while Java 7 is supported only through enterprise subscription, it's not dead in enterprise solutions. If there are no particular limitations, would be great if the binaries could be compiled against 1.7 target.

Thanks in advance!
Best,
Nick

**Comment by kullfar** [comment]
Hi,
actually, even java 6 still have extended support ;-)
As for java7 compatibility, ScribeJava have some uses of streams. It's not compilable under javac 7 starting from v5.0.0
It's not hard to fix this java8 usages.
As I see OpenJDK still have security fixes for jdk7.
I think, I'll migrate this library to the earliest available jdk = 7 soon.

**Comment by masewo** [comment]
Hi,
I had the same problem under Android Oreo and revoked some of the java 7 commits:
https://github.com/masewo/scribejava/commit/fde05f79946f8cf7de877b180920c7ee08af8c1a
Kind regards!
