### ISSUE TITLE
Yandex oauth  support 

### ISSUE THREAD

**Issue by demon101** [scribejava/scribejava#808]
As I can see, yandex support was dropped few years ago
https://github.com/scribejava/scribejava/blob/b32bd4ea80e6e5c1182960cbcc6a7568e7c632c8/src/main/java/org/scribe/builder/api/YandexApi.java

Why? Is it possible to restore it? 
I mean is there something that prevents the support now? If no, I will try to make a pull request

**Comment by kullfar** [comment]
Hi, I can't find this commit in the master history. It seems it was in branch only.
Can you point to commit with _drop_ing of the support?
Anyway, there is no reason not to restore it.
You can make a pull request adding support for Yandex for sure. You are welcome!

**Comment by kullfar** [comment]
closing issue. Pull Request are welcome
