### ISSUE TITLE
SignatureType is not available anymore in the ServiceBuilder.

### ISSUE THREAD

**Issue by AndradeB91** [scribejava/scribejava#809]
In the section: https://github.com/scribejava/scribejava/wiki/Custom-Apis, you say we can modify the signature by adding ".signatureType(SignatureType.QueryString)" in the ServiceBuilder params but that's not possible.

**Comment by kullfar** [comment]
yep. outdated wiki. it happens

**Comment by AndradeB91** [comment]
How do i do nowadays?

**Comment by kullfar** [comment]
I hope this two search results can help you
https://github.com/scribejava/scribejava/search?utf8=%E2%9C%93&q=SignatureType&type=
https://github.com/scribejava/scribejava/search?utf8=%E2%9C%93&q=OAuth2SignatureType&type=

**Comment by kullfar** [comment]
in short, you need method
getSignatureType
in API class

**Comment by AndradeB91** [comment]
In fact i have to override the signature type. If i just override the getSignatureType it's not going to work.

**Comment by AndradeB91** [comment]
Ah ok, i just override like this:
` @Override
    public OAuth1SignatureType getSignatureType() {
        return OAuth1SignatureType.QueryString;
    }`

**Comment by kullfar** [comment]
right

**Comment by AndradeB91** [comment]
I still get the error: oauth_problem=signature_method_rejected scribejava. You know what it could be?

**Comment by kullfar** [comment]
It seems like you use a wrong signature method.
Check that your signature method is the one, requested by OAuth provider.
Does Breakpoint and debug shows that OAuth1SignatureType.QueryString were used?
Does your code works with older versions of ScribeJava?
Does your OAuth provider still OAuth1.0? not OAuth 2?

Code samples and full output can helps me to understand your problem.

**Comment by AndradeB91** [comment]
I'm trying to use the oauth to authenticate with atlassian products as stated here: https://medium.com/mibexsoftware/how-to-use-oauth-with-atlassian-products-c0f357ae91eb
as i read, atlassian uses oauth1.

**Comment by AndradeB91** [comment]
Here is my api class:

```
public class DocsApi extends DefaultApi10a {
    private static final String AUTHORIZE_URL = "(url here).../authorize?token=%s";

    protected DocsApi() {}

    private static class InstanceHolder {
        private static final DocsApi INSTANCE = new DocsApi();
    }

    public static DocsApi instance() {
        return InstanceHolder.INSTANCE;
    }

    @Override
    public String getAccessTokenEndpoint(){
        return "(url here).../access-token";
    }

    @Override
    public String getRequestTokenEndpoint() {
        return "(url here).../request-token";
    }

    @Override
    public String getAuthorizationUrl(OAuth1RequestToken requestToken) {
        return String.format(AUTHORIZE_URL, requestToken.getToken());
    }

    @Override
    public OAuth1SignatureType getSignatureType() {
        return OAuth1SignatureType.QueryString;
    }
}
```

**Comment by AndradeB91** [comment]
And i call it like this:

`final OAuth10aService service = new ServiceBuilder("key_string_here")
                                        .apiSecret("secret_string_here")
                                        .build(DocsApi.instance());`

**Comment by AndradeB91** [comment]
I marked a debugger in the getSignatureType method, and it's been called.

**Comment by kullfar** [comment]
Did it work with earlier versions of ScribeJava?
Trouble can be not in type of signature, but in an other part.
for example

https://community.atlassian.com/t5/Answers-Developer-Questions/oauth-problem-signature-method-rejected/qaq-p/557534
"I ended rewriting the groovy script to use RSA-SHA1 keys as HMAC-SHA1 doesn't seem to be supported"
