### ISSUE TITLE
NetIQ Access Manager - Oauth 2 - Response body is incorrect.

### ISSUE THREAD

**Issue by drcimux** [scribejava/scribejava#810]
I have a problem with oauth2 using NetIQ Access Manager.
After that, i receive the form where I put user and password I got the error.
My request is sent to this URL: tokenUrl = "https://mytestlogin.XXXXX.com/nidp/oauth/nam/token"
My request is contains this parameter: 
![image](https://user-images.githubusercontent.com/32959022/34109856-29dcbe0e-e405-11e7-89d0-87257d81f4e6.png)

But server reply with this resp.

![image](https://user-images.githubusercontent.com/32959022/34109907-550d50a2-e405-11e7-9c23-da7b78e2c5b6.png)

I analyze the req/resp with Fiddler:
![image](https://user-images.githubusercontent.com/32959022/34109932-724b8260-e405-11e7-9ac6-c6a4ae33c82d.png)
The error that i can see in tomcat is this:
![image](https://user-images.githubusercontent.com/32959022/34109958-8115bf36-e405-11e7-9719-a7d9f62ff872.png)

Can be the length of code that I sent that is big? It's possible that this can create a problem? It's possible to reduce the length of "code" in configuration inside NetIQ Access Manager 4.4, because the size is around 2k

**Comment by kullfar** [comment]
I think you have to ask XXXXX.com about this error.
It looks more like their part then ScribeJava.

Anyway try to open this broken (Error 400) url in browser. And try to fix it. May be url is incorrect, or as you said length is too big

**Comment by rsangeetha** [comment]
May be your request url is incorrect check your redirect_uri is it same that was registered. I would go Postman to find out the issue because the size is huge and try to send the payload as POST data not as an url query string.
