### ISSUE TITLE
LinkedIn access token requests fail.

### ISSUE THREAD

**Issue by jhorowitz-firedrum** [scribejava/scribejava#811]
Unfortunately, LinkedIn is not following the client authentication spec, and only supports client_id and client_secret in the request body.

Commit 82f38333b9fd53291f32f29638ee473c578f9900 broke this by not specifying 
```
@Override
public ClientAuthenticationType getClientAuthenticationType() {
	return ClientAuthenticationType.REQUEST_BODY;
}
```
in LinkedInApi20.java.

**Comment by kullfar** [comment]
Hi,
thanks pointing to this fact, I'll recheck and fix it if needed next year ;-)
I mean in couple of weeks.

**Comment by kullfar** [comment]
fix in the master
https://github.com/scribejava/scribejava/commit/dd5b08858466ce112a4aedf388db188c3a9d9492
thanks again
