### ISSUE TITLE
Can I authenticate to read MS Excel data stored on OneDrive using scribe from a simple java app?

### ISSUE THREAD

**Issue by hemano** [scribejava/scribejava#812]
I'm having a simple java maven project and want to read the excels stored/ shared on OneDrive.

I'm following the below article, however, it restricts me to have a web app for the auth.
https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/excel.md

**Comment by kullfar** [comment]
I have no idea how can I help you. Is it ScribeJava related question?
