### ISSUE TITLE
Change ServiceBuilder's default callback URL to null

### ISSUE THREAD

**Issue by massongit** [scribejava/scribejava#815]
`com.github.scribejava.core.builder.ServiceBuilder`'s default callback URL is `oob` now.
But in some API (e.g. GitHub API), it is useful to change the default callback URL to `null`.

**Comment by kullfar** [comment]
As I see default callback was 'oob' from the very beginning, from the first commit (6 Sep 2010)
I'm using GitHub API in production and I don't need 'null'.
But anyway, callback (redirect_uri) is optional in OAuth2, I have pushed the commit with the fix. https://github.com/scribejava/scribejava/commit/7b8aab5eaba99495518b69f36924e216fe1a037f

Thanks
