### ISSUE TITLE
How to generate an authorization header from consumer key and secret?

### ISSUE THREAD

**Issue by cliren** [scribejava/scribejava#820]
I have an oAuth 1.0 endpoint (https://localhost:3000/api/sign_in) which expects a "Authorization" header with signed request signature from oAuth consumer key and secret (available to the client). Is there a way scribejave library be used to generate a signature and work with an Android http client (volley)?

**Comment by kullfar** [comment]
Authorization header in OAuth1.0 will be automatically added in the guts of OAuth10aService.java while signing the oauth request

here
https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/oauth/OAuth10aService.java#L88

method appendSignature can be interested to you as well.

If you need just this header, you can try to get only this part from the whole OAuth10aService.java.

As for volley - I have no data about this. But ScribeJava has OKHttp native support from the box

**Comment by cliren** [comment]
Thanks, it helped!
