### ISSUE TITLE
LinkedInAPI20 reporting missing client_id

### ISSUE THREAD

**Issue by jardineworks** [scribejava/scribejava#822]
Hi --

I'm dropping a note here in case anyone else is having this issue. I have pulled scribe into my project and am using the LinkedInApi20 service. I build the service in more than one place so I have put the code to build the service into it's own method --

`return new ServiceBuilder(clientId).apiSecret(clientSecret).scope("r_fullprofile r_emailaddress").callback(redirectURL).build(LinkedInApi20.instance());`

In the first class where I use this to get the code from linked in, there is no issue. Once I get the code, I am now in a new Java class so I use the same method to rebuild the service and then use this line to request the token --

`OAuth2AccessToken token = service.getAccessToken(code);`

I inspected the service before making this call and I can see the api key and secret are part of the definition (which I expect of course). For some reason though, I keep getting this as a response from LinkedIn --

`{"error":"invalid_request","error_description":"A required parameter \"client_id\" is missing"}
`

I dug into the scribe code a bit and found that sure enough, the request that was being sent includes the code (from the initial request), the scope and the redirect uri, but the client_id is not being added as a parameter.

Is anyone else having this issue? Is it a known issue? -- or is there something obvious that I am not doing correct? (I have used this same model for several other oauth service providers and have had no issues with any of them)

Thanks in advance.

**Comment by kullfar** [comment]
Hi,
what is the version of ScribeJava are you using?
Looks like this issue https://github.com/scribejava/scribejava/issues/811
it was fixed already in 5.1.0

**Comment by jardineworks** [comment]
Ah -- I am on 5.0.0. I'll upgrade to see if that fixes the issue and let you know.

**Comment by jardineworks** [comment]
Yep, moving to 5.1.0 fixed it. A colossal waste of 3 hours of my life, but problem solved now. Thanks for the help!
