### ISSUE TITLE
Using Linkedin Mobile access token in scribejava

### ISSUE THREAD

**Issue by stylphub** [scribejava/scribejava#829]
Hello,

I just wanted to ask if you could use the access token obtained in the Linkedin Mobile SDK with scribejava, because I tried to use it and got this error message:

com.github.scribejava.core.model.OAuth2AccessTokenErrorResponse:
{
    "error": "invalid_request",
    "error_description": "Unable to retrieve access token: appid/redirect uri/code verifier does not match authorization code. Or authorization code expired. Or external member binding exists"
}

I'm using OAuth20Service in scribe with the token. I know I can do it with http requests in Android to get the token, but I wanted to keep it simple using the provided SDK.

So I don't know if this is because it is not possible or I'm doing something wrong here.

**Comment by kullfar** [comment]
OAuth2AccessTokenErrorResponse is response for access token retrieving request.
You said you have access token already, you do not need to ask for it again

**Comment by stylphub** [comment]
Oh, you are right! Thanks for that, but it still gives me an error when I use the access token to sign the request.

I'm trying to sign it with the access token has a string (just the value), I necessarily have to do it has an object of type OAuth2AccessToken?

Thanks for the help so far :)

**Comment by kullfar** [comment]
Sorry, I can't understand your problem and needs.
You can sign providing just String
 public void signRequest(String accessToken, OAuthRequest request) {
https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/oauth/OAuth20Service.java#L251

And I need code sample to understand when you have "Unable to verify access token" error.

**Comment by stylphub** [comment]
Hi,

Sorry for been so cryptic, I'm going to try to explain it better now.

I have an Android application that uses the LinkedIn SDK to obtain the value of the access token, that looks like this:

AQXkUpMUB5wX3pesLMrjbOlGM0dVcNUmQEmElKGGS4R0KM9LNeFkihPBZz-rCxwhpq-rmLOIf80......2wZkkW4oG96vEr4iKCWa0k1SyY371hWRSoLOA8vQd-mAszU3VN21lP2srRj34O2vTnbGhZKHgw

I send this access token to a webservice that uses scribejava to get the information from LinkedIn and then process it, for that I initialize the service like this:

 OAuth20Service service = new ServiceBuilder(client_id)
                    .apiSecret(client_secret)
                    .callback(callback_url)
                    .scope("r_basicprofile r_emailaddress")
                    .build(LinkedInApi20.instance());

Where the client_id and client_secret are obtained from the developer page of LinkedIn and the callback_url is test url.

Then I try to get the info using this:

 final OAuthRequest request = new OAuthRequest(Verb.GET, String.format(PROTECTED_RESOURCE_URL));
            request.addHeader("x-li-format", "json");
            request.addHeader("Accept-Language", "ru-RU");
            service.signRequest(token, request);
            Response response = service.execute(request);
            System.out.println("Response Code:" + response.getCode());

Where the protected_resource_url is the linkedIn Api web page and token is the access token received from the Android application. This part returns me an Unable to verify access token.

So the question is if it's possible to do this with the token provided from de Android SDK and I'm missing something or if it's impossible to do.

Thanks for the patience and for the help c:

**Comment by kullfar** [comment]
Hi, I do not see anything that will not work from the ScribeJava side in your scenario. May be LinkedIn has some restrictions.

**Comment by stylphub** [comment]
Just found this hiden in a documentation:

Mobile vs. server-side access tokens

It is important to note that access tokens that are acquired via the Mobile SDK are only useable with the Mobile SDK, and cannot be used to make server-side REST API calls.

Similarly, access tokens that you already have stored from your users that authenticated using a server-side REST API call will not work with the Mobile SDK.

So it's not possible to make cross token authentications.

Sorry for the trouble :c
