### ISSUE TITLE
Yahoo Fantasy Sports API not working

### ISSUE THREAD

**Issue by vic2r** [scribejava/scribejava#830]
Yahoo FS API has stopped supporting OAUTH 1.0 and is recommending everyone to switch to OAUTH 2.0.  

I have been using the java scribe libs for many years and downloaded the latest and see that YahooApi still subclasses DefaultApi10a

This does not work anymore, yahoo is returning an error:  "500  Internal Server Error".

This thread details the problems we are all having.

https://forums.yahoo.net/t5/Help-with-Fantasy-Baseball/Receiving-500-quot-Internal-Server-Error-quot-from-Yahoo-Fantasy/td-p/341427/page/4

**Comment by kullfar** [comment]
Pull Requests are welcome.
Maybe this one will help you
https://github.com/scribejava/scribejava/pull/828

If you can point to the news from yahoo, that OAuth1.0 isn't supported anymore, I will can to drop this old code from the library. Thx

**Comment by kullfar** [comment]
FYI, Pull Request with Yahoo OAuth 2 was merged to the master

**Comment by vic2r** [comment]
Thanks, that worked for me.  I'm using the code already.  Having the scribe libs wrap the OAuth 2 yahoo was great.

You asked about OAuth 1.0 support in yahoo.  I can't speak for the other yahoo APIs, just Fantasy Sports.  It's possible that OAuth 1.0 works for other APIs.

**Comment by kullfar** [comment]
Ok, so I will left OAuth1.
Can we close this issue, noq questions anymore?
