### ISSUE TITLE
Oauth10a implementation for Nokia Health - Oauth Parameters in AuthorizationUrl

### ISSUE THREAD

**Issue by JanedoeGVA** [scribejava/scribejava#832]
Hi,

I'm trying to implement an Auth10a for Nokia Health API with Scribe but I'm stuck with the Verification URL, the url needs Oauth parameters (oauth_nonce, oauth_signature....) but after i get the requestToken i can't access to them. Maybe someone can help me ? 

I had this in my API class : There is a best way to do that ?

![getauthorisationurl](https://user-images.githubusercontent.com/36301580/36586820-56cd73d8-1883-11e8-89ba-d1f919240185.PNG)

**Comment by JanedoeGVA** [comment]
I had this in my API class :  There is a best way to doo that ?

@Override
	public String getAuthorizationUrl(OAuth1RequestToken requestToken) {
		Properties config = OauthUtils.getClientConfigProps(NokiaApiConstant.PATH_FILE_OAUTH_CONFIG);
		String bString = String.format(NokiaApiConstant.BASE_STRING_AUTH_NOKIA_URL_FORMAT,
				config.getProperty(NokiaApiConstant.NOKIA_CLIENT_ID),
       			getTimestampService().getNonce(),
       			getSignatureService().getSignatureMethod(),
       			getTimestampService().getTimestampInSeconds(),
       			requestToken.getToken(),
       			config.getProperty(NokiaApiConstant.NOKIA_CLIENT_ID)
       			);
       	final String signature = getSignatureService().getSignature(bString, config.getProperty(NokiaApiConstant.NOKIA_CLIENT_SECRET), "");
		return bString+"&oauth_signature="+signature;
	}

**Comment by kullfar** [comment]
You need to implement
```    public String getAuthorizationUrl(OAuth1RequestToken requestToken) ```
in your API class.
And add all this additional params yourself.
According to the specs https://tools.ietf.org/html/rfc5849#section-2.2
these params are additional. only oauth_token is specified in this url.

This method can helps you
```

    protected void addOAuthParams(OAuthRequest request, String tokenSecret) {
        final OAuthConfig config = getConfig();
        request.addOAuthParameter(OAuthConstants.TIMESTAMP, api.getTimestampService().getTimestampInSeconds());
        request.addOAuthParameter(OAuthConstants.NONCE, api.getTimestampService().getNonce());
        request.addOAuthParameter(OAuthConstants.CONSUMER_KEY, config.getApiKey());
        request.addOAuthParameter(OAuthConstants.SIGN_METHOD, api.getSignatureService().getSignatureMethod());
        request.addOAuthParameter(OAuthConstants.VERSION, getVersion());
        final String scope = config.getScope();
        if (scope != null) {
            request.addOAuthParameter(OAuthConstants.SCOPE, scope);
        }
        request.addOAuthParameter(OAuthConstants.SIGNATURE, getSignature(request, tokenSecret));

        config.log("appended additional OAuth parameters: " + request.getOauthParameters());
    }
```
in OAuth10aService.java

May be it make sense to refactor somehow this code, so any user can reuse part of this method in their cases, like yours one.

ps. Pull Requests are welcome
