### ISSUE TITLE
OAuth2 Implementation FitBit API for Android 

### ISSUE THREAD

**Issue by NVwingh84** [scribejava/scribejava#834]
Hi, 

I am working on an application using FitBit API on Android. Have been looking around for a suitable library for the implementation, tried Spring but this turned out to be too complex. After checking the documentation realised that there is no out-of-the-box implementation for FitBit, but Scribe can do the job.

What I want to do is implement the Authorization Grant Flow with an automatic "Refresh Token Flow" and easy to use "Revoke Token Flow". 

Therefore I am looking for three things:
- An overview of all methods with their parameters and ideally some extra info of the Scribe Library 
- An example of a "not out of the box" implementation, using Authorization Grant Flow
- A helping hand if I run into issues further down the road

Is all of this possible with Scribe? 
Can you give me some advice?  

Thank you on beforehand and all the best!

Niels Vanwingh

**Comment by kullfar** [comment]
Hi. Sure.
You can start with https://github.com/scribejava/scribejava/search?q=FitBit&type=Issues&utf8=%E2%9C%93
and https://github.com/scribejava/scribejava/wiki

And any successful Pull Request with new API https://github.com/scribejava/scribejava/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed

**Comment by NVwingh84** [comment]
Hi @kullfar , thank you for your quick response. 
I am going to look at it today, I will let you guys know if I get stuck. 

Take care and have a nice day!

**Comment by NVwingh84** [comment]
Hi guys, I have done a basic implementation of the Library and indeed it is quite clear to handle.. 
So far, I have started an authentication with a Basic GET method to get my activities from 27/02/2018.

I still have a few questions.. 
First of all, FitBit asks to encode your Client ID and Secret with Base64 Encoding. I have checked an example of how this is done, and apparentely the "Base64Encoder" method is depreciated. Any other method you would recommend to use and maybe an example? 

I have implemented the API.class as recommended by you, this seems fine. 
Furthermore, here the implementation of the Service.class for FitBit. 
Everything seems ok, except for the last line "return request". I get an error message from Android Studio. 

    public class FitBit20Service extends OAuth20Service {

    public FitBit20Service(DefaultApi20 api, OAuthConfig config) {
        super(api, config);
    }

    @Override
    protected OAuthRequest createAccessTokenRequest(String code) {
        OAuthConfig config = this.getConfig();
        createAccessTokenRequest(code).addParameter("grant_type","authorization_code");
        createAccessTokenRequest(code).addParameter("client_id", config.getApiKey());
        createAccessTokenRequest(code).addParameter("redirect_uri", config.getCallback());

        createAccessTokenRequest(code).addHeader("Authorization", "Basic" + "encoded String used for now directly") ;

        return request;
    }

Finally, in my Main Activity I have created a new OAuth20Service Instance, got the Access Token and Performed a Basic GET request on the FitBit API. 

First error I get at "new ServiceBuilder()", this asks for an argument, while this is not seen in the examples I have used. 
Second error is at "new OAuthRequest(Verb.GET, ACTIVITY_RESOURCE_URL , service)", apparently these are not the right arguments. How can I change this? 
Last one is at  "response = request.send();", in the Repository I cannot find the right method to actually make the GET request. Which one is the right one? 


    public class MainActivity extends AppCompatActivity {

    private String clientid = "my id";
    private String client_secret = "my secret";
    private String ACTIVITY_RESOURCE_URL ="https://api.fitbit.com/1/user/-/activities/date/2018-02-27.json";

    private OAuth20Service service = new ServiceBuilder()
            .apiKey(clientid)
            .apiSecret(client_secret)
            .scope("activity%20heartrate%20location%20profile%20sleep")
            .callback("https://fibi22CJ69")
            .build(FitBitApi.instance());

    private Scanner in = new Scanner(System.in);


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        OAuth2_Process();
    }

    public void OAuth2_Process(){

        //get the Authorization code
        String authorizationUrl = service.getAuthorizationUrl();
        System.out.println("Authorization Url"+ authorizationUrl);
        String code = in.nextLine();
        System.out.println();

        //trade code for access token
        try {
            OAuth2AccessToken accessToken = service.getAccessToken(code);
        } catch (IOException e) {
            e.printStackTrace();
        } catch (InterruptedException e) {
            e.printStackTrace();
        } catch (ExecutionException e) {
            e.printStackTrace();
        }

 

        //ask for protected resource
        OAuthRequest request = new OAuthRequest(Verb.GET, ACTIVITY_RESOURCE_URL , service);
        request.addHeader("x-li-format", "json");
        request.addHeader("Authorization", "Bearer " + accessToken);
        final Response response = request.send();

        //print the response
        System.out.println();
        System.out.println(response.getCode());
        System.out.println();
        System.out.println(response.getBody());
    }
}


THANK YOU VERY MUCH!!!!!

**Comment by kullfar** [comment]
> the "Base64Encoder" method is depreciated. Any other method you would recommend to use and maybe an example?
Point please exactly to the method you're talking about.


> Everything seems ok, except for the last line "return request". I get an error message from Android Studio.

there is no variable named  'request' in your code to return it.
And you have created 4 instances of it while invoking createAccessTokenRequest method 4 times.

As for other questions. Docs sometimes are out-dated, look real examples https://github.com/scribejava/scribejava/tree/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples

**Comment by NVwingh84** [comment]
Method "Base64Encoder" is deprecated.. 
Is used by FitBit to encode Client Secret and ID. 
No I have run this manually, I think they did it automatically through this method. 

I will give it another go and let you know.. 
Thank you for the feedback!

**Comment by kullfar** [comment]
>Method "Base64Encoder" is deprecated..
Is used by FitBit to encode Client Secret and ID.
Now I have run this manually, I think they did it automatically through this method.

unfortunately, I don't know this method, neither ScribeJava does. There is no such method in ScribeJava library: https://github.com/scribejava/scribejava/search?utf8=%E2%9C%93&q=Base64Encoder&type=

**Comment by NVwingh84** [comment]
I have used this from another example, apparently not a good one.. I am looking through a few of the examples you pointed me too, some errors already fixed, I will continue and let you know how it works out.. Great library man and thanks for the feedback!

**Comment by NVwingh84** [comment]
Hi, now I have an issue with my dependencies. Android Studio is not recognising a few methods I have implemented.. 

In the code underneath are not recognised:
- AbstractRequest
- .addParameter
- .addHeader 

I have added the following dependency to my "app Gradle file". 
    compile 'com.github.scribejava:scribejava-apis:5.0.0'

Am I missing something? 

    class FitBit20Service extends OAuth20Service {

    public FitBit20Service (DefaultApi20 api, OAuthConfig config){
        super(api, config);
    }

    /**
     * ref: https://dev.fitbit.com/docs/oauth2/#access-token-request
     * @param code
     * @param request
     * @param <T>
     * @return
     */

    //deze attributen moeten overeenkomen met de elementen die je hebt gedefinieerd bij het creeren van de "instance" in Main
    //hier worden dan configuraties geplaatst voor de calls die in main gebeuren, met parameters en headers

    @Override
    protected <T extends AbstractRequest> T createAccessTokenRequest(String code, T request) {
        OAuthConfig config = this.getConfig();
        request.addParameter("client_id", config.getApiKey());
        request.addParameter("client_secret", config.getApiSecret());
        request.addParameter("code", code);
        request.addParameter("redirect_uri", config.getCallback());
        request.addParameter("scope", config.getScope());
        request.addParameter("grant_type", "authorization_code");
        //this is non-OAuth2 standard, but Fitbit requires it
        request.addHeader("Authorization", "Basic " + "MjJDSjY5OjIwMTI0YTI2N2Y5NjY1ODliNDdkMGQ4MzJiMWFiMjc1=" );
        request.addHeader("Content-Type: application/x-www-form-urlencoded");
        return request;
    }

**Comment by kullfar** [comment]
Hi,

> Can I help you with something?

You can always help with good Pull Requests.

> I am getting errors in processing "scribejava-core-5.0.0.jar". I am using the Gradle system. Apparently there is something wrong with the file.. Can you advise me what to do?

Why not to try the latest version v5.2.0-java7again?

**Comment by NVwingh84** [comment]
Hi kullfar, 

I have never made any Pull Request.. If I succeed in implementing FitBit OAuth2, I will add it as a Pull Request.. Might need some help but I will do my best. 

I have used the latest version, v5.2.0-java7again, and the application initiates. Now I get the error "java.util.NoSuchElementException" when trying to read the code through "String code = in.nextLine".. 

According to my Log, this is what I send to the FitBit Server:
    
System.out: https://www.fitbit.com/oauth2/authorize?response_type=code&client_id=22CJ69&scope=activity%2520heartrate%2520location%2520profile%2520sleep

Can you spot what is wrong with my code - see above code?

**Comment by kullfar** [comment]
I don't see any ScribeJava-related problems here, sorry. It does look like just generic java question.

**Comment by christophsturm** [comment]
you can replace the Base64Encoder call with `Base64.getEncoder().encodeToString(.... `

**Comment by christophsturm** [comment]
here's a fitbit class that works with scribe 4.x : https://github.com/alexthered/fitbitAPI20-scribe-java/blob/master/src/main/java/Fitbit20ServiceImpl.java

to use it with latest scribe just replace the 2 `Base64Encoder` calls with `Base64.getEncoder().encodeToString(....`

**Comment by NVwingh84** [comment]
Hi christophsturm, 

Thank you for your reply.. 

I have tried implementing it that way. 

My sketch is missing a library dependency, namely:
**import com.github.scribejava.core.model.AbstractRequest;**
The IDE cannot find the dependency.. 

I use Gradle and have added the following dependency:
 **compile 'com.github.scribejava:scribejava-apis:5.2.0-java7again**

What am I missing?

**Comment by christophsturm** [comment]
ah I see. the problem is that the source that i linked to uses scribe 3.x 

I ported it to scribe 4.x and later 5.x and i could give it to you but my version is in kotlin. 

maybe it helps you convert the old java source to the latest api. here it is:
```
import com.github.scribejava.core.builder.api.DefaultApi20
import com.github.scribejava.core.model.OAuthConfig
import com.github.scribejava.core.model.OAuthRequest
import com.github.scribejava.core.oauth.OAuth20Service
import java.nio.charset.Charset
import java.util.*


/**
 * Fitbit's OAuth2 client's implementation
 * source: https://dev.fitbit.com/docs/oauth2/
 */
class FitbitApi20 : DefaultApi20() {
    override fun getAccessTokenEndpoint(): String = "https://api.fitbit.com/oauth2/token"

    override fun getAuthorizationBaseUrl(): String = "https://www.fitbit.com/oauth2/authorize"

    override fun createService(config: OAuthConfig): OAuth20Service = Fitbit20ServiceImpl(this, config)
}


class Fitbit20ServiceImpl(api: DefaultApi20, config: OAuthConfig) : OAuth20Service(api, config) {

    override fun createAccessTokenRequest(code: String): OAuthRequest {

        val request = OAuthRequest(api.accessTokenVerb, api.accessTokenEndpoint)

        val config = this.config
        request.addParameter("client_id", config.apiKey)
        request.addParameter("client_secret", config.apiSecret)
        request.addParameter("code", code)
        request.addParameter("redirect_uri", config.callback)
        config.scope?.let {
            request.addParameter("scope", it)
        }

        //this is non-OAuth2 standard, but Fitbit requires it
        request.addHeader(
            "Authorization", "Basic " + Base64.getEncoder().encodeToString(
                String.format(
                    "%s:%s", config.apiKey, config.apiSecret
                ).toByteArray(Charset.forName("UTF-8"))
            )
        )

        request.addParameter("grant_type", "authorization_code")
        return request
    }


    override fun createRefreshTokenRequest(refreshToken: String?): OAuthRequest {
        val request = OAuthRequest(api.accessTokenVerb, api.refreshTokenEndpoint)
        if (refreshToken.isNullOrBlank()) {
            throw IllegalArgumentException("The refreshToken cannot be null or empty")
        }
        val config = this.config
        request.addParameter("client_id", config.apiKey)
        request.addParameter("client_secret", config.apiSecret)
        request.addParameter("refresh_token", refreshToken)
        request.addParameter("grant_type", "refresh_token")

        //this is non-OAuth2 standard, but Fitbit requires it
        request.addHeader(
            "Authorization", "Basic " + Base64.getEncoder().encodeToString(
                String.format(
                    "%s:%s", config.apiKey, config.apiSecret
                ).toByteArray(Charset.forName("UTF-8"))
            )
        )

        return request
    }

}
```

**Comment by NVwingh84** [comment]
Very similar to my code, thank you for sharing though.. 

The problem is in my MainActivity.. 
In my System.out I get the right API Call, I have checked this in my browser and everything is ok. 
I get a "java.util.NoSuchElementException", at the line "String code = in.nextLine();". So I do not receive anything back from the EndPoint. 

Any advice on that? 

    private String clientid = "xxxxx";
    private String client_secret = "xxxxx";

    OAuth2AccessToken accessToken;
    String token;

    private FitBit20Service service = (FitBit20Service) new ServiceBuilder(clientid)
        .apiSecret(client_secret)
        .scope("activity%20heartrate%20location%20profile%20sleep")
        .callback("xxxx")
        .build(FitBitApi.instance());

    private Scanner in = new Scanner(System.in);

    @Override
    protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);
    OAuth2_Process();

    public void OAuth2_Process() throws InterruptedException, ExecutionException, IOException {

    //get the Authorization code
    String authorizationUrl = service.getAuthorizationUrl();
    System.out.println(authorizationUrl);
    String code = in.nextLine();
    System.out.println();

**Comment by kullfar** [comment]
It looks like the problem with using Scanner

**Comment by NVwingh84** [comment]
I have checked again, and I believe the problem lies in my Callback URI. I have specified the URI both at the FitBit EndPoint and in my Activity, but forgot to do so in my Manifest File. 

According to me, the solution will be in correctly filling in the ??? below.. I know it is not a Scribe issue, just wanted to keep you posted.. 

    <?xml version="1.0" encoding="utf-8"?>
    <manifest xmlns:android="http://schemas.android.com/apk/res/android"
      package="com.example.gebruiker.scribetest">

     <uses-permission android:name="android.permission.INTERNET" />

     <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>

            <intent-filter>
                <action android:name="???"/>
                <data android:mimeType="???"/>
                <category android:name="???"/>
            </intent-filter>
        </activity>
      </application>

    </manifest>

**Comment by NVwingh84** [comment]
I have a working Application! So I am ready to write a Pull Request for FitBit.. Will be continued soon, first need to read the documentation.. Thank you for your patience!

**Comment by spike322** [comment]
> 
> 
> ah I see. the problem is that the source that i linked to uses scribe 3.x
> 
> I ported it to scribe 4.x and later 5.x and i could give it to you but my version is in kotlin.
> 
> maybe it helps you convert the old java source to the latest api. here it is:
> 
> ```
> import com.github.scribejava.core.builder.api.DefaultApi20
> import com.github.scribejava.core.model.OAuthConfig
> import com.github.scribejava.core.model.OAuthRequest
> import com.github.scribejava.core.oauth.OAuth20Service
> import java.nio.charset.Charset
> import java.util.*
> 
> 
> /**
>  * Fitbit's OAuth2 client's implementation
>  * source: https://dev.fitbit.com/docs/oauth2/
>  */
> class FitbitApi20 : DefaultApi20() {
>     override fun getAccessTokenEndpoint(): String = "https://api.fitbit.com/oauth2/token"
> 
>     override fun getAuthorizationBaseUrl(): String = "https://www.fitbit.com/oauth2/authorize"
> 
>     override fun createService(config: OAuthConfig): OAuth20Service = Fitbit20ServiceImpl(this, config)
> }
> 
> 
> class Fitbit20ServiceImpl(api: DefaultApi20, config: OAuthConfig) : OAuth20Service(api, config) {
> 
>     override fun createAccessTokenRequest(code: String): OAuthRequest {
> 
>         val request = OAuthRequest(api.accessTokenVerb, api.accessTokenEndpoint)
> 
>         val config = this.config
>         request.addParameter("client_id", config.apiKey)
>         request.addParameter("client_secret", config.apiSecret)
>         request.addParameter("code", code)
>         request.addParameter("redirect_uri", config.callback)
>         config.scope?.let {
>             request.addParameter("scope", it)
>         }
> 
>         //this is non-OAuth2 standard, but Fitbit requires it
>         request.addHeader(
>             "Authorization", "Basic " + Base64.getEncoder().encodeToString(
>                 String.format(
>                     "%s:%s", config.apiKey, config.apiSecret
>                 ).toByteArray(Charset.forName("UTF-8"))
>             )
>         )
> 
>         request.addParameter("grant_type", "authorization_code")
>         return request
>     }
> 
> 
>     override fun createRefreshTokenRequest(refreshToken: String?): OAuthRequest {
>         val request = OAuthRequest(api.accessTokenVerb, api.refreshTokenEndpoint)
>         if (refreshToken.isNullOrBlank()) {
>             throw IllegalArgumentException("The refreshToken cannot be null or empty")
>         }
>         val config = this.config
>         request.addParameter("client_id", config.apiKey)
>         request.addParameter("client_secret", config.apiSecret)
>         request.addParameter("refresh_token", refreshToken)
>         request.addParameter("grant_type", "refresh_token")
> 
>         //this is non-OAuth2 standard, but Fitbit requires it
>         request.addHeader(
>             "Authorization", "Basic " + Base64.getEncoder().encodeToString(
>                 String.format(
>                     "%s:%s", config.apiKey, config.apiSecret
>                 ).toByteArray(Charset.forName("UTF-8"))
>             )
>         )
> 
>         return request
>     }
> 
> }
> ```

How did you add the `com.github.scribejava.core` dependency in your Android project? I'm not able to
