### ISSUE TITLE
Signed JWT for Client Authentication

### ISSUE THREAD

**Issue by CameronDowner** [scribejava/scribejava#836]
Hi,

I was wondering if there is any plans for supporting Signed JWT for Client Authentication and Authorization Grant (See [rfc7523](https://tools.ietf.org/html/rfc7523))?

I've looked through and I cannot see a way to extend the current client authentication methods because they are in enum `ClientAuthenticationType`. Have I missed something here, is there a way to extend the current library to add this?

Any advice would be appreciated :)

Thanks,
Cameron

**Comment by kullfar** [comment]
Hi, I have no such plans and have no info about any activity on adding Signed JWT support.
I see only that https://github.com/scribejava/scribejava/search?utf8=%E2%9C%93&q=jwt&type= in code and issues.
Pull Requests are welcome, you can try to add new enum value in ClientAuthenticationType for that purposes. It looks like the best option ;-)

**Comment by CameronDowner** [comment]
Cheers, thought it might be :)

I'll look into it & see if I can submit a PR

**Comment by kullfar** [comment]
some news here
https://github.com/scribejava/scribejava/pull/983
