### ISSUE TITLE
Add FranceConnectApi to use FranceConnect service

### ISSUE THREAD

**Issue by Taybou** [scribejava/scribejava#838]
Hi,

I'm working on implementing an OAuth connector (module) using **FranceConnect** API. 

The FranceConnect provide two type of endPoints for particular and enterprise and for each one there are URLs for development and production mode:

**Development mode:** 
1. FranceConnect particular endPoints:
Authorize : https://fcp.integ01.dev-franceconnect.fr/api/v1/authorize
Token : https://fcp.integ01.dev-franceconnect.fr/api/v1/token
UserInfo : https://fcp.integ01.dev-franceconnect.fr/api/v1/userinfo
Logout : https://fcp.integ01.dev-franceconnect.fr/api/v1/logout

2. FranceConnect enterprise endPoints:
Authorize : https://fce.integ01.dev-franceconnect.fr/api/v1/authorize
Token : https://fce.integ01.dev-franceconnect.fr/api/v1/token
UserInfo : https://fce.integ01.dev-franceconnect.fr/api/v1/userinfo
Logout : https://fce.integ01.dev-franceconnect.fr/api/v1/logout

**Production mode:**
1. FranceConnect particular endPoints:
Authorize : https://app.franceconnect.gouv.fr/api/v1/authorize
Token : https://app.franceconnect.gouv.fr/api/v1/token
UserInfo : https://app.franceconnect.gouv.fr/api/v1/userinfo
Logout : https://app.franceconnect.gouv.fr/api/v1/logout

2. FranceConnect enterprise endPoints:
Authorize : https://ape.franceconnect.gouv.fr/api/v1/authorize
Token : https://ape.franceconnect.gouv.fr/api/v1/token
UserInfo : https://ape.franceconnect.gouv.fr/api/v1/userinfo
Logout : https://ape.franceconnect.gouv.fr/api/v1/logout

I have a little proposition to extend the scribe APIs (you can find it, in my scribejava [fork](https://github.com/Taybou/scribejava/commit/028eb6690edd81c1f0d799104fbb2fe634406807))

So the question is: how can we solve this issue with the different type of endPoints?

Thanks a million <3

**Comment by kullfar** [comment]
Hi,
I'd recommend something like here https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/main/java/com/github/scribejava/apis/SalesforceApi.java#L60

so your API sources will be like this
```
private final String authorizeUrl;
private final String tokenUrl;
private final String userInfoUrl;
private final String logoutUrl;

    private static class DevParticularInstanceHolder {
        private static final FranceConnectApi INSTANCE = new FranceConnect("https://fcp.integ01.dev-franceconnect.fr/api/v1/authorize", ...);
    }

    private static class DevEnterpriseInstanceHolder {
        private static final FranceConnectApi INSTANCE = new FranceConnect("https://fce.integ01.dev-franceconnect.fr/api/v1/authorize", ...);
    }

....
    public static FranceConnectApi devParticularInstance() {
        return DevParticularInstanceHolder.INSTANCE;
    }

    public static FranceConnectApi devEnterpriseInstance() {
        return DevEnterpriseInstanceHolder.INSTANCE;
    }
...

**Comment by kullfar** [comment]
and the constructor

```
public FranceConnectApi(authorizeUrl, tokenUrl, userInfoUrl, logoutUrl) {
  this.authorizeUrl = authorizeUrl;
  ...
}
```

**Comment by kullfar** [comment]
Is it actual?

**Comment by kullfar** [comment]
outdated
