### ISSUE TITLE
Box Authentication isn't working

### ISSUE THREAD

**Issue by dolukhanov** [scribejava/scribejava#842]
Whilst trying to get the access token with the BoxApi20 integration results in the error:

`box {"error":"invalid_client","error_description":"The client credentials are invalid"}`

The addition of the following method to BoxApi20.java resolves the problem:

`public ClientAuthenticationType getClientAuthenticationType()
    {
        return ClientAuthenticationType.REQUEST_BODY;
    }`

**Comment by kullfar** [comment]
Thanks for finding that.
Could you provide test app credentials and test user credentials for me to run the example to check this fix?

**Comment by kullfar** [comment]
outdated
