### ISSUE TITLE
ScribeJava crash on Android device with not full JDK7 support

### ISSUE THREAD

**Issue by arcao** [scribejava/scribejava#851]
ScribeJava v5.4.0 crash with `NoClassDefFoundError` while preparing Access token on Android device with SDK 18 and lower.

Class `Objects` was added in Android SDK 19 which is first version with full JDK7 support.  

```
java.lang.NoClassDefFoundError: java.util.Objects
        at com.github.scribejava.core.model.OAuth1RequestToken.hashCode(OAuth1RequestToken.java:60)
        at java.lang.Object.toString(Object.java:332)
        at java.lang.StringBuilder.append(StringBuilder.java:202)
        at com.github.scribejava.core.oauth.OAuth10aService.prepareAccessTokenRequest(OAuth10aService.java:144)
        at com.github.scribejava.core.oauth.OAuth10aService.getAccessTokenAsync(OAuth10aService.java:131)
        at 
...
```

**Comment by arcao** [comment]
Problem is in logging content of request token: https://github.com/scribejava/scribejava/blob/23e4ed3083d5f2e6fb1a8deb8716ec6eb78f0419/scribejava-core/src/main/java/com/github/scribejava/core/oauth/OAuth10aService.java#L144
`OAuth1RequestToken` doesn't implements `toString()` method, so the default `toString()` Java implementation call `hashCode()` where you use that `Objects` class.

The best solution will be to remove `requestToken` from logging. It doesn't return its content anyway, only class name and instance reference id. 
Another way would be to implement `toString()` for all model classes.

**Comment by kullfar** [comment]
Oh, I see.
I think I have a third way.
log(..) - is for debugging purposes only. It's not nice to concatenate this message string (including invoking toString() method on params) in case debug logging is off.

**Comment by kullfar** [comment]
merged the fix to the master
