### ISSUE TITLE
Fantastic work! Extending API to work with Go-OAuth2 Server

### ISSUE THREAD

**Issue by icemagno** [scribejava/scribejava#853]
I'm working on extend a custom [2.0 API](https://github.com/scribejava/scribejava/wiki/Custom-Apis) to work with https://github.com/RichardKnop/go-oauth2-server.

I'll tell you when I'm done.

**Comment by kullfar** [comment]
:+1: :smile:

**Comment by kullfar** [comment]
Do we need this issue open?
You can create new Pull Request when you will done
