### ISSUE TITLE
JSON POST body

### ISSUE THREAD

**Issue by Langsdorf** [scribejava/scribejava#854]
How can I send a request with JSON POST body? For Twitter new API: 

https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/api-reference/new-event

I tried to use setPayload(json); but returns null.

_English isn't my first language_

**Comment by kullfar** [comment]
Hi, I haven't yet check this Pull Request
https://github.com/scribejava/scribejava/issues/854
but maybe it can help you
