### ISSUE TITLE
Question regarding method for retrieving Refresh-token from API callback.. 

### ISSUE THREAD

**Issue by NVwingh84** [scribejava/scribejava#856]
Hello, I am using Scribe to authenticate against the FitBit API. 

This are a few Helper methods of the application.. 

     _//creates an instance of OAuth20Service with the parameters to make the call
    private OAuth20Service createService() {
        return new ServiceBuilder(clientid)
                .apiSecret(clientSecret)
                .scope(apiScope) // what data do you want access to
                .callback(apiCallback)  //your callback URL to handle the callback to the app
                .build(FitBitApi20.instance());
    }

    //Creates service if necessary
    private OAuth20Service getService() {
        if (service == null) {
            service = createService();
        }
        return service;
    }

    //You get the Token with the Access Code
    private void requestAccessToken() {
        try {
            OAuth20Service serviceCall = getService();
            OAuth2AccessToken accessToken = serviceCall.getAccessToken(authCode);
            //refresh_token = ????
            accessToken_String = accessToken.toString();
            Log.d("AccessToken", accessToken_String);
        } catch (IOException e) {
            e.printStackTrace();
        } catch (InterruptedException e) {
            e.printStackTrace();
        } catch (ExecutionException e) {
            e.printStackTrace();
        }_

In this mindset, how do I retrieve the refresh token from the API response? 
I have checked the Scribe Library documents and methods, but cannot find an appropriate method.. 
I can then store it to check if there is a valid refresh token and use another process..

**Comment by kullfar** [comment]
you can see example here https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples/Google20Example.java#L76
```
        System.out.println("Refreshing the Access Token...");
        accessToken = service.refreshAccessToken(accessToken.getRefreshToken());
        System.out.println("Refreshed the Access Token!");
        System.out.println("(The raw response looks like this: " + accessToken.getRawResponse() + "')");
```

is it what you need?

**Comment by NVwingh84** [comment]
Yes, awesome, it works.. Thanks!
