### ISSUE TITLE
Question about older releases

### ISSUE THREAD

**Issue by cmrockwell** [scribejava/scribejava#857]
Hello
Could someone knowledgable about this project say whether Scribe v1.3.5 support OAuth2.0?

In my work we develop on Adobe Experience Manager (AEM) which wraps Scribe within one of Adobe's OSGI bundles. The current version of Scribe used in 1.3.5. I have found it working for OAuth 1.0, but I cannot get OAuth 2.0 working with LinkedIn. I suspect that it would be possible if a newer version of scribe were used. I have submitted a ticket to the vendor, as it is integrated within their proprietary Granite framework. In my support ticket, they have asked me to refer to documentation stating whether Scribe v1.3.5 support OAuth2.0. Any thoughts or suggestions would be appreciated.

**Comment by kullfar** [comment]
Anyway, I'd recommend to update to the latest version of ScribeJava anyway

**Comment by kullfar** [comment]
Any more questions?
Or we can close this issue?
