### ISSUE TITLE
Azure v2.0 endpoint

### ISSUE THREAD

**Issue by dgrudenic** [scribejava/scribejava#861]
Is there any plans for out of the box support for Azure v2.0 endpoint: https://apps.dev.microsoft.com?
Awesome work BTW.

**Comment by kullfar** [comment]
I have no info about this.
ScribeJava has only this https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/main/java/com/github/scribejava/apis/MicrosoftAzureActiveDirectoryApi.java
for the moment.
You are free to add this support. Anyone can create new Pull Request here

**Comment by gnumarco** [comment]
Indeed it would be great to get support for the new Microsoft oauth2. I tried to add it by hand, but I find it a bit tricky, maybe someone who knows more the library could have a look?

**Comment by kullfar** [comment]
Does anyone need this issue open?

**Comment by gnumarco** [comment]
If it can help having Scribe support Microsoft v2 endpoint, yes.

**Comment by kullfar** [comment]
No, it won't. Only Pull Request can

**Comment by gnumarco** [comment]
Hi again. I finally got my hands into the code, and in fact the only thing that revents the MicrosoftAzureActiveDirectoryApi.java to work correctly is the following point:

`private static final String MSFT_GRAPH_URL = "https://graph.windows.net";`

The Microsoft Graph URL is outdated, it is now "https://graph.microsoft.com". So the code should be:

`private static final String MSFT_GRAPH_URL = "https://graph.microsoft.com";`

Then it seems that to be able to use the Graph API, both the auth and the token have to specify that they will use the Graph API as ressource, so:

`private static final String TOKEN_URI = "oauth2/token";`

should be:

`private static final String TOKEN_URI = "oauth2/token?resource=" + MSFT_GRAPH_URL;`

I modified the code (actually I copied the code of MicrosoftAzureActiveDirectoryApi.java and made my own Api class) and it works for me using the Graph API.

I can share the code or help to update the lib if someone tells me how to do ;)

**Comment by kullfar** [comment]
Hi, glad to read this.
You can make Pull Request here.
I will need "test app credentials" and "test user credentials" to run the example successfully then

**Comment by gnumarco** [comment]
Hi, sure.
Can you tell me exactly how to correctly done pull request? That would be my first.
Where can I give you the credentials to run the tests?

**Comment by kullfar** [comment]
Hi,
there is nothing special about PullRequests for ScribeJava. As any other on github.
You can look for any successful merged PR here https://github.com/scribejava/scribejava/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Amerged as an example.
You need to provide at least API and Example classes.
You can send credentials to this email https://github.com/scribejava/scribejava/blob/master/pom.xml#L52

**Comment by rzukow** [comment]
@kullfar 
I can make a PR with this, but do you want to upgrade the API to 2.0 or somehow have support for 1.0?

If we change MicrosoftAzureActiveDirectoryApi.java to new MS API there will be no support for old one. Do we want to handle both API or rather use old one as obsolete and handle only new one ?

**Comment by kullfar** [comment]
@rzukow if MS API 1.0 is still working, we definitely should leave its support in ScribeJava.
So, it's better to make Pull Request with new class.
As for naming, imho MicrosoftAzureActiveDirectory20Api is the best

**Comment by rzukow** [comment]
I created PR https://github.com/scribejava/scribejava/pull/872
Waiting for comments and suggestions.

**Comment by kullfar** [comment]
PR looks ok, I'm waiting for credentials to run the example

**Comment by kullfar** [comment]
outdated

**Comment by dgrudenic** [comment]
FYI I tried @rzukow PR against our company account and was working correctly. Thanks @rzukow.

**Comment by kullfar** [comment]
good to hear this. In case you can provide test user and test app credentials, I would run the example and merge it to the master

**Comment by dgrudenic** [comment]
OK will send you private message

**Comment by dgrudenic** [comment]
Sent to gmail.

**Comment by kullfar** [comment]
thanks a lot!
have changed a bit
have adopted to the new master
have tested (thanks to @dgrudenic)
have merged to the master (thanks to @rzukow)
