### ISSUE TITLE
OAuthException not delivered to onError callback

### ISSUE THREAD

**Issue by jochen314** [scribejava/scribejava#862]
I am using the async interface with the ApacheHttpClient
I try to get an access token, but I have an authentication issue.
So I get an error method back from the server.
That error is not handled correctly:

- sendAccessTokenRequest* methods no not check the status code. The conversion is tried, even is the status code is not 200.
- OAuth2AccessToken*Extractor throws a RuntimeException (OAuthException), which is not cought anywhere.  OAuthAsyncCompletionHandler only catches IOException, JDKHttpClient.executeAsync only catches  InterruptedException | ExecutionException | IOException. No RuntimeException

**Comment by kullfar** [comment]
1."sendAccessTokenRequest* methods no not check the status code. The conversion is tried, even is the status code is not 200."

give the example please. OAuth2AccessTokenJsonExtractor for example checks the response code

2."throws a RuntimeException (OAuthException), which is not cought anywhere". Who should catch it and how to process it?

**Comment by jochen314** [comment]
1. Just as an example, please have a look at OAuth2AccessTokenExtractor. Can you please point me to the lines, which check the status code?

2. Using the async interface (with the ApacheHttpClient) the extractor is called in an apache thread. Therefore the expection cannot be caught by the application.
I would suggest, that OAuthAsyncCompletionHandler will catch any Throwable and forwards it to callback.onThrowable() to inform the application.
In case of the JDKHttpClient it is no as bad, as the exception will be thrown on the application thread. But is seems odd to me, that some exceptions are thrown and some are delivered using then onThreadble() callback.
ahc, ning and okhttp suffer from the same problem as apache.

**Comment by kullfar** [comment]
1.Yep, you're right. In this custom implementation, there is no such check for status code. It's only in default https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/extractors/OAuth2AccessTokenJsonExtractor.java#L45
It can be added in case someone will be interesting.

2.sounds strange. There is even unit test on this behavior
```assertNotNull(callback.getThrowable());```
https://github.com/scribejava/scribejava/blob/master/scribejava-httpclient-apache/src/test/java/com/github/scribejava/httpclient/apache/OauthAsyncCompletionHandlerTest.java#L88

**Comment by kullfar** [comment]
2.Ah, caught it. You mean this step
https://github.com/scribejava/scribejava/blob/master/scribejava-httpclient-apache/src/main/java/com/github/scribejava/httpclient/apache/OAuthAsyncCompletionHandler.java#L53
while processing httpResponse

**Comment by thodte** [comment]
Hello @kullfar 
I have the same issue in my project and I'm interested in @jochen314 request. Please have a look there and provide a new version. 

Thanks!
