### ISSUE TITLE
Setting a custom "content-type" header (lowercase) results in duplicate header and invalid request

### ISSUE THREAD

**Issue by marnix** [scribejava/scribejava#865]
The code over at

https://github.com/scribejava/scribejava/blob/f96b6768cd2fcdb1f242e8de62e6737d4d0c4b02/scribejava-httpclient-apache/src/main/java/com/github/scribejava/httpclient/apache/ApacheHttpClient.java#L86-L88

fails if a header `content-type` (all lowercase) is passed: in that case something like

```
Content-Type: application/x-www-form-urlencoded
content-type: application/json
```

is sent by Scribe, which is of course an invalid request, since [HTTP headers are case insensitive](https://stackoverflow.com/a/5259004/223837).

**Comment by kullfar** [comment]
Hi,
thanks for pointing to this.
will be fixed soon.

Thanks,
Stas

**Comment by marnix** [comment]
Thanks in advance!  I thought about providing a patch, but there are multiple possible solutions (e.g., always keep the keys in the `Map` Camel-Case; find all lookups and comparisons and do them case-insensitively; use a [CaseInsensitiveMap](https://commons.apache.org/proper/commons-collections/apidocs/org/apache/commons/collections4/map/CaseInsensitiveMap.html)) and I didn't know which you prefer.

**Comment by kullfar** [comment]
Fix is in the master
