### ISSUE TITLE
OAuthRequest - Twitter count param

### ISSUE THREAD

**Issue by bdil24** [scribejava/scribejava#866]
Hi,
I'm using scribejava to authenticate and hit endpoints for Twitter. A couple of the endpoints take a "count" parameter, such as "https://api.twitter.com/1.1/followers/list.json". If I add this parameter, I get an unauthorized response, but it works without. A google search came back that perhaps the parameters have to be in alphabetical order. Is there a way to do that with an OAuthRequest? To send the "count" param before the oauth parameters and other parameters. Here is a snippet doing the request:

OAuthRequest request = new OAuthRequest(Verb.GET, "https://api.twitter.com/1.1/followers/list.json");
request.addQuerystringParameter("screen_name", "user name");
service.signRequest(token, request);

Subsequent calls add on the "cursor" param to get the next page, but adding "count" there or before the screen name gives unauthorized or is ignored.
request.addQuerystringParameter("count", "100");

If this is beyond the scope of the library or better put on the twitter forum, I can try there.
Thanks!

**Comment by bdil24** [comment]
Thanks, I checked this class, and the order is correct. I'll look into from the twitter angle then.

**Comment by bdil24** [comment]
I didn't resolve this yet, but for SA, I did open a Twitter forum topic on this - https://twittercommunity.com/t/count-parameter-on-list-endpoint-returning-unauthorized/110170/3

**Comment by kullfar** [comment]
I have one idea. Maybe param 'count' should be excluded from request sign generation?
Btw, does the twitter reference/docs/specs have some additional information about this param.

**Comment by bdil24** [comment]
There is nothing special referenced about this param, but here is the API spec for one of the calls -https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-friends-list . Where is the sign generation happening? I could try it out.

**Comment by kullfar** [comment]
I mentioned the method getSortedAndEncodedParams before.
You can try to exclude 'count' param right here and see what will happen

**Comment by kullfar** [comment]
no, it will not be excluded from the request. It will do exactly what you need - exclude from the signature generation. like this

   protected String getSortedAndEncodedParams(OAuthRequest request) {
        final ParameterList params = new ParameterList();
        params.addAll(request.getQueryStringParams());
        params.addAll(request.getBodyParams());
        params.addAll(new ParameterList(request.getOauthParameters()));

**params.remove('count');**

        return params.sort().asOauthBaseString();
    }

this collection 'params' here is used only to sort and generate oAuthBaseString

**Comment by bdil24** [comment]
Ok, that makes sense. I don't get an unauthorized status code back with this change, but it ignores the count parameter.

**Comment by kullfar** [comment]
'it ignores' you mean 'didn't send to twitter'?

**Comment by bdil24** [comment]
Sorry - I meant the count doesn't change (as if twitter ignores it), but I get back a valid response with the default 20 results from twitter with the count removed from the signature.

**Comment by kullfar** [comment]
Hi, dou you have any news?

**Comment by kullfar** [comment]
outdated
