### ISSUE TITLE
com.github.scribejava.core.exceptions.OAuthException: Response body is incorrect

### ISSUE THREAD

**Issue by fgroupindonesia** [scribejava/scribejava#868]
I think i forgot something but i didn't realized where should i clear this out?

I recently followed the tutorial of LinkedIn's API using scribe, from 
This url example: 
1) [LinkedIn](https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples/LinkedInExample.java)

But the output for the first one is:

> com.github.scribejava.core.exceptions.OAuthException: Response body is incorrect. Can't extract token and secret from this: 'oauth_problem=Invalid%20redirect

Is there anyone know how to solved this?

**Comment by kullfar** [comment]
you have error text already
"oauth_problem=Invalid%20redirect"
you need to fix it. refer to LinkedIn docs

**Comment by kullfar** [comment]
Does anybody need this issue open?

**Comment by pradeepjadi** [comment]
Yes

**Comment by kullfar** [comment]
not an issue
