### ISSUE TITLE
Threw an exception when serializing: class org.scribe.exceptions.OAuthException :: Response body is incorrect. Can't extract token and secret from this: 'oauth_problem=Invalid%20redirect'

### ISSUE THREAD

**Issue by pradeepjadi** [scribejava/scribejava#876]
final String  PROTECTED_RESOURCE_URL = "http://api.linkedin.com/v1/people/~/connections:(id,last-name)";   
     	   OAuthService service = new ServiceBuilder()
                   .provider(LinkedInApi.class)
                   .apiKey("#################")
                   .apiSecret("#######################")
                   .build();
     	  try{
                  //In the constructor the AuthHandler goes through the chain of calls to create an Access Token
                  Scanner in = new Scanner(System.in);
                  System.out.println("=== LinkedIn's OAuth Workflow ===");
                  System.out.println();

                  // Obtain the Request Token
                  System.out.println("Fetching the Request Token...");
                  Token requestToken = service.getRequestToken();
                  System.out.println("Got the Request Token!");
                  System.out.println();

                  System.out.println("Now go and authorize Scribe here:");
                  System.out.println(service.getAuthorizationUrl(requestToken));
                  System.out.println("And paste the verifier here");
                  System.out.print(">>");
                  Verifier verifier = new Verifier(in.nextLine());
                  System.out.println();

                  // Trade the Request Token and Verfier for the Access Token
                  System.out.println("Trading the Request Token for an Access Token...");
                  Token accessToken = service.getAccessToken(requestToken, verifier);
                  System.out.println("Got the Access Token!");
                  System.out.println("(if your curious it looks like this: " + accessToken + " )");
                  System.out.println();

                  // Now let's go and ask for a protected resource!
                  System.out.println("Now we're going to access a protected resource...");
                  OAuthRequest request = new OAuthRequest(Verb.GET, PROTECTED_RESOURCE_URL);
                  service.signRequest(accessToken, request);
                  Response response = request.send();
                  System.out.println("Got it! Lets see what we found...");
                  System.out.println();
                  System.out.println(response.getBody());

                  System.out.println();
                  System.out.println("Thats it man! Go and build something awesome with Scribe! :)");

          }catch (Exception e){
              System.out.println("Threw an exception when serializing: " + e.getClass() + " :: " + e.getMessage());
          }

out put is:   === LinkedIn's OAuth Workflow ===

Fetching the Request Token...
Threw an exception when serializing: class org.scribe.exceptions.OAuthException :: Response body is incorrect. Can't extract token and secret from this: 'oauth_problem=Invalid%20redirect'

**Comment by kullfar** [comment]
so?

**Comment by kullfar** [comment]
Do you have any question? How can I help you?
I didn't see any questions or problems in your text, sorry

**Comment by kullfar** [comment]
Does anybody need this issue open?

**Comment by kullfar** [comment]
not an issue
