### ISSUE TITLE
Access to Oauth1.0a Authorization Header

### ISSUE THREAD

**Issue by paolop** [scribejava/scribejava#882]
As per title, I'm using the library to connect to an external service using OAuth1.0a. 
I followed the steps highlighted in the wiki and I'm able to retrieve an access token. Now, I need to retrieve the Authorization header to be able to call some remote requests. By looking at the implementation, all the methods related to the auth. header require an `OAuthRequest` instance that is not directly visible to client code when using the default `OAuth10aService`. Is this correct? 
In my case what is the correct approach to follow? Define a specialization of the service?

**Comment by kullfar** [comment]
Did you use Examples https://github.com/scribejava/scribejava/tree/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples as well?
Are there any answers to you?

**Comment by paolop** [comment]
Thanks @kullfar, found a possible solution by extracting the header from a `Request` instance.
