### ISSUE TITLE
 Google+ API Shutdown

### ISSUE THREAD

**Issue by fvasco** [scribejava/scribejava#885]
> On March 7, 2019, all Google+ APIs will be shut down. This will be a progressive shutdown beginning in late January, with calls to these APIs starting to intermittently fail as early as January 28, 2019.

> The Google+ Sign-in feature has been fully deprecated and will also be shut down on March 7, 2019. Developers should migrate to the more comprehensive Google Sign-in authentication system.

See https://developers.google.com/+/api-shutdown

How to migrate to new API?

**Comment by kullfar** [comment]
Hi,
I don't think it's ScribeJava-related issue.
Anyway, are you sure ScribeJava are using Google+ Sign-in feature? and not just OAuth2 part of Google Sign-in authentication system? It seems, Google are not going to deprecate OAuth2 support on their side.

**Comment by fvasco** [comment]
This example refers to Google Plus

https://github.com/scribejava/scribejava/blob/fac5e70bee6d2bcd7865feb90cef3aeea648b91f/scribejava-apis/src/test/java/com/github/scribejava/apis/examples/Google20Example.java#L19

Update the example should be enough.

**Comment by kullfar** [comment]
Ah, I see. PROTECTED_RESOURCE_URL sould be changed as well
```private static final String PROTECTED_RESOURCE_URL = "https://www.googleapis.com/plus/v1/people/me";```

ok. I will update myself in near future if it will be no PullRequests from someone.

**Comment by kullfar** [comment]
thx

**Comment by fvasco** [comment]
Migrate from Google+ Sign-In

https://developers.google.com/identity/sign-in/web/quick-migration-guide

**Comment by jllado** [comment]
@kullfar I guess the change in the example it's simply change the PROTECTED_RESOURCE_URL to "https://www.googleapis.com/oauth2/v3/userinfo". Is it?

Thanks!

**Comment by kullfar** [comment]
@jllado yep, it does looks like that.
https://www.googleapis.com/oauth2/v3/userinfo
and NETWORK_NAME = "G+ Async";

**Comment by kullfar** [comment]
I have pushed commit to the master. Now Scribejava is free from any Google+ mentios
