### ISSUE TITLE
Does scribe support Open ID connect authorization code flow?

### ISSUE THREAD

**Issue by apraovjr** [scribejava/scribejava#886]

**Comment by kullfar** [comment]
in short - no.
a very bit - you can look for usages here https://github.com/scribejava/scribejava/tree/master/scribejava-apis/src/main/java/com/github/scribejava/apis/openid

**Comment by kullfar** [comment]
there is Pull Request https://github.com/scribejava/scribejava/pull/646
and Open Id connect is in the middle plans. no more info ;-(

**Comment by apraovjr** [comment]
thanks @kullfar !
