### ISSUE TITLE
client credential flow by adding certificates

### ISSUE THREAD

**Issue by apraovjr** [scribejava/scribejava#888]
Hi

It seems there is no support currently for initiating the client credentials flow by using certificates in addition to client secrets? Is there backlog item for it to add it in future?

**Comment by kullfar** [comment]
Hi,

actually I don't know what do you mean. Is it OAuth2 related?
I didn't find anything in specs https://tools.ietf.org/html/rfc6749

Possibly, it's something additional, not directly related to OAuth2 and ScribeJava.
So I have no info about future of this feature yet ;-)
