### ISSUE TITLE
Azure AD v2.0 not work as expected

### ISSUE THREAD

**Issue by kenpusney** [scribejava/scribejava#890]
According to the document, the endpoint for auth and token should be:
```
https://login.microsoftonline.com/{tenant}/oauth2/v2.0/authorize
https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token
```
https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow

Here is a reference implementation:
https://github.com/microsoftgraph/console-java-connect-sample/blob/master/src/main/java/com/microsoft/graphsample/connect/MicrosoftAzureAD20Api.java

**Comment by oscararias** [comment]
I'm struggling with the same problem accessing v2.0

Besides, both scribe and the reference implementation  are ignoring the {tenant} component of the endpoint url.  I cannot see how other tenant apart  from "common" could be specified.

**Comment by kenpusney** [comment]
@oscararias 
It would be possible to create an API factory to support this by parameterize the 'tenant' field.
The reference implementation is just an example shows the correct way to call Azure AD v2.

**Comment by oscararias** [comment]
We came up with a quick solution that works for our use case. You can see our changes here: https://github.com/oscararias/scribejava/commit/95d0bda7aaeb6ce2eca84c425fe6e9d52c6de0c4

In a nutshell, we removed the singleton behaviour in MicrosoftAzureActiveDirectory20Api and we allowed specific tenantIds to be passed through the constructor. 

We also fixed authorizationBaseUrl and accessTokenEndpoint inside BaseMicrosoftAzureActiveDirectoryApi.java according to the format suggested by @kenpusney.

We finally adapted MicrosoftAzureActiveDirectory20Example.java to our changes. It seems to work fine and all automatic tests pass.

We know this is a rather unsophisticated solution, we would like to hear @kullfar opinion on this issue.

**Comment by oscararias** [comment]
I updated the commit due to a dumb mistake Here's the new one https://github.com/oscararias/scribejava/commit/941ec8b05df34e32dd3a8bf062dc6395630b8765

**Comment by kullfar** [comment]
Ooook.. Thanks to all participants!
Here is my summary https://github.com/scribejava/scribejava/commit/ea8e48d610b958759fb3f1866678a13d9e9745a0
It's in the master, you can test it.

changes are:
1.tenant - user should have possibility to specify any, "common" is the default value for v1 and v2
2.resource - v1 only, recommended, not required, can be specified by user, no defaults
3.We do not need special class for version, two API classes are enough
4.add "v2.0" to the urls for v2

**Comment by oscararias** [comment]
Thanks for your effort. I've just dropped you a few comments, hope they're useful.

**Comment by kullfar** [comment]
@oscararias Thx a lot! You're right with your comment. I'm coding in blind manner, I don't have app and user to test the code.

**Comment by kullfar** [comment]
Fix in the master https://github.com/scribejava/scribejava/commit/1f024918d17e02331dc5a94ca5925a398834629d

**Comment by oscararias** [comment]
@kullfar thx for the fix. We've tried your solution in our app and works perfectly, looking forward to the next release 😄 

For the sake of completion we also executed MicrosoftAzureActiveDirectory20Example and we found a small pitfall. Apparently MS requires a new scope in order to access the user profile. Here:

https://github.com/scribejava/scribejava/blob/e2ecdac1b68940513b2004209ee453256fde1279/scribejava-apis/src/test/java/com/github/scribejava/apis/examples/MicrosoftAzureActiveDirectory20Example.java#L28

you should add "User.Read" as a second scope, something like this `.scope("openid User.Read")`

**Comment by kullfar** [comment]
Ok, thx. I've added this as well https://github.com/scribejava/scribejava/commit/872af9aa4919900a94cf6e33774f2e081f15f89f

As for release, I will do that tomorrow in case of no troubles

**Comment by oscararias** [comment]
Awesome! Big thx! 👍

**Comment by kullfar** [comment]
release 6.3.0 is on the maven central already
