### ISSUE TITLE
keycloak user/password not working

### ISSUE THREAD

**Issue by zenwork** [scribejava/scribejava#891]
Hi,

I am having a problem with user/password auth with keycloak 4.8.x. Client credential auth works fine. But I need both. First of all thanks for the existance of this lib. It is so much simpler then everything else I have looked at.

I initialise like this:
```
        OAuth20Service service = new ServiceBuilder(clientId)
                .build(KeycloakApi.instance(baseUrl, realm));
        OAuth2AccessToken token = service.getAccessTokenPasswordGrant(user, password);
```

I have had to create my own KeycloakApi to return the right ClientAuthentication.

I have only had to add this to the existing API.
```
@Override
    public ClientAuthentication getClientAuthentication() {
        return new RequestBodyAuthenticationScheme(){};
    }
```

From all the testing that I have been doing a user/password based authentication requires the `client_id` field in the request body, which in scribejava is delivered by the `RequestBodyAuthenticaitonScheme` class.

Have I miss-understood something?

**Comment by kullfar** [comment]
Could you write here what is the problem that you have? Any Exceptions, errors, responses with error etc.

**Comment by kullfar** [comment]
out-dated

**Comment by web-cstone** [comment]
Hi. I am still interested in this. I have just been busy with other things recently. But I can not generate the error at the moment.

**Comment by kullfar** [comment]
I see, just reopen this issue in case you have any error again.

As for RequestBodyAuthenticationScheme, if you provide me with test user credentials and test app client id and secret to run the example, I'll merge it to the master (c) https://github.com/scribejava/scribejava/wiki/FAQ#when-will-you-support-insert_api_here- me

ps. it's better to use singleton
```
    @Override
    public ClientAuthentication getClientAuthentication() {
        return RequestBodyAuthenticationScheme.instance();
    }
```
