### ISSUE TITLE
errors at example

### ISSUE THREAD

**Issue by intmainreturn00** [scribejava/scribejava#893]
Hi, i'm trying to extend `DefaultApi10a` as shown at the [Custom-Apis] section (https://github.com/scribejava/scribejava/wiki/Custom-Apis) but i've got a few errors showing that the example was probably written for another version (i'm using `compile' com.github.scribejava:scribejava-apis:5.4.0'` as suggested at the installation guide):

* first, we need to override one more method at extended class : `getAuthorizationBaseUrl` - example didn't mention it and what it should provide.
* also at this sampe you are calling `ServiceBuilder()` ctor without key, which is contradictory to the current api as far as i can tell

**Comment by kullfar** [comment]
Hi,
it's not an example, it's a wiki. It's always outdated more or less.
You are free to update it.
