### ISSUE TITLE
OAuth20Service.getAccessToken not contain's the parameter of 'client_id'

### ISSUE THREAD

**Issue by awq9524** [scribejava/scribejava#895]
I use scribejava to get bearer token from aliyun。 But OAuth20Service.getAccessToken not contain's the parameter of 'client_id', And 'client_id' parameter is required for accessTokenRequest

**Comment by kullfar** [comment]
Try the example
Working runnable examples are here https://github.com/scribejava/scribejava/tree/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples

Common usage: https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples/Google20Example.java
