### ISSUE TITLE
Introspection -- RFC 7662

### ISSUE THREAD

**Issue by dhait** [scribejava/scribejava#898]
Are there any plans to support OAuth2 Introspection (RFC 7662)? This would involve a POST to an "/introspection" endpoint.

**Comment by kullfar** [comment]
Hi, I think, no. At least I didn't hear anything about such plans.
All code here is from Pull Requests. You can make such PR with support for RFC 7662 as well.

**Comment by SteveHarney** [comment]
Although not implemented directly in scribejava..  it is fairly trivial to implement with the tools available. 

        OAuthRequest request = new OAuthRequest(Verb.POST, introspectionEndpointURL);
        HttpBasicAuthenticationScheme.instance().addClientAuthentication(request, clientId, clientSecret);
        request.addParameter("token", token);
        
        OAuth20Service service = ...;
        Response response = service.execute(request);
        if (response.getCode() != 200)
        {
            OAuth2AccessTokenJsonExtractor.instance().generateError(response.getBody());
        }
        String result = response.getBody();

**Comment by miltonbo** [comment]
Might be good to have this feature (token introspection).
