### ISSUE TITLE
Can i use the redirect url to get auth_verifier instead of pin code in twitter 

### ISSUE THREAD

**Issue by TheEagle0** [scribejava/scribejava#900]
I'm trying to use my redirect url to get the auth verifier so is there is any way to do this within the library

**Comment by kullfar** [comment]
Look for examples
https://github.com/scribejava/scribejava/tree/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples

**Comment by TheEagle0** [comment]
Actually I'm using this example 
[](https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples/TwitterExample.java)
 if there is any recomendation for another example please let me know.

**Comment by kullfar** [comment]
And what is the problem with running the TwitterExample?
On which line is the problem?

**Comment by TheEagle0** [comment]
There is no problem with the example I just want to know if the library supports working with redirect URL or not because twitter example is working wit the pin code to get the auth_verifier

**Comment by kullfar** [comment]
Ah, I see. Yes, ScribeJava does support this
