### ISSUE TITLE
How do I upgrade from version 4.0.0 to version above, where and how do I get api Key?

### ISSUE THREAD

**Issue by DinaDurykina** [scribejava/scribejava#905]
I'm making an application based on an open source project that in turn uses 'com.github.scribejava:scribejava-apis:4.0.0', 
raising this library to the latest version fails, gives a compilation error. The new version requires api Key, where and how to get it?

**Comment by kullfar** [comment]
Hi,
first of all, I don't think it's a good idea to upgrade only ScribeJava without upgrading that open source project and to have two versions of ScribeJava in classpath as result.
Second, try to upgrade version by version. Each new version should be backward-compatible with the previous one with deprecation warnings, just fix them (javadocs always have hints) and go forward to the next version.
In case you will have trouble with upgrading to one or another version, let me know.
Stacktraces, compile errors is a must to mention in that cases.

**Comment by DinaDurykina** [comment]
Thanks for the reply. In version 4.0.0, Service Builder() is empty in parentheses. 
A String apiKey is expected when you try to update in parentheses.
An error in this code when I raise the library to the next version.
ServiceBuilder serviceBuilder = new ServiceBuilder();
                        serviceBuilder.apiKey(client_id);
                        if(client_secret.length() > 0) {
                            serviceBuilder.apiSecret(client_secret);
                        }
                        if(authorize_options_data.has("scope") && 
                        authorize_options_data.getString("scope").length() > 0) {
                        serviceBuilder.scope(authorize_options_data.getString("scope"));
                        }
                        if(authorize_options_data.has("state") && 
                        authorize_options_data.getString("state").length() > 0) {
                        serviceBuilder.state(authorize_options_data.getString("state"));
                        }
                        final OAuth20Service oauthService = serviceBuilder.build(oauthApi);

serviceBuilder.scope - 
serviceBuilder.state - it's not

I'm sorry if I'm still asking the wrong question, I'm learning and working to get better.

**Comment by kullfar** [comment]
```
ServiceBuilder serviceBuilder = new ServiceBuilder();
serviceBuilder.apiKey(client_id);
```
change to
```
ServiceBuilder serviceBuilder = new ServiceBuilder(client_id);
```

serviceBuilder.scope and serviceBuilder.state are needed only for AccessToken requests and should be used in this requests only.
But you can set serviceBuilder.defaultScope if you want.
and serviceBuilder.state is only per request.

Look for working examples here https://github.com/scribejava/scribejava/tree/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples

Google's one
https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples/Google20Example.java

And answer for you first question is on the main page, first abstract
Dead Simple
Who said OAuth/OAuth2 was difficult? Configuring ScribeJava is so easy your grandma can do it! check it out:
```
OAuthService service = new ServiceBuilder(YOUR_API_KEY)
                                  .apiSecret(YOUR_API_SECRET)
                                  .build(LinkedInApi20.instance());
```
