### ISSUE TITLE
Bearer Token Example

### ISSUE THREAD

**Issue by afrancoc2000** [scribejava/scribejava#907]
Hi, 

Can you guide me on how to validate a Bearer Token for a web API? I am working on authenticating a web API against Azure Active Directory V2.0 using a Bearer token I get from the frontend, and I see that the OAuth 2.0 Authorization flow for Bearer Token is implemented but I'm a little lost on how to use your classes.

I can create an example after.

Thanks!

Thanks

**Comment by kullfar** [comment]
Hi,
what do you mean by "validating a Bearer Token"?
ScribeJava is a client Oauth library. It just send Token to Server and validation is on the server side. On AAD in your case.

You don't need to think about that usualy ;-)
There is interface BearerSignature and two implementations (for https://tools.ietf.org/html/rfc6750#section-2.1 and https://tools.ietf.org/html/rfc6750#section-2.3).
API class define which one to use.
MicrosoftAzureActiveDirectory20Api have this method
```
    @Override
    public BearerSignature getBearerSignature() {
        return MicrosoftAzureActiveDirectory20BearerSignature.instance();
    }
```

it overrides default signature mechanism from DefaultApi20
```
    public BearerSignature getBearerSignature() {
        return BearerSignatureAuthorizationRequestHeaderField.instance();
    }
```
with custom AAD BearerSignature one, which is implemented in class MicrosoftAzureActiveDirectory20BearerSignature

**Comment by afrancoc2000** [comment]
My app is a backend API and a frontend sends me an Authentication header with a Bearer token, this token is an idToken and I need to check it is a valid one to return the resource.

on the msal4j library I was looking at the methods to get an access token "OnBehalfOf" kind of like this:

    ConfidentialClientApplication clientApplication = ConfidentialClientApplication.builder(
            clientId, ClientCredentialFactory.create(clientSecret))
                .authority(authority).build();

    Set<String> scopes = new HashSet<>(Arrays.asList(scope.split(" ")));
    UserAssertion assertion = new UserAssertion(idToken);

    OnBehalfOfParameters params = OnBehalfOfParameters.builder(scopes, assertion).build();
    CompletableFuture<AuthenticationResult> future = clientApplication.acquireToken(params);

    AuthenticationResult result = future.get();

I'm getting an error though.

How can I do the same thing using ScribeJava?

So, what I mean by verifing the Bearer token is to get an access token from an Id Token given by an external app and getting an access token or checking that this token is good, by checking its signature or something, before sending the resourse back.

Thanks!

**Comment by kullfar** [comment]
Hm... it seems you are speaking about microsoft specific "on-behalf-of" flow.
I didn't find any RFC about it. Unfortunately, I don't know anything about this flow.

**Comment by afrancoc2000** [comment]
Ahh ok thanks

**Comment by kullfar** [comment]
Anymore questions?
Should we close the issue?

**Comment by afrancoc2000** [comment]
Yes lets close it. Thank you!! :)
