### ISSUE TITLE
Linkedin api not working anymore

### ISSUE THREAD

**Issue by peternees** [scribejava/scribejava#908]
The LinkedIn2.0 example does not work anymore since today. The PROTECTED_RESOURCE_URL has changed to I think to https://api.linkedin.com/v2/me. 
However, if I use that v2 protected resource endpoint, I get a permission failure. (403)

**Comment by peternees** [comment]
Solved: upgraded to scribejava 6.5.1 and applied https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/migration-faq?context=linkedin/consumer/context

**Comment by kullfar** [comment]
So, does ScribeJava need any changes? Or on its side all is ok already?

**Comment by peternees** [comment]
Only the LinkedIn20Example.java example needs an update:

private static final String PROTECTED_RESOURCE_URL = "https://api.linkedin.com/v2/me";
private static final String PROTECTED_EMAIL_RESOURCE_URL = "https://api.linkedin.com/v2/emailAddress?q=members&projection=(elements*(handle~))";


final OAuth20Service service = new ServiceBuilder(clientId)
                .apiSecret(clientSecret)
                ..defaultScope("r_emailaddress r_liteprofile") // replace with desired scope
                .callback("http://example.com/callback")
                .build(LinkedInApi20.instance());

final String secretState = "secret" + new Random().nextInt(999_999);
final String authorizationUrl = service.getAuthorizationUrl(secretState);
...
final OAuthRequest request = new OAuthRequest(Verb.GET, String.format(PROTECTED_RESOURCE_URL, query));
...
// To obtain the email address:
final OAuthRequest emailRequest = new OAuthRequest(Verb.GET, String.format(PROTECTED_EMAIL_RESOURCE_URL , query));
...

**Comment by kullfar** [comment]
Thanks for the info, I have updated the master
https://github.com/scribejava/scribejava/commit/4f84b315f17d4a4623ed78cf073b7dc8b2792865
