### ISSUE TITLE
Default access token extractor don't unescape json

### ISSUE THREAD

**Issue by galimru** [scribejava/scribejava#909]
The extractor class `OAuth2AccessTokenJsonExtractor` uses regular expressions to extract tokens from JSON response. It will work fine until service escaped access token in JSON response. For example, service returns this response
```JSON
{
    "access_token": "fkFjvLZ\/hKSueaLh7pRQDQ8cXzxbWp7QvXl..."
}
```
The symbol `/` in access token escaped so we should use this access token `fkFjvLZ/hKSueaLh7pRQDQ8cXzxbWp7QvXl` for signed requests.
Reference documentation: https://tools.ietf.org/html/rfc7159

I've sorted out this using a custom extractor and `StringEscapeUtils.unescapeJson` but I believe it should be implemented in ScribeJava.

**Comment by kullfar** [comment]
Hi, thanks for info. I Will look closer.
BTW, RFC 7159 was Obsoleted by https://tools.ietf.org/html/rfc8259

**Comment by kullfar** [comment]
Ok, it seems, it's a time to switch from ugly hacks with regexps to jackson dependency.
StringEscapeUtils was unavailable as well. ScribeJava had not any dependency yet. Jackson will be the first one, but support json without json library in dependecy is too hard.
fix is in the master https://github.com/scribejava/scribejava/commit/7d2ce91c04bd4ec8d3ce48de7dd6f53522d50db0
thx for pointing that issue.
