### ISSUE TITLE
Sign in with Apple

### ISSUE THREAD

**Issue by snamstorm** [scribejava/scribejava#910]
Any plan to implement / support the newly announced "Sign in with Apple" feature?

**Comment by kullfar** [comment]
Hi, I have no info.
But you can always use ScribeJava with any custom API
https://github.com/scribejava/scribejava/wiki/Custom-Apis
or add it
https://github.com/scribejava/scribejava/wiki/FAQ#when-will-you-support-insert_api_here-

**Comment by meraedit** [comment]
created PR #1074
