### ISSUE TITLE
NullPointerException without openid scope Google

### ISSUE THREAD

**Issue by mikaelalmgren** [scribejava/scribejava#911]
When using the Google api `GoogleApi20` a `NullPointerException` is thrown if the scope "openid" is missing. This is because the value for the key `"id_token"`, in `OpenIdJsonTokenExtractor.java#L27`, is `null` (missing from the JSON response) and `.asText()` is called on the value.
I think the response contains a "regular" access token when the "openid" scope is omitted, and not a "openid access token".

**Comment by kullfar** [comment]
Hi, thx for pointing this. Will fix soon

**Comment by kullfar** [comment]
The fix in the master, v6.6.3 is ready, will be on the maven central after synchronisations.
