### ISSUE TITLE
Adding authorization data to Request Headers

### ISSUE THREAD

**Issue by BelalAboarab** [scribejava/scribejava#914]
Hey guys,

I'm using Scribe and I'm trying to send message via Twitter API, but It always tell me that "Unable to authenticate you", and the reason to this that It requires some authorization data in headers. I did that successfully in Postman and sent the message but I want to implement it in Java. So any one can help?

**Comment by kullfar** [comment]
Hi, first of all, ensure that you use the latest ScribeJava version.
Next, ScribeJava is the unpaid opensource project. You can try to fix this issue and share via PullRequest ;-)
I have no experience working with Twitter API.
And the last, code snippet are must be to get a help.

**Comment by BelalAboarab** [comment]
Thanks Kullfar for your answer,
I don't know if this is an Issue or not, I'm just having a concern whether this is something that can be done or not.

So, my concern is can I add authorization data to request headers or not? I add request headers as shown below in the snippet, but I always receive "Could not authorize you."


`

                 public void sendMessage(String recieverID, String body, OAuth10aService service, OAuth1AccessToken accessToken) {
                 
                    try {

                    String apiURL = "https://api.twitter.com/1.1/direct_messages/events/new.json";
			final OAuthRequest request = new OAuthRequest(Verb.POST, apiURL);

                    request.addHeader("Authorization", "OAuth oauth_consumer_key=API KEY,oauth_token=ACCESS TOKEN");

			request.addHeader("Content-Type", "application/json");
			//System.out.println(request.getHeaders());
			request.addParameter("type", "message_create");
			request.addParameter("message_create.target.recipient_id", recieverID);
			request.addParameter("message_create.message_data ", body);
			service.signRequest(accessToken, request);
			final Response response = service.execute(request);
			System.out.println(response.getBody());
			System.out.println(response.toString());
		} catch (Exception ex) {
			System.out.println("Exception: " + ex.getMessage());
		} `

**Comment by kullfar** [comment]
1. did you try to run the example? https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples/TwitterExample.java

2. You do not need to add any auth header. It's ScribeJava's job.
ScribeJava collects needed auth data in this method ```service.signRequest```
here https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/oauth/OAuth10aService.java#L139
and here https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/oauth/OAuth10aService.java#L78


and then adds it as header here https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/oauth/OAuth10aService.java#L178

Maybe there is a bug or Twitter had changed their API sometime ago.

You can debug and compare requests with one from Postman to fix your(or ScribeJava) code.

**Comment by BelalAboarab** [comment]
Dear Kullfar,
I almost got all APIs working except for sending messages, as I told you earlier it returns "Could not authenticate you".

I tried to add OAuthparameters, but it returns with an exception: OAuth parameters must either be 'scope', 'realm' or start with 'oauth_'.

The only difference between the request on ScribeJava & Postman is that when authorizing I chose the option to add authorization data to request headers, that made it work on postman.

So any idea how to do it in ScribeJava?

![Postman-screenshot](https://user-images.githubusercontent.com/52494085/60797697-0f808200-a170-11e9-8005-99fc08582675.png)

**Comment by kullfar** [comment]
Hi,
this is controlled by method
```
    public OAuth1SignatureType getSignatureType() {
        return OAuth1SignatureType.HEADER;
    }
```
in the https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/builder/api/DefaultApi10a.java#L87

It's not overrided by TwitterApi, so ScribeJava use Headers already to add authorisation data.

You have to analyze the resulted Http request in ScribeJava (using java debug for example) and maybe compare it with the request, generated by Postman

**Comment by kullfar** [comment]
If you have successfully done any API request to Twitter, I think the problem is not in auth headers. Maybe you haven't requested needed scope for your AccessToken.

**Comment by BelalAboarab** [comment]
And how can I request the scope for the AccessToken?

**Comment by kullfar** [comment]
use this method in Builder
https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/builder/ServiceBuilderOAuth10a.java#L39

**Comment by kullfar** [comment]
like here
https://github.com/scribejava/scribejava/blob/caf0bf5074f73b4c47ca9e2f8a4a4cfde65f0228/scribejava-apis/src/test/java/com/github/scribejava/apis/examples/FreelancerExample.java#L30
