### ISSUE TITLE
linkedin post

### ISSUE THREAD

**Issue by JhenieS326** [scribejava/scribejava#915]
Do you have any sample of posting on Linked In using scribe. I used the old code  from API v1 but it didn't work? :( Any help would be appreciated. Thank you.

**Comment by kullfar** [comment]
Hi, only these
https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples/LinkedInExample.java
https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples/LinkedInExampleWithScopes.java
https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples/LinkedIn20Example.java
