### ISSUE TITLE
"Bad" Test Name Detection (Research proposal, feedback needed)

### ISSUE THREAD

**Issue by Jianwei-Wu-1** [scribejava/scribejava#916]
Hello Developers for scribejava/scribejava:

I'm Jianwei Wu, and a PhD student from University of Delaware. I'm conducting an evaluation of my current research work, and the following contents are partial results of my research. In order to evaluate my work, I might need your feedbacks for the following contents.

Explanation of the contents: 
The following contents are some improvements of existing test names in your Github project (this project). The first line shows the original test names, and the second line shows our extracted components from the test name and the test body. If they are not matching, then we will consider it "bad" for the test name. "Better" test name means we take the extracted components from the test body to provide a "better" version of the test name. For your feedbacks, you can accept or reject our modification, and a partial accept or reject is also welcomed. Any other kinds of feedbacks or comments are also welcomed.

Contents: 
TestName: shouldParseResponse (OAuth2AccessTokenJsonExtractorTest)
SC body action: getAccessToken | ok
SC body predicate: assertEquals
SC body scenario: token (Alternative Scenario: token=1 )
SC name action: null(Regex)
SC name predicate: null(Regex)
SC name scenario: null(Regex)
-> 
unmatched with name
unmatched with name
unmatched with name
-> 
"Better" test name -> GetAccessToken/OK(...)Equals(...)Token

TestName: shouldExcludePort80 (BaseStringExtractorTest)
SC body action: [Refer to Alternative] (Alternative Action: extract=1 )
SC body predicate: assertEquals
SC body scenario: N/A (Alternative Scenario: baseString=1 )
SC name action: null(Regex)
SC name predicate: null(Regex)
SC name scenario: null(Regex)

-> 
unmatched with name
unmatched with name
unmatched with name
-> 
"Better" test name -> Extract(...)Equals(...)BaseString

TestName: shouldProperlySortParameters (ParameterListTest)
SC body action: asFormUrlEncodedString[Only] (Alternative Action: add=4 )
SC body predicate: Assert.assertEquals[Only]
SC body scenario: add (Alternative Scenario:  )
SC name action: null(Regex)
SC name predicate: null(Regex)
SC name scenario: null(Regex)

-> 
unmatched with name
unmatched with name
unmatched with name
-> 
"Better" test name -> AsFormUrlEncodedString/Add(...)Equals(...)

TestName: testSimpleMultipartPayload (JDKHttpClientTest)
SC body action: append(unmatched with outside)
SC body predicate: N/A
SC body scenario: header(unmatched with outside)
SC name action: testSimpleMultipartPayload(Regex)
SC name predicate: null(Regex)
SC name scenario: null(Regex)
-> 
unmatched with name
unmatched with name
unmatched with name
-> 
"Better" test name -> Append(...)Header
---End

Thank you so much for your help and any feedback would be appreciated! 
Jianwei Wu

**Comment by Jianwei-Wu-1** [comment]
We also include some “good” test names:

SimpleComparison:shouldExceptionIfRequestIsNull (HeaderExtractorTest)
SC body action: extract (Alternative Action: extract=1 )
SC body predicate: N/A
SC body scenario: extractor (Alternative Scenario:  )
SC name action: is(NLP)
SC name predicate: N/A(NLP)
SC name scenario: exception(NLP)

**Comment by kullfar** [comment]
not interested
