### ISSUE TITLE
It is not mandatory that a POST contains a body

### ISSUE THREAD

**Issue by jkoorts** [scribejava/scribejava#918]
com.github.scribejava.core.httpclient.jdk

private static void addBody(HttpURLConnection connection, byte[] content, boolean requiresBody) throws IOException {
        final int contentLength = content.length;
        if (requiresBody || contentLength > 0) {
            prepareConnectionForBodyAndGetOutputStream(connection, contentLength).write(content);
        }
    }

Should be 

private static void addBody(HttpURLConnection connection, byte[] content, boolean requiresBody) throws IOException {
        final int contentLength = content.length;
        if (contentLength > 0) {
            prepareConnectionForBodyAndGetOutputStream(connection, contentLength).write(content);
        }
    }

**Comment by kullfar** [comment]
Thanks for reporting. Do you know any such provider, who accept POST without payload. Or any case when you need POST without body. It's very strange semantic - "POST nothing".

**Comment by jkoorts** [comment]
Sure do,

JHipster UAA

POST: http://127.0.0.1:9999/oauth/token?username=user&password=user&grant_type=password&scope=openid

**Comment by kullfar** [comment]
Ugh... Sending password in the query param is totally insecure. I'd recommend not to use such framework. or... Maybe you have just misunderstood their docs? 

Maybe request should look like
POST: http://127.0.0.1:9999/oauth/token username=user&password=user&grant_type=password&scope=openid

in curl notation:
curl -X POST 'http://127.0.0.1:9999/oauth/token' -d "username=user&password=user&grant_type=password&scope=openid"

As an example here
https://www.baeldung.com/jhipster-uaa-secured-micro-service

```
$ curl -X POST --data \
 "username=user&password=user&grant_type=password&scope=openid" \
 http://web_app:changeit@localhost:9999/oauth/token
```

**Comment by kullfar** [comment]
May be both variants are supported by JHipster. I'd prefer to use good one. POST with data

**Comment by jkoorts** [comment]
"Sending password in the query param is totally insecure"

If sent over HTTPS it does not matter how you send it - it will be secure.  If send over HTTP also does not matter as well - insecure.

JHipster is a very good tool.

Note that the RFC 2616 does not dictate that POST contain a body.

**Comment by kullfar** [comment]
Password in query param is not about HTTP(S). Request URLs are logged frequently, are in referrer headers, are in browser address fields etc.
But you are right, POST doesn't require entity body (I'd prefer RFC 7231, 7230 however, 2616 was obsoleted by them)

And your proposed fix is incomplete. We should set the Content-Length header (it's set in code under requiresBody check).
```
   A user agent SHOULD send a Content-Length in a request message when
   no Transfer-Encoding is sent and the request method defines a meaning
   for an enclosed payload body.  For example, a Content-Length header
   field is normally sent in a POST request even when the value is 0
   (indicating an empty payload body).
```
https://tools.ietf.org/html/rfc7230#section-3.3.2

I have added small fix to the master https://github.com/scribejava/scribejava/commit/6e85a3bc7335e5732c009429747c49561314b153

As for your problem. What type of error do you have? Stacktrace will awesome. As for now, I don't see any situations you will have an Exception or any other trouble.

**Comment by jkoorts** [comment]
I think it was a null pointer because of prepareConnectionForBodyAndGetOutputStream(connection, contentLength).write(content); //my content was null

**Comment by kullfar** [comment]
I have inspected code, it should be byte[0], zero-lentgh array, not a null.
If you can reproduce the Exception, please let me know, so I can fix it.

**Comment by jkoorts** [comment]
Sorry don't have the code with me anymore. I reverted to write my own REST call (JHipster handles actually most of the OAUTH2 stuff eg. refreshing) with retrofit and so on.

**Comment by kullfar** [comment]
I see. Ok, do you need this issue to be open or we can close it?

**Comment by jkoorts** [comment]
You can close thanks
