### ISSUE TITLE
Document potential for memory leak

### ISSUE THREAD

**Issue by omaric** [scribejava/scribejava#922]
At least when using OkHttpHttpClient, a `Response` contains an InputStream. That InputStream must be closed or it will result in a memory leak. The way OkHttp3 alerts users to this possibility is that both Response and ResponseBody implement Closeable, and ResponseBody [has a lot of JavaDoc on closing the resource](https://square.github.io/okhttp/3.x/okhttp/okhttp3/ResponseBody.html) including a statement in bold "The response body must be closed."

ScribeJava should do the same by at least writing a JavaDoc comment on the Response class that "the response body stream (if non-null) should be closed by calling `getBody()` or `getStream().close()`."

**Comment by kullfar** [comment]
good point, thx.
Pull Request will be awesome

**Comment by omaric** [comment]
Done.

**Comment by kullfar** [comment]
fixed in https://github.com/scribejava/scribejava/pull/923
