### ISSUE TITLE
ServiceBuilderOAuth10a builder returns ServiceBuilderOAuth20

### ISSUE THREAD

**Issue by mgyucht** [scribejava/scribejava#925]
It seems like the ServiceBuilderOAuth10a builder returns ServiceBuilderOAuth20 for some of its methods. I'm not sure if this is intentional, but it does mean that I can't, for example, configure the HttpClient I want to use for an OAuth 1.0a client.

I created #924 to fix this problem; let me know if you have any questions or concerns about this.

**Comment by kullfar** [comment]
fixed, PR have been merged to the master, Thx a lot!
