### ISSUE TITLE
Etsy integration 411 HTTP Exception

### ISSUE THREAD

**Issue by mikita-herasiutsin** [scribejava/scribejava#926]
Going though etsy's example https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples/EtsyExample.java
found an exception like that:
```
<p><b>411.</b> <ins>That’s an error.</ins>
  <p>POST requests require a <code>Content-length</code> header.  <ins>That’s all we know.</ins>
```
Fixed that by overriding getAccessTokenVerb and getRequestTokenVerb to use GET
Am I doing something wrong or it is broken?

**Comment by kullfar** [comment]
Got it. I have found an error in ScribeJava. Will fix it soon

**Comment by kullfar** [comment]
fix is in the master https://github.com/scribejava/scribejava/commit/8caa3ae90dc4d28e07021f446751fed15cf07c62
Thanks for pointing that.

For history: was broken here https://github.com/scribejava/scribejava/commit/6e85a3bc7335e5732c009429747c49561314b153 made for https://github.com/scribejava/scribejava/issues/918
