### ISSUE TITLE
OAuthExcepion Specifying No Content Length

### ISSUE THREAD

**Issue by iankurverma** [scribejava/scribejava#927]
Hi,

I am having below error for Yahoo when i am trying to retrieve getRequestToken(). Could you please help me how i can fix this issue. This API used to work with older pom version but now it has stopped working.

com.github.scribejava.core.exceptions.OAuthException: Response body is incorrect. Can't extract token and secret from this: '<HTML>
<HEAD>
<TITLE>No Content Length</TITLE>
</HEAD>

<BODY BGCOLOR="white" FGCOLOR="black">
<H1>No Content Length</H1>
<HR>

<FONT FACE="Helvetica,Arial"><B>
Description: Could not process this request because
there was no Content-Length specified.
</B></FONT>
<HR>
</BODY>

**Comment by kullfar** [comment]
Got it. I have found an error in ScribeJava. Will fix it soon

**Comment by kullfar** [comment]
fix is in the master https://github.com/scribejava/scribejava/commit/8caa3ae90dc4d28e07021f446751fed15cf07c62
Thanks for pointing that.

For history: was broken here https://github.com/scribejava/scribejava/commit/6e85a3bc7335e5732c009429747c49561314b153 made for https://github.com/scribejava/scribejava/issues/918
