### ISSUE TITLE
Error 405 HTTP method POST is not supported by this URL

### ISSUE THREAD

**Issue by iankurverma** [scribejava/scribejava#928]
Hey, thank you so much for fixing OAuthExcepion Specifying No Content Length issue quickly.
This issue is no longer reproducible, however now i am encountering a new issue while i try to  retrieve the token i am getting the blow error for YahooAPI. Below is the stack trace. Could you please look into it once or guide me how i can fix this issue.

com.github.scribejava.core.exceptions.OAuthException: Response body is incorrect. Can't extract token and secret from this: '<html>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 405 HTTP method POST is not supported by this URL</title>
<body><h2>HTTP ERROR 405</h2>
<p>Problem accessing /oauth/v2/get_request_token. Reason:
<pre>    HTTP method POST is not supported by this URL</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.z-SNAPSHOT</a><hr/>
</body>

at com.github.scribejava.core.extractors.AbstractOAuth1TokenExtractor.extract(AbstractOAuth1TokenExtractor.java:42)
	at com.github.scribejava.core.extractors.AbstractOAuth1TokenExtractor.extract(AbstractOAuth1TokenExtractor.java:32)
	at com.github.scribejava.core.extractors.AbstractOAuth1TokenExtractor.extract(AbstractOAuth1TokenExtractor.java:19)
	at com.github.scribejava.core.oauth.OAuth10aService.getRequestToken(OAuth10aService.java:48)

**Comment by kullfar** [comment]
Hi,
First of all, you're using https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/main/java/com/github/scribejava/apis/YahooApi.java, maybe it's time to switch to https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/main/java/com/github/scribejava/apis/YahooApi20.java?
Next, you can try to change POST to another HTTP method by overriding method
```
    public Verb getRequestTokenVerb() {
        return Verb.POST;
    }
```
from https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/builder/api/DefaultApi10a.java
in the https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/main/java/com/github/scribejava/apis/YahooApi.java

**Comment by kullfar** [comment]
Hi, sorry no, I don't know Yahoo API. It's out of scope for ScribeJava

**Comment by kullfar** [comment]
Does anyone still need this issue to be open?

**Comment by iankurverma** [comment]
Please close this issue. Thanks for your support
