### ISSUE TITLE
ServiceBuilder.withScope() returns ServiceBuilderOAuth10a

### ISSUE THREAD

**Issue by volgin** [scribejava/scribejava#929]
This code works in 6.8.0, but shows an error in 6.8.1.

```
OAuth20Service fbService = new ServiceBuilder(clientId).apiSecret(secret)
.withScope("public_profile,email").callback(url).build(FacebookApi.instance());
```

**Comment by kullfar** [comment]
Right.
You should use ```.defaultScope("public_profile,email")```
https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/builder/ServiceBuilder.java#L61

The same effect internally, but it's more logically correct. You can override this default scope while requesting access_token
```final OAuth2AccessToken accessToken = service.getAccessToken(AccessTokenRequestParams.create(code).scope("another_one"));```

**Comment by kullfar** [comment]
Does anyone still need this issue to be open?
