### ISSUE TITLE
Access token missing xoauth_yahoo_guid for New YahooAPI

### ISSUE THREAD

**Issue by iankurverma** [scribejava/scribejava#930]
I am trying to retrive accesstoken using an oauthVerifier, I am able to retrive accesstoken and other parameters but **xoauth_yahoo_guid is missing** from the response. Is there a way i can retrieve the same with new Yahoo20API

**Comment by kullfar** [comment]
Sorry, dunno. It's out of scope for SribeJava.
It's Yahoo API specific question. ScribeJava is for getting access_token and sending (signing) requests, and all about OAuth, but not about vendor business API

**Comment by kullfar** [comment]
Does anyone still need this issue to be open?

**Comment by iankurverma** [comment]
No please close this issue.
