### ISSUE TITLE
The official Yahoo Oauth 2 Example is Giving 401

### ISSUE THREAD

**Issue by burakim** [scribejava/scribejava#938]
Hi Everyone, I used the given Yahoo Oauth 2.0 example to test this library. Eventhough, it is refreshing the access token successfully, It is giving  401 error continuously for accessing protected URLS. Here is the response that I am getting from Yahoo.
```
401
<?xml version='1.0' encoding='UTF-8'?>
<yahoo:error xmlns:yahoo='http://yahooapis.com/v1/base.rng'
  xml:lang='en-US'>
  <yahoo:description>Please provide valid credentials. OAuth oauth_problem="unable_to_determine_oauth_type", realm="yahooapis.com"</yahoo:description>
</yahoo:error>
```

**Comment by kullfar** [comment]
Hi.
1.Does any protected URL return 401, even one from the example?
2.Yahoo2 is here from v5.3.0. Could you try this or any other older versions, maybe we have introduced some bug to the ScribeJava. Or Yahoo have changed something. In that case new Pull Request will be needed.

**Comment by burakim** [comment]
1. The one that is given in the example, returns 200. However, my protected url returns 401. (https://api.gemini.yahoo.com/v3/rest/campaign/). I checked the token that was refreshed using Scribe, is working using Postman well.
2. I tested with older versions, the problem still persists.

**Comment by kullfar** [comment]
Sorry, I can't help you furthermore
Maybe @javatestcase can
```add Yahoo2 API (thanks to https://github.com/javatestcase)```
 https://github.com/scribejava/scribejava/blob/master/changelog#L93

**Comment by burakim** [comment]
@kullfar When I use with the OkHttp lib, it works well. I think something is wrong with native scribe network operation implementation.

**Comment by kullfar** [comment]
Hm... It's interesting. Maybe.
I can investigate and try to fix, but I will need test credentials for application in yahoo and test user. I don't have such. If you could provide them, I'll try to make this job.

**Comment by burakim** [comment]
@kullfar I'll try to create a user and an application to let you test your code in this weekend. I'll let you know when I finish it.

**Comment by kullfar** [comment]
outdated, no data was received
