### ISSUE TITLE
add a BOM

### ISSUE THREAD

**Issue by xenoterracide** [scribejava/scribejava#940]
so that one doesn't have to keep all versions the same can you add a BOM (bill of materials) artifact to your builds?

**Comment by kullfar** [comment]
Hi, Could you provide such dependency, which should to be kept the same version?
Actually ScribeJava is almost dependency-free library (jackson is the only one).
So, I can imagine only one such case - for this jackson dependency (if you add scribejava-httpclient-ning and scribejava-httpclient-okhttp in the same time with different versions, but why?).

I can't imagine real case.

**Comment by xenoterracide** [comment]
well, for example I added my deps like this, in theory if you did a release these could end up at different versions...

```
    implementation("com.github.scribejava:scribejava-core:6.+")
    implementation("com.github.scribejava:scribejava-httpclient-apache:6.+")
    implementation("com.github.scribejava:scribejava-apis:6.+")
```

with a bom you could write

```
    implementation(enforcedPlatform("com.github.scribejava:scribejava-bom:6.+"))
    implementation("com.github.scribejava:scribejava-httpclient-apache")
    implementation("com.github.scribejava:scribejava-apis")
```
which also gives the benefit of only having to change the code in one place. Really though it's up to you.... ultimately I personally won't need -apis because I'm not using a popular one ;).

**Comment by kullfar** [comment]
```
    implementation("com.github.scribejava:scribejava-core:6.+")
    implementation("com.github.scribejava:scribejava-httpclient-apache:6.+")
    implementation("com.github.scribejava:scribejava-apis:6.+")
```
You don't need scribejava-core. apis and httpclient-apache have it as transitive dependency.
All this modules are released at the same moment, never alone. It was so and will be so.

As for one line of code to change, in pom.xml it's easy to reach using properties
```
<properties>
    <scribejavaVersion>6.17.0</scribejavaVersion>
</properties>
...
<dependency>
    <groupId>com.github.scribejava</groupId>
    <artifactId>scribejava-httpclient-apache</artifactId>
    <version>${scribejavaVersion}</version>
</dependency>
<dependency>
    <groupId>com.github.scribejava</groupId>
    <artifactId>scribejava-apis</artifactId>
    <version>${scribejavaVersion}</version>
</dependency>
```

Anyway, thx for the idea.
