### ISSUE TITLE
Try to get Twitter Request Token gives me 401 Unauthorized

### ISSUE THREAD

**Issue by mraliagha** [scribejava/scribejava#941]
I have not been able to manage to work with Twitter on the first step of OAuth which is getting the OAuth access token:

```
twitterOAuthService = new ServiceBuilder(twitterOauthConsumerKey)
          .apiSecret(twitterOauthConsumerKey).debug().callback(callbackUrl).build(
              TwitterApi.instance());
      OAuth1RequestToken requestToken = twitterOAuthService.getRequestToken();
```

It throws the following exception:

`Response{code=401, message='Authorization Required', body='null', headers={date=Tue, 05 Nov 2019 07:06:34 GMT, null=HTTP/1.1 401 Authorization Required, server=tsa_l, content-length=64, expires=Tue, 31 Mar 1981 05:00:00 GMT, x-response-time=166, x-frame-options=SAMEORIGIN, www-authenticate=OAuth realm="https://api.twitter.com", x-transaction=00e2c19300b2d1ab, strict-transport-security=max-age=631138519, pragma=no-cache, set-cookie=guest_id=v1%3A157293759473549885; Max-Age=63072000; Expires=Thu, 4 Nov 2021 07:06:34 GMT; Path=/; Domain=.twitter.com, last-modified=Tue, 05 Nov 2019 07:06:34 GMT, x-xss-protection=0, x-content-type-options=nosniff, content-disposition=attachment; filename=json.json, x-connection-hash=badf004485a6d713a29ed3f90de9e981, x-twitter-response-tags=BouncerCompliant, content-type=application/json; charset=utf-8, cache-control=no-cache, no-store, must-revalidate, pre-check=0, post-check=0, status=401 Unauthorized}}
`

Is this some sort of bug I am hitting as I am able to get this to work using Postman without any issues?

Thanks

**Comment by kullfar** [comment]
Hi, I have no ideas, neither the twitter account.
Did you manage this problem somehow?

**Comment by mraliagha** [comment]
Yes. It was resolved. It was an app permission.
