### ISSUE TITLE
How can I get the Authorisation Token without copying and pasting it?

### ISSUE THREAD

**Issue by cosmabogdan** [scribejava/scribejava#942]
I am trying to use GitHub OAuth. How can I fetch the generated link back in the app without having to copy and paste the 2 codes?

**Comment by kullfar** [comment]
It's up to you.
In case of web site, backurl refers to your site, you just take GET params, in case of app (android, usually), you get the link from the webview (ScribeJava have util method to parse such urls).
But this question is not about ScribeJava
