### ISSUE TITLE
Exclude unused dependencies

### ISSUE THREAD

**Issue by cesarsotovalero** [scribejava/scribejava#943]
Hello, I noticed that in module `scribejava-httpclient-ahc` the transitive dependency `io.netty:netty-resolver-dns` is not used at all, and can be safely excluded from dependency `org.asynchttpclient:async-http-client`. This change has a positive impact on the module since this dependency has other dependencies that are also not used, and removing all of them makes the dependency tree of this scribejava module less complex and easier to maintain.

These are the dependencies that can be removed with this small change:

```
+- io.netty:netty-resolver-dns:jar:4.1.42.Final:compile
|  +- (io.netty:netty-common:jar:4.1.42.Final:compile - omitted for duplicate)
|  +- (io.netty:netty-buffer:jar:4.1.42.Final:compile - omitted for duplicate)
|  +- io.netty:netty-resolver:jar:4.1.42.Final:compile
|  |  \- (io.netty:netty-common:jar:4.1.42.Final:compile - omitted for duplicate)
|  +- (io.netty:netty-transport:jar:4.1.42.Final:compile - omitted for duplicate)
|  +- (io.netty:netty-codec:jar:4.1.42.Final:compile - omitted for duplicate)
|  \- io.netty:netty-codec-dns:jar:4.1.42.Final:compile
|     +- (io.netty:netty-common:jar:4.1.42.Final:compile - omitted for duplicate)
|     +- (io.netty:netty-buffer:jar:4.1.42.Final:compile - omitted for duplicate)
|     +- (io.netty:netty-transport:jar:4.1.42.Final:compile - omitted for duplicate)
|     \- (io.netty:netty-codec:jar:4.1.42.Final:compile - omitted for duplicate)
```

In addition, the compile scope dependency `org.jetbrains.kotlin:kotlin-stdlib-common`, which resides in the dependency tree of module ` scribejava-httpclient-okhttp`, is also not used by the module. Hence, it can be excluded from dependency `jetbrains.kotlin:kotlin-stdlib`.

Can I suggest these changes via pull requests?

**Comment by kullfar** [comment]
These dependencies are transitive. It's hard to decide, whether they will be used by first-level dependency in near future. It's safer to leave them. And the end user can exclude them in their projects.
Another point, we do not now how end user will use ScribeJava and it's http client, which he get via transitive dependencies.

Btw, user can always use core ScribeJava without any bundled http client at all.
