### ISSUE TITLE
Not possible to specify Accept: application/json to client credentials request

### ISSUE THREAD

**Issue by rantavuo** [scribejava/scribejava#946]
Endpoint we're trying to integrate to requires this header. Library does not set it, so we get 400 bad request, and I see no easy way of setting it (or any other similar headers).

Could there be a way to set such headers?

**Comment by rantavuo** [comment]
Well, I guess there are plenty of things that are not supported OOB but you need to implement yourself so closing this.

**Comment by kullfar** [comment]
If you didn't find the solution, try to look at the *Examples.
Working executable examples are here https://github.com/scribejava/scribejava/tree/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples

For example
``` request.addHeader("Accept", "application/json");```
https://github.com/scribejava/scribejava/blob/cca662cb770b8920e52e2a2a6dcf822db8d5e0e2/scribejava-apis/src/test/java/com/github/scribejava/apis/examples/PolarAPIExample.java#L71

Sometime you will need implement your own Service class, like
https://github.com/scribejava/scribejava/blob/cca662cb770b8920e52e2a2a6dcf822db8d5e0e2/scribejava-apis/src/main/java/com/github/scribejava/apis/wunderlist/WunderlistOAuthService.java#L23
or
https://github.com/scribejava/scribejava/blob/cca662cb770b8920e52e2a2a6dcf822db8d5e0e2/scribejava-apis/src/main/java/com/github/scribejava/apis/microsoftazureactivedirectory/BaseMicrosoftAzureActiveDirectoryBearerSignature.java#L18

if you will need to add new header to OAuth request's signature.
