### ISSUE TITLE
Setting request parameters in callback URL with ServiceBuilder for OAuth10aService

### ISSUE THREAD

**Issue by mklueh** [scribejava/scribejava#950]
Is there anything similar that let´s me set additional callback parameters when using the ServiceBuilder like this?

```
    Map<String,String> params;
    OAuth10aService auth = new ServiceBuilder(YOUR_API_KEY)
                .apiSecret(YOUR_API_SECRET)
                .callback(callback, params)
                .build(api);
```

**Comment by kullfar** [comment]
Hi, no. You can add all additional static (not dependable on each request)  params to the callback url.
Plus, OAuth provider will return unique per request 'state' and 'code' params to this callback url.
You can encode your requests data to the 'state' param.

**Comment by kullfar** [comment]
some additional info,
ServiceBuilder - is for multiple requests. It should not have anything special data for one request
