### ISSUE TITLE
Resource Owner Password Credentials Example?

### ISSUE THREAD

**Issue by dlauer** [scribejava/scribejava#955]
Hi! Your README says you support:
RFC 6749 The OAuth 2.0 Authorization Framework, Resource Owner Password Credentials Authorization Grant

But it's the only flow that doesn't have an associated example. I know it's a simple flow but I'm trying to track down the correct API calls - any pointers?

Thanks!

**Comment by Viktorhe** [comment]
This is example of Microsoft Azure Resource Owner Password Credentials

String clientid="your clientid";
Sting clientsecret = "your clientsecret";
String scope = "your scope";
OAuth2AccessToken token;
OAuth20Service oauth2Service;

oauth2Service = new ServiceBuilder(clientid)
				.apiSecret(clientsecret)
			           .defaultScope(scope)
			           .build(MicrosoftAzureActiveDirectory20Api.instance());

token = oauth2Service.getAccessTokenPasswordGrant(username, password);

**Comment by kullfar** [comment]
Right. There is no example, because I do not have application with approved permission to use this flow. If someone provide me such application and test user for it, I will make such an example.

And, yes. It's simple. Just one method as @Viktorhe wrote ```token = oauth2Service.getAccessTokenPasswordGrant(username, password);```
