### ISSUE TITLE
Obtaining id_token from access_token

### ISSUE THREAD

**Issue by david-wg2** [scribejava/scribejava#968]
Hi, thanks for making this library! I need to obtain and `id_token` from an `access_token`, which I currently do like this:

```kotlin
fun OAuth2AccessToken.getIdToken(): String {
    val jwtPayload = objectMapper.readTree(this.rawResponse)
            .get("id_token")
            .textValue()
            .split(".")[1] // jwt is header.payload.signature, we want payload
    return String(Base64.getDecoder().decode(jwtPayload))
}
```

This is a Kotlin extension function. If the syntax is unfamiliar, I basically read `accessToken.getRawResponse()` into Jackson and decode the `id_token` manually.

This seems like something that should be part of the library, but maybe there are reasons for not including it?

**Comment by kullfar** [comment]
Hi, @david-wg2 , not all OAuth providers give id_token in their responses. And it's not mandatory by the OAuth standards. It's OpenId part (that will be here in the future I believe, but not now).
But for them, who does, ScribeJava have OpenIdJsonTokenExtractor (https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/main/java/com/github/scribejava/apis/openid/OpenIdJsonTokenExtractor.java)
and OpenIdOAuth2AccessToken (https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/main/java/com/github/scribejava/apis/openid/OpenIdOAuth2AccessToken.java)

It's very easy to turn it on for a new provider. For the moment only three providers in ScibeJava use this subtype of AccessToken. It's a Frappe, Google and Keycloak (https://github.com/scribejava/scribejava/search?q=OpenIdJsonTokenExtractor).

**Comment by david-wg2** [comment]
Thank you @kullfar !
