### ISSUE TITLE
AhcHttpClientConfig prevents the Tomcat server from shutdown

### ISSUE THREAD

**Issue by lianhwang** [scribejava/scribejava#970]
Use the following code in a Tomcat filter; but Tomcat cannot shutdown ... probably waiting on threads.

                clientConfig = new AhcHttpClientConfig(new DefaultAsyncHttpClientConfig.Builder()
                    .setMaxConnections(5)
                    .setRequestTimeout(10_000)
                    .setPooledConnectionIdleTimeout(1_000)
                    .setUseInsecureTrustManager(true)
                    .setReadTimeout(1_000)
                    .build());
            serviceBuilder.httpClientConfig(clientConfig);

**Comment by kullfar** [comment]
Hi, you should invoke close() on your OAuthService in some sort of onShutdown hooks for the Tomcat and it will close underlying async HTTP client as well.

**Comment by kullfar** [comment]
Put breakpoint here https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/extractors/OAuth2AccessTokenJsonExtractor.java#L33
