### ISSUE TITLE
Ms Azure Ad - Response body is incorrect. can't extract a token from an empty string.

### ISSUE THREAD

**Issue by AccFan23** [scribejava/scribejava#971]
Hello,

I'm using Scribejava to get an access token from Azure but it seems to be intermittently giving the following error:

**Response body is incorrect. can't extract a token from an empty string.**

I'm trying to figure out how to troubleshoot this further.  When I test it in my local it's working perfectly but when it's on my app server, it's a hit or miss.  Here's how I'm requesting the access token:

    	private static String getAccessToken(String clientId, String clientSecret,
			String tenantName)
			throws IOException, InterruptedException, ExecutionException {
		OAuth20Service service = new ServiceBuilder(clientId)
				.apiSecret(clientSecret).scope("openid")
				.build(MicrosoftAzureActiveDirectoryApi.customTenant(tenantName));
		
		String accessToken = service.getAccessTokenClientCredentialsGrant().getAccessToken();
		System.out.println("Access token is: " + accessToken);

		return accessToken;
          }

This has been working for quite some time on a different environment but this new one I'm trying to run it on has an issue, same codebase, same setup.

Any ideas?

Thank you

**Comment by kullfar** [comment]
Hi, first of all try to get full raw HTTP response. with response code, headers and maybe something in the body.

Put breakpoint here https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/extractors/OAuth2AccessTokenJsonExtractor.java#L33

You can use response.toString() here to see full HTTP Response.

Second, full stracktraces and error logs are welcome.

**Comment by kullfar** [comment]
Maybe HTTP response code will give you a hint for the error (network or API or...)

**Comment by AccFan23** [comment]
Thanks for the reply.  It turned out to be a firewall issue and nothing with the code/library.  Once we white listed the Azure IPs, it's been working fine since.

Thanks again!
