### ISSUE TITLE
The IP address of a host could not be determined when I make call with access token

### ISSUE THREAD

**Issue by wovvtech** [scribejava/scribejava#973]
My back end java REST application is running in tomcat server.
It is working fine and it is up and running.
In this application, I am using the ScribeJava OAuth library to make authentication and make API calls to SalesForce APEX REST API.
During this process, several times I face an issue and log the exception that is "**The IP address of a host could not be determined.**"
This happened for some span of a period of 2 to 3 hours, and then suddenly it gets stopped giving the above mention exception and then the system integration works normal and fine, and it starts giving the response.
It also happens for some requests, for EX. I make 20 API calls in 1 hour of time, and out of this 20 I get responses for 15 calls and do not receive responses for 5 calls and the same above mention exception gets logged. 
Kindly help us with this problem.

**Comment by kullfar** [comment]
I thinks it's not about ScribeJava, but about your network configuration and specifically DNS.
You can even hardcode ip of the server to the /etc/hosts to check and as a fast workaround.
