### ISSUE TITLE
Trading the Authorization Code for an Access Token for Discord brings out an error

### ISSUE THREAD

**Issue by Bedi58** [scribejava/scribejava#975]
When i use the Discord example for my button in my android app i have an android.os.NetworkOnMainThreadException on the line: OAuth2AccessToken accessToken = service.getAccessToken(code);

I have the right authorization code and i check all of my configs for example the callback url, client id, client secret...
Is there aother examples for Discord oauth2? Or anybody know why i have this issue?
<img width="817" alt="Anmerkung 2020-07-30 195802" src="https://user-images.githubusercontent.com/63723379/88957409-21632480-d29f-11ea-9008-5b4005fe5d27.png">
<img width="782" alt="Anmerkung 2020-07-30 195834" src="https://user-images.githubusercontent.com/63723379/88957421-27f19c00-d29f-11ea-99b7-98179c38c721.png">

**Comment by kullfar** [comment]
Hi, did you find the solution? It can help another users with the same problem.
