### ISSUE TITLE
Latest 7.0.0 version is not available to fetch from Maven

### ISSUE THREAD

**Issue by VictorAlbertos** [scribejava/scribejava#976]
Hi 👋 

I'm trying to add as a Gradle dependency to an Android Studio project the latest version: `implementation 'com.github.scribejava:scribejava-apis:7.0.0'` but I got this error: `Failed to resolve com.github.scribejava:scribejava-apis:7.0.0`, although if I set the version to `6.9.0` it works fine. 

It seems that `7.0.0` is not yet available on Maven, the README says that this is the version that we should use but I also see that this version was released just yesterday, so maybe we should wait and use the previous version?

Thanks!

**Comment by kullfar** [comment]
Hi, it's my fault. Usually, it takes from 15 mins to 2 hours to appear the artefact on the maven central, but I forgot to push it from the staging repo after testing.
Will push right now

**Comment by kullfar** [comment]
And... It's on the maven central now

**Comment by VictorAlbertos** [comment]
Thanks!
