### ISSUE TITLE
 Polar API not revoking token

### ISSUE THREAD

**Issue by PhilippS93** [scribejava/scribejava#977]
Hello,

the new PolarAPI (scribejava Version 7.0.0) does not provide the option to revoke the generated token. Due to the Polar API specification, this has to be done to reconnect a user (see https://www.polar.com/accesslink-api/#get-user-information)

Best,
Philipp

**Comment by kullfar** [comment]
Hi, the Polar API never provided the option to revoke token in the ScribeJava. It's a quite new option in the ScribeJava and has support from only Discord, Google and Keycloak APIs for the moment.

It's quite easy to add support of this option to any API.
In the simplest scenario you will only have to override getRevokeTokenEndpoint method from DefaultApi20 and provide correct url for access token revokation https://github.com/scribejava/scribejava/blob/54407f0e6103cc0df5e27a85a78d94ca2ef75ee3/scribejava-core/src/main/java/com/github/scribejava/core/builder/api/DefaultApi20.java#L72

as Google API does https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/main/java/com/github/scribejava/apis/GoogleApi20.java#L40

And if Polar API has no nonstandard mechanisms, it will work automagically.

If it does work for you, please make the Pull Request here.
And add some code to the example to demonstrate how it works. Just add to https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples/PolarAPIExample.java
something like that https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples/Google20RevokeExample.java#L88-L107
If it's not clear for you, just skip this step with the example, I'll add it myself.

One complexity is here - I have to test the changes, but I have no Polar application and user, so if you will submit changes to the Polar API I will need test app credentials and test user credentials. (Actually these credentials and revoke token url is enough, I can add needed source code).
