### ISSUE TITLE
Is there any plan for Zoom 0Auth2?

### ISSUE THREAD

**Issue by sushiljic** [scribejava/scribejava#981]
I find this library promising? But could not find Zoom integration out of box.
Due to Covid19 impact, Zoom is being used widely so I wish that I would be very best if 
Zoom could also be integrated.
[Zoom oauth](https://marketplace.zoom.us/docs/guides/auth/oauth)

**Comment by leotu** [comment]
> I find this library promising? But could not find Zoom integration out of box.
> Due to Covid19 impact, Zoom is being used widely so I wish that I would be very best if
> Zoom could also be integrated.
> [Zoom oauth](https://marketplace.zoom.us/docs/guides/auth/oauth)

Sample code:

1) Define API instance
```java
public class ZoomApi extends DefaultApi20 {

    protected ZoomApi() {
    }

    private static class InstanceHolder {
        private static final ZoomApi INSTANCE = new ZoomApi();
    }

    public static ZoomApi instance() {
        return InstanceHolder.INSTANCE;
    }

    @Override
    public String getAccessTokenEndpoint() {
        return "https://zoom.us/oauth/token";
    }

    @Override
    protected String getAuthorizationBaseUrl() {
        return "https://zoom.us/oauth/authorize";
    }
}
```

2) Write OAuth2 Client

```java
public class ZoomClient  {
   ...
  private final OAuth20Service service; 
  ...
  public ZoomClient() {
        this.service = new ServiceBuilder(clientId)
                .apiSecret(clientSecret)
                .defaultScope("user:read:admin accound:read:admin contact:read:admin")
                .callback("https://your_side/callback")
                .build(ZoomApi.instance());
    }
 ...
}
```

**Comment by kullfar** [comment]
@sushiljic https://github.com/scribejava/scribejava/wiki/FAQ#when-will-you-support-insert_api_here-
@leotu thx!

If someone can provide me Pull Request with Example and provide me test user credentials and test application credentials to run it, I will can merge it to the master. Thx!
