### ISSUE TITLE
Getting Latency in Response for 2 API.

### ISSUE THREAD

**Issue by shrikant-css** [scribejava/scribejava#987]
We are using the below Mention google liabrary to Make a request to https://www.googleapis.com/oauth2/v3/userinfo API & https://www.googleapis.com/oauth2/v4/token API. 
Google Library : 1. scribejava-core-6.3.0.jar
       
 1.  https://www.googleapis.com/oauth2/v3/userinfo  -> 7830 MS Response Latency
2. https://www.googleapis.com/oauth2/v4/token  -> 63,700 MS Response Latency. 
 
                                So please look into this as quickly as possible & Please suggest us how can we reduce response latency.
& Latency screen shot also i have added.
![Google-UserInfoAPI-Response-Latency](https://user-images.githubusercontent.com/74773298/99799367-83021400-2b58-11eb-8978-a654ae9a6455.png)
![UserInfo-API](https://user-images.githubusercontent.com/74773298/99799525-d4120800-2b58-11eb-8208-f1892b379abc.png)

**Comment by kullfar** [comment]
How does it relate to the scribejava?

**Comment by shrikant-css** [comment]
com.github.scribejava.core.oauth.OAuth20Service this Package We are Using to Make Above Request and it is an related to scribe java package only.

**Comment by kullfar** [comment]
Does latency was produced by ScribeJava code? I suppose it's cause is network configuration.
Could you try to make http request to googleapis.com without using ScribeJava?
Try from the console (even ping command) and then from the Java code, using raw java HttpUrlConnection. Like this:
```
final URL url = new URL(...);
final HttpURLConnection connection = (HttpURLConnection) url.openConnection();
connection.connect();
final int responseCode = connection.getResponseCode();
```
and adding lines from https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/httpclient/jdk/JDKHttpClient.java#L117-L145

Or even debugging this method.

p.s. Do you have any proxy configured?
p.s. Another suggestion is to try to use hardcoded ip, may be your DNS is working bad.
