### ISSUE TITLE
1-legged OAuth 1.0a

### ISSUE THREAD

**Issue by mohankumargopalsamy** [scribejava/scribejava#992]
Need a help for 1-legged OAuth 1.0a.

I only have access key and secret and endPoint to be accessed.  There are no other URLs given like accessToken URL or any sort of thing.  

I need it for accessing Alteryx API. They say for your own client, you will need to implement or use third-party signature generation code based upon the OAuth 1.0a standard.The Alteryx API does not implement the full three-legged OAuth 1.0a flow. Instead, we only require the signature generation. This is sometimes called a one-legged flow. Please see the OAuth 1.0a specification for information, paying special attention to the Signing Process section.

In addition to the parameters specified in each API method below, the following parameters are required for every API call:

oauth_consumer_key
oauth_signature_method (must be HMAC-SHA1)
oauth_signature
oauth_timestamp
oauth_nonce
You may also reference a fully functional sample Alteryx client in C# or JavaScript.

**Comment by mohankumargopalsamy** [comment]
Just to clarify again, I need some thing without APIProvider.

**Comment by mohankumargopalsamy** [comment]
I found solution for my own problem.  There is 2 places useless code goes in. 
1. We uselessly need to give dummy implementations by returning the null for each endpoints, 
2. Need to give Empy token value since its not being used or no way to generate.

Solution below. The library should support it in a better way. In the mean time I can go ahead and use this solution. 

Working Code Below:

import org.scribe.builder.api.DefaultApi10a;
import org.scribe.model.*;

import java.util.Map;

public class ScribeJavaMain {
    private static final String url ="https:// gallery.alteryx.com/gallery/api/v1/workflows/5ff71f96185f0201fc0437e5/jobs/";
    private static final String key ="YOUR_KEY_HERE";
    private static final String secret ="YOUR_SECRET_HERE";
    public static void main(String[] args) {
        DefaultApi10a api = new DefaultApi10a() {
            @Override
            public String getRequestTokenEndpoint() {
                return null;
            }

            @Override
            public String getAccessTokenEndpoint() {
                return null;
            }

            @Override
            public String getAuthorizationUrl(Token requestToken) {
                return null;
            }
        };


        OAuthRequest request = new OAuthRequest(Verb.GET,url);
        request.addOAuthParameter(OAuthConstants.TIMESTAMP, api.getTimestampService().getTimestampInSeconds());
        request.addOAuthParameter(OAuthConstants.NONCE, api.getTimestampService().getNonce());
        request.addOAuthParameter(OAuthConstants.CONSUMER_KEY, key);
        request.addOAuthParameter(OAuthConstants.SIGN_METHOD, api.getSignatureService().getSignatureMethod());
        request.addOAuthParameter(OAuthConstants.VERSION, "1.0");
        String baseString = api.getBaseStringExtractor().extract(request);
        System.out.println("baseString==>"+baseString);
        String signature = api.getSignatureService().getSignature(baseString, secret, "");
        System.out.println("signature==>"+signature);
        request.addOAuthParameter(OAuthConstants.SIGNATURE, signature);
        for (Map.Entry<String, String> entry : request.getOauthParameters().entrySet())
        {
            request.addQuerystringParameter(entry.getKey(), entry.getValue());
        }
        Response response2 = request.send();
        System.out.println(response2.getBody());
    }

}

Dependencies :

<dependency>
    <groupId>org.scribe</groupId>
    <artifactId>scribe</artifactId>
    <version>1.3.6</version>
</dependency>

**Comment by kullfar** [comment]
Hi!

First of all, you are using very-very old version (almost 7 years old). The current version is 8.1.0.
But there was no many changes to OAuth 1.0 part of the ScribeJava.

It will be cool if you could provide a pull request to better support OAuth1.0 (1-legged) with Example class like this https://github.com/scribejava/scribejava/blob/master/scribejava-apis/src/test/java/com/github/scribejava/apis/examples/TwitterExample.java

The main complication will be that I will need test user credentials and test application credentials to run the Example and test provided changes.
