### ISSUE TITLE
MIT License is incorrect

### ISSUE THREAD

**Issue by CodingFabian** [scribejava/scribejava#994]
To ensure Java 7 compatibility, you included 2 classes copy&paste from the JDK. You did include the original license, however this makes your complete package not MIT licensed.
Maybe you revisit your decision to support Java 7, or maybe you do offer a java 8+ branch?

**Comment by kullfar** [comment]
Hm... It's a very interesting point. I need some time to think and to decide.
I have two options, as I understand:
1.Revert commit where I switched code to use these 2 copy-pasted classes.
2.drop java 7 support.

Thanks for pointing this.

**Comment by CodingFabian** [comment]
Another option would be to "reimplement" these classes. `Consumer` is trivial Base 64 is not, but maybe it is possible to import it from another project that implemented base64 under MIT / Apache License

**Comment by kullfar** [comment]
Right. Actually I switched from external dependency (apache commons) to java8 in this commit https://github.com/scribejava/scribejava/commit/8d1527b5f2e6ad797ce9505cee04e2013b5bf67c

**Comment by kullfar** [comment]
And it's Apache license

**Comment by kullfar** [comment]
Anyway, we have
java7-compatibilty vs external dependency

and I hope, java 8 is almost everywhere now. The last try in  Nov 2017 (v5.0.0) was unsuccessful, but it was 3+ years ago

**Comment by kullfar** [comment]
but... java7 has Extended Support Until July 2022. So it can be used by some clients..

**Comment by kullfar** [comment]
So, I will go to apache codec dependency option for at least next couple of years.
Will make changes soon.

**Comment by kullfar** [comment]
ok, that's it
https://github.com/scribejava/scribejava/compare/cd20f57ff1554a6d23a85c3bd5abadb4032956a6...45ad5e422757b409523801fc95d015bfc61d1493

I have added 4 alternatives for Base64
java8 Base64
Apache Commons Codec
and two JAXB (v2 for JRE7 and the latest v3)
ScribeJava will choose any of them to work with.

And I completely removed all classes copy-pasted from JDK8.
